### ISSUE TITLE
FeedbackDialog Motion Specs 

### ISSUE THREAD

**Issue by johnbister** [carbon-design-system/gatsby-theme-carbon#1008]
This issue finalizes/fixes the motion specs discussed #977

I made a few minor tweaks to the OPEN and CLOSE FeedbackDialog prototypes based on feedback from @shixiedesign and @mjabbink 

@mjabbink Can you please confirm that you’re comfortable with the revised timing for the OPEN and CLOSE prototypes shown below? If you approve, I will go ahead and lay out the timing, curve values, and other specs so @jnm2377 can build.

OPEN:
[Open.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5262217/Open.mp4.zip)

![Open](https://user-images.githubusercontent.com/70543333/93821572-5ac36b00-fc24-11ea-923b-051b968161a4.gif)

CLOSE:
[Close.mp4.zip](https://github.com/carbon-design-system/carbon-website/files/5262225/Close.mp4.zip)

![Close](https://user-images.githubusercontent.com/70543333/93821924-f8b73580-fc24-11ea-8e3f-440483d84dc5.gif)

**Comment by johnbister** [comment]
@jnm2377 Thank you!

@jeanservaas Can you take a look at the OPEN/CLOSE sequence below? @mjabbink thought we were in a good place, but wanted your thumbs up too before we moved forward. Thanks!

[FeedbackDialog_v3.mp4.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/5271659/FeedbackDialog_v3.mp4.zip)
![FeedbackDialog_v3](https://user-images.githubusercontent.com/70543333/94064606-8888eb00-fdaf-11ea-84a2-edf7e5655c15.gif)

**Comment by jeanservaas** [comment]
This looks good to me!

**Comment by johnbister** [comment]
@jnm2377 Hey! Looks like we're ready to hand over some motion specs to you.  Here are the **OPEN** and **CLOSE** sequences.

**OPEN:**
![Open_Final](https://user-images.githubusercontent.com/70543333/94472624-9e702480-0190-11eb-90f6-bdaf1651276e.gif)

**OPEN timeline:**
![Open_Timeline](https://user-images.githubusercontent.com/70543333/94472871-0161bb80-0191-11eb-9c95-c129133a1219.png)

**OPEN start/finish values:**
![Open_Values](https://user-images.githubusercontent.com/70543333/94472931-1a6a6c80-0191-11eb-8119-63c10e7cb5c0.png)

**OPEN curve values:**
cubic-bezier(0.4, 0.14, .3, 1) for all curves
![Open:Close Curve ](https://user-images.githubusercontent.com/70543333/94472965-29e9b580-0191-11eb-8685-8e6b74b3f077.png)


***********************

**CLOSE:**
![Close_Final](https://user-images.githubusercontent.com/70543333/94473058-4980de00-0191-11eb-8f6e-15d8f2c489ae.gif)

**CLOSE timeline:**
![Close_Timeline](https://user-images.githubusercontent.com/70543333/94473085-53a2dc80-0191-11eb-8206-c1fdd476b326.png)

**CLOSE start/finish values:**
![Close_Values](https://user-images.githubusercontent.com/70543333/94473109-5ef60800-0191-11eb-820f-10f02cbd078d.png)

**CLOSE curve values:**
cubic-bezier(0.4, 0.14, .3, 1) for all curves
<img width="339" alt="Open:Close Curve " src="https://user-images.githubusercontent.com/70543333/94473195-7d5c0380-0191-11eb-973b-92c5809d3491.png">


*************************
I apologize for the crazy long comment. Please let me know if this breakdown is helpful or if you need any additional information. Thanks!

**Comment by jnm2377** [comment]
Hey @johnbister , I don't quite understand everything in your comment. I made a table that kind of shows exactly how I would be implementing this in CSS. I plugged in what I understood from your comment, but there are some things I still need clarification on. I don't understand the difference between **group** and **box** in your example. Also, I'm not sure what center x and center y are, or what CSS property those would correlate to, so I didn't include them. If you could plug in the missing info or correct anything that is wrong, that would be really helpful. Thanks! 

**OPEN animations**

| ClassName/Element    | property      | duration token | curven token                  | delay | to |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog` (Group)      | width         | ?              | `motion(standard, expressive`) | 0ms   | `320px` |
| `.dialog`   | height        | ?              | `motion(standard, expressive)` | 4ms ? | `436px` |
| `.button-row` | height        | ?              |  `motion(standard, expressive)`    | 12ms? | `4rem` |
| `.button-row` | opacity       | ?              |  `motion(standard, expressive)`   | 12ms  | `1` |

**CLOSE animations**

| Element    | property      | duration token | curven token                  | delay | to |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog` (Group) | width         | ?              | `motion(standard, expressive)` | 30ms?   | `0px` |
| `.dialog`      | opacity | ?              |   `motion(standard, expressive)` | 30ms   | `0` |
| `.dialog`      | height        | ?              | `motion(standard, expressive)` | 37ms ? | `0px` |

**Comment by johnbister** [comment]
@jnm2377 Thanks! I'll use this chart as template for future handoffs.  

Unfortunately, It looks like we're being asked to use a different feedback api called Medallia so let's hit pause on this for now.

**Comment by vpicone** [comment]
@johnbister Medalia is a paid service, the theme has dozens of sites that could still use this feedback component so it’s worth exploring still.

**Comment by mjabbink** [comment]
Yes. Please proceed @johnbister

**Comment by johnbister** [comment]
@jnm2377 I filled in the gaps to the best of my understanding... I'll be going through some js and css tutorials this week to try understand it from your perspective. Ultimately, I'd love to be able to actually help code these things.

**OPEN animations**

| ClassName/Element    | property      | duration token | curven token                  | delay | open value |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog` (Group)      | width         | 12ms              | `motion(standard, expressive`) | 0ms   | `320px` |
| `.dialog`   | height        | 20ms              | `motion(standard, expressive)` | 4ms  | `436px` |
| `.button-row` | height        | 21ms              |  `motion(standard, expressive)`    | 12ms | `4rem` |
| `.button-row` | opacity       |21ms              |  `motion(standard, expressive)`   | 12ms  | `1` |

**CLOSE animations**

| Element    | property      | duration token | curven token                  | delay | closed value |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog` (Group) | width         | 25ms             | `motion(standard, expressive)` | 37ms   | `0px` |
| `.dialog`      | opacity |25ms              |   `motion(standard, expressive)` | 30ms   | `0` |
| `.dialog`      | height        | 25ms              | `motion(standard, expressive)` | 30ms  | `0px` |

**Comment by johnbister** [comment]
@jnm2377 I added an active state to the dialog-container, fixed the launch button color, and smoothed out enter/exit motion.  I wasn’t able to figure out how to reset focus states after submit, but you can see how far I got at: 

https://github.com/johnbister/gatsby-theme-carbon/tree/feedback-motion

Please let me know if you need anything else or have any questions.  Thanks!

**OPEN animations**

| Element    | property      | duration  | curven token                  | delay | open value |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog`      | width         | 120ms              | `motion(entrance, expressive)` | 0ms   | 320px |
| `.dialog`   | height        | 200ms              | `motion(entrance, expressive)` | 40ms  | 436px |
| `.form-container` | top | 240ms | `motion(entrance, expressive)` | 40ms | 0px
|`.form-container` | opacity | 240ms | `motion(entrance, expressive)`| 40ms | 1
| `.button-row` | height        | 120ms              |  `motion(entrance, productive)`    | 170ms | 4rem |
| `.button-row` | margin-top   |  120ms              |  `motion(entrance, productive)`   | 170ms  | 0px |

**CLOSE animations**

| Element    | property      | duration | curven token                  | delay | closed value |
|------------|---------------|----------------|-------------------------------|-------|-------|
| `.dialog`  | width         | 250ms             | `motion(standard, expressive)` | 70ms   | 0px |
| `.dialog`      | height | 250ms              |   `motion(standard, expressive)` | 0ms   | 0px |
| `.dialog`      | opacity       | 250ms              | `motion(standard, expressive)` | 0ms  | 0 |
|`.form-container`| top | 300ms | `motion(standard, expressive)` | 0ms | 200px |
|`.form-container` | opacity | 300ms | `motion(standard, expressive)` | 0ms | 0 |
|`.button-row` | height | 210ms | `motion(standard, productive)` | 120ms | 0px |
|`.button-row` | margin-top | 210ms | `motion(standard, productive)` | 120ms | 4rem |

**Comment by johnbister** [comment]
I'll go ahead and close this.
