### ISSUE TITLE
Proposal to implement 'Feedback Dialog' component on gatsby home pages 

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/gatsby-theme-carbon#1010]
## Detailed description

> Describe in detail the issue you’re having.
'Feedback dialog’ component (wink emoji) don’t appear on the Brand site's (BC & DL) home page and appear only on the internal pages. 

> What did you expect to happen? What happened instead? What would you like to see changed?
It would be a good experience if we can also implement 'Feedback dialog’ component (wink emoji) on the home page as well to get our users feedback.

> What browser are you working in?
Firefox, Chrome

- Screenshots or code
Feedback dialog component:-
![01](https://user-images.githubusercontent.com/38890232/94281515-b9d2f980-ff1c-11ea-8166-a6cd7c9caa0d.jpg)

**Comment by vpicone** [comment]
Not a bug, this is now the default behavior.
