### ISSUE TITLE
H4 Headers: should not have increased line space below

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#102]
![Screen Shot 2019-05-23 at 3 38 11 PM](https://user-images.githubusercontent.com/10566194/58291112-0f1f5980-7d71-11e9-9e54-ee8c6d827b29.png)

https://ibmbrandcenter-preview.mybluemix.net/naming

**Comment by alisonjoseph** [comment]
Looks like this one has been fixed. feel free to re-open if needed.
