### ISSUE TITLE
Feedback and jump to top of page buttons need smaller margins in Mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1024]
The two buttons should get closer to the right edge of the screen and probably closer to the bottom. They are taking up too much space in  the screen canvas.

@aagonzales can maybe investigate the spacing and provide specs to solve this. FYI @jeanservaas 

![Screen Shot 2020-10-08 at 12.44.59 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/feb6c1b8-60a5-4435-8327-7f28a28cf1f1)

**Comment by mjabbink** [comment]
@jeanservaas Check this out in mobile. I think it’s fine in desktop because it hugs the margin. In mobile it’s still the desktop spacing so feels floating in the page too much. Should this hug the mobile margin?

**Comment by mjabbink** [comment]
@vpicone Use whatever the margin is in mobile. It will behave like Desktop which locks to the right margin edge. In mobile it can lock to the right margin edge

**Comment by aagonzales** [comment]
This is a very ugly fast sketch but I would take it down to half of what it currently is 

Current padding shown on left; new proposed padding on right.
![image](https://user-images.githubusercontent.com/11670886/97195219-15411300-1779-11eb-9ab1-241ca278960c.png)

**Comment by mjabbink** [comment]
Thank you @aagonzales

**Comment by mjabbink** [comment]
This was closed 21 days ago yet it’s not on the glass. Is there a reason this is not getting released?

**Comment by aagonzales** [comment]
I see it fixed on the carbon site. It maybe a breakpoint issue. I'm seeing it a phone size but not tablet. Do you think we should do it for the next breakpoint up @mjabbink ?

**Comment by mjabbink** [comment]
They should be sitting on whatever the margins are. In mobile those buttons were previously on a 32px margin instead of the 16px.
