### ISSUE TITLE
Dark - light theme configuration guide

### ISSUE THREAD

**Issue by ridhwaanm** [carbon-design-system/gatsby-theme-carbon#1028]
Hi, 

This is my very first react website. I have zero experience with any languages and found the this theme + gatsby quite user friendly. 

The issue which I have struggled to find documentation on is how to switch between the dark and light theme without editing each component / shadowing the entire theme. I see an indication of this in the styling section but it does not provide the same newbie clarity other sections provide.

Thanks

**Comment by sstrubberg** [comment]
hey @ridhwaanm, we actually have a [PR](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/979) open for this exact issue. Currently though, the only way is how you described. Lots of shadowing and overriding styles. Stay tuned!
