### ISSUE TITLE
Message after running "npx gatsby new ...." is wrong

### ISSUE THREAD

**Issue by ethankoch4** [carbon-design-system/gatsby-theme-carbon#1040]
## Detailed description

> Describe in detail the issue you’re having.

The message you receive after running `npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme`, is incorrect. 

> What did you expect to happen? What happened instead? What would you like to see changed?

It says to run `gatsby develop` but that doesn't actually work. You need to run `yarn dev` or `npm run dev` from here: https://gatsby-theme-carbon.now.sh/getting-started/#first-steps

I think if the line was `yarn dev || npm run dev` instead of `gatsby develop` it would work just fine.

> What browser are you working in?
N/A

installed on mac

## Steps to reproduce the issue

1. Navigate to Terminal
2. run `npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme`
3. `cd my-carbon-site`
4. try `gatsby develop` and note it doesn't work :(

## Additional information

<img width="602" alt="Screen Shot 2020-10-27 at 9 26 54 AM" src="https://user-images.githubusercontent.com/16977711/97323573-901c3380-1836-11eb-8cc5-2c10f3eba61f.png">

**Comment by alisonjoseph** [comment]
Please reopen if this is still an issue.
