### ISSUE TITLE
Update release docs to include sites to update

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1041]
## Update release docs to include list of sites to update 

After releasing an update to the theme we need to ensure the following sites get updated, we should add this to the release checklist so it doesn't get forgotten.

- [ ] Brand center
- [ ] IDL
- [ ] Carbon
- [ ] Event design
- [ ] IBM a11y
- [ ] AI
- [ ] Research
- [ ] w3 / design

**Comment by sstrubberg** [comment]
Dibs on w3/design, Research, and AI.
