### ISSUE TITLE
[search] extend search field in mobile to allow users to enter a term

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#1049]
1. Right now in mobile, it's not possible for users to trigger the typewriter to enter a search term on their phones because the field does not extend wide enough.

2. Mike wanted to try to get the search width onto the grid at the desktop and tablet breakpoints as well. 

### Current

![IMG_2256](https://user-images.githubusercontent.com/43144260/97719098-b0e1c480-1a94-11eb-99e7-60bf3fdde548.PNG)

Please span the search to the left side of the hamburger menu (see below) to make it as easy as possible for users to interact with it.

### Expected

<img width="436" alt="image" src="https://user-images.githubusercontent.com/43144260/97725932-ba6f2a80-1a9c-11eb-81c8-d8427d7ec8f8.png">

## 2. Modify search width to align with grid at all breakpoints.

Align edge of open Search field with the edge of the first tab on the banner at all breakpoints.

### Expected

1312 breakpoint example (do same alignment through tablet)
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/43144260/97809640-add10a80-1c33-11eb-9c41-52ae84df5c18.png">

**Comment by jnm2377** [comment]
@jeanservaas should we re-open this if the search isn't aligning to page tabs or is the full width intentional?
<img width="1792" alt="Screen Shot 2021-01-15 at 1 51 18 PM" src="https://user-images.githubusercontent.com/32556167/104773439-ae5d4580-573a-11eb-9804-5cfbbbd3db28.png">
<img width="1676" alt="Screen Shot 2021-01-15 at 2 00 00 PM" src="https://user-images.githubusercontent.com/32556167/104773449-b3ba9000-573a-11eb-8ebd-6b1e1727c3df.png">

**Comment by jeanservaas** [comment]
Great call @jnm2377 ! Thanks for catching this. I just reopened the issue and I wonder if I missed this while reviewing it or something.

The expected behavior in desktop is this:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/43144260/104780689-c33fd600-5746-11eb-8840-7670e036a2a6.png">

Not this:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/43144260/104780720-d2268880-5746-11eb-8f5f-8b0958b57d76.png">

**Comment by mjabbink** [comment]
Can we get this done please.

**Comment by mjabbink** [comment]
@jeanservaas I was checking on the preview link for the Workplace site and played with the extended search and the issue we need to take into account is the results that span across the entire width. I think we need to spec right side margin to prevent this.


<img width="1209" alt="Screen Shot 2021-02-03 at 8 41 05 PM" src="https://user-images.githubusercontent.com/32881239/106837649-7cb40c00-6660-11eb-9d19-836d9788c075.png">

**Comment by mjabbink** [comment]
@jeanservaas Did you connect with @alisonjoseph on this for specs on width of search result text?

**Comment by vpicone** [comment]
Following up with what @mjabbink mentioned, @jeanservaas the shell sits on top of the grid. Is it tied to that specific anchor point at every viewport width?

And just to make sure, on mobile it expands to hit the nav launch button?
