### ISSUE TITLE
Update Brand ecosystem sites with latest gatsby switcher menu

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/gatsby-theme-carbon#1053]
## Detailed description

> Describe in detail the issue you’re having.

At present following Brand ecosystem sites have old switcher.
- IBM Brand Center
- IBM Watson XG
- IBM Cloud XG
- IBM Services XG
- IBM Security XG
- IBM Research XG
- IBM IT Infrastructure XG
- IBM Developer XG

> What did you expect to happen? What happened instead? What would you like to see changed?
Brand ecosystem sites should be updated with the new switcher (attached is the screenshot of new switcher)

## Additional information
Also:
On new switcher - ‘IBM Brand Center’ link is throwing 404 error page in following site :
- IBM Brand Platform XG

- Screenshots (New switcher)
![new-switcher.jpg](https://images.zenhubusercontent.com/5ae8a3724b5806bc2bd159f8/b6c03346-3cbf-45bf-b479-ded252a8a468)

@sstrubberg @vpicone 

fyi: @kennethhartmann

**Comment by vpicone** [comment]
@rmathur16 Is there a reason you opened this on the theme repo? We don't maintain those projects
