### ISSUE TITLE
Add” Universal Experience“ with LOCK icon to switcher when they launch 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1057]
”IBM Universal Experiences“ site is set to launch next week. Could be delayed but we should be prepared to get their site added to the switcher in the “Practices” section under IBM iX. Needs a lock icon.

I do not know what the url will be at this time but Kelly Renfro or Matt Brothers will.

<img width="359" alt="Screen Shot 2020-11-11 at 6 13 34 PM" src="https://user-images.githubusercontent.com/32881239/98879146-70962500-244a-11eb-9f8d-59199a409c05.png">

**Comment by mjabbink** [comment]
FYI @alisonjoseph Can you coordinate with Kelly Churchill on the date. I can also help communicate for others to updates GT as well.

**Comment by mjabbink** [comment]
Tabled for now. The site now wants to live a bit more incognito for a while.

**Comment by mjabbink** [comment]
@sstrubberg I hear from Jessica you are on the case for the Racial Equity in Design site which should place their site in the “Community” section.

reference image

![Uploading Screen Shot 2020-11-11 at 8.04.46 PM.png…]()

**Comment by mjabbink** [comment]
@sstrubberg Please remove Playbook from the switcher.

**Comment by mjabbink** [comment]
@sstrubberg @alisonjoseph This can be updated in Carbon and IDL among all the other places that share the same switcher content.

**Comment by mjabbink** [comment]
They launched two or more weeks ago.

**Comment by sstrubberg** [comment]
Aren't we saving this until REiD goes public?

**Comment by mjabbink** [comment]
@sstrubberg Not seeing this in IDL or Carbon switcher?

**Comment by mjabbink** [comment]
REiD and UE — should also be included in w3.ibm.com/design
