### ISSUE TITLE
404 page when clicked 'IBM Brand Center' link on new switcher

### ISSUE THREAD

**Issue by rmathur16** [carbon-design-system/gatsby-theme-carbon#1058]
## Detailed description

> On the new switcher 'IBM Brand Center' link is throwing 404 page when clicked from following Brand ecosystem sites:
https://www.ibm.com/brand/
https://www.ibm.com/brand/systems/watson/
https://www.ibm.com/brand/systems/cloud/
https://www.ibm.com/brand/platform/experience-guide/
https://www.ibm.com/brand/systems/developer/

> What did you expect to happen? What happened instead? What would you like to see changed?
'IBM Brand Center' link should go to https://www.ibm.com/brand/

Thanks.

@vpicone @sstrubberg 
Fyi: @kennethhartmann @sadekbazaraa

**Comment by alisonjoseph** [comment]
I'm unable to replicate this error, anyone else?

**Comment by sstrubberg** [comment]
Me either. @rmathur16 can you elaborate on the issue a bit more?

**Comment by rmathur16** [comment]
@alisonjoseph @sstrubberg 
The issue seems to be fixed now but earlier when you were on the below sites
https://www.ibm.com/brand/
https://www.ibm.com/brand/systems/watson/
https://www.ibm.com/brand/systems/cloud/
https://www.ibm.com/brand/platform/experience-guide/
https://www.ibm.com/brand/systems/developer/

On the switcher (see in the attached screenshot) - onclick of 'IBM Brand Center' link was throwing 404 error page.
Thanks.

Screenshot:
![1053.jpg](https://images.zenhubusercontent.com/5ae8a3724b5806bc2bd159f8/470aa834-5995-4968-a6d7-a743c26a8c6e)

**Comment by alisonjoseph** [comment]
Glad its working now, going to close this issue.
