### ISSUE TITLE
[IDL] Color: Specs tab switcher is funky

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/gatsby-theme-carbon#1072]
Something is off with the tabs on the Specifications section:
https://www.ibm.com/design/language/color/#specifications

It should be behaving more like these tabs
https://www.carbondesignsystem.com/data-visualization/color-palettes

![Screen Shot 2020-12-07 at 9.25.41 AM.png](https://images.zenhubusercontent.com/5ae76b2b4b5806bc2bd136f9/03409efa-5592-4911-8713-68ffc0c5c6b2)

**Comment by sadekbazaraa** [comment]
@vpicone curious if this might be a simple fix. Seems to be a bug happening across the board. We're about to implement this feature on the Partner Ecosystem XG and I just noticed the same on the ITI XG: https://www.ibm.com/brand/systems/it-infrastructure/expression/color#primary-colors

Tabs should be white and the continued horizontal bar should be Gray 10. For some reason they're inverted.

![Screen Shot 2020-12-11 at 12.15.03 PM.png](https://images.zenhubusercontent.com/5ae76b2b4b5806bc2bd136f9/fbdede2a-320a-4d67-851d-fa2572f70ae4)

**Comment by mjabbink** [comment]
@vpicone @sadekbazaraa Seems related to this issue as well https://github.com/carbon-design-system/design-language-website/issues/839

**Comment by sstrubberg** [comment]
> @vpicone curious if this might be a simple fix. Seems to be a bug happening across the board. We're about to implement this feature on the Partner Ecosystem XG and I just noticed the same on the ITI XG: https://www.ibm.com/brand/systems/it-infrastructure/expression/color#primary-colors
> 
> Tabs should be white and the continued horizontal bar should be Gray 10. For some reason they're inverted.
> 
> ![Screen Shot 2020-12-11 at 12.15.03 PM.png](https://camo.githubusercontent.com/d7a7e52fcac5538944b04958f1fef24bc5f6c366a17ca3a1b5deeb054e144d46/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3561653736623262346235383036626332626431333666392f66626465646532612d333230612d346436372d383531642d666132353732663730616534)

Found [the fix](https://github.com/carbon-design-system/design-language-website/pull/846). We'll need to do the same to the Brand site.

**Comment by mjabbink** [comment]
and as I mentioned above related to https://github.com/carbon-design-system/design-language-website/issues/839
