### ISSUE TITLE
in Mobile/tablet the “Carbon Design System” does not click to go home

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1073]

**Comment by mjabbink** [comment]
@tw15egan Will this get fixed in Carbon site on the next Gatsby theme update?

**Comment by tw15egan** [comment]
yes we will update the site once the theme has been updated 👍

**Comment by mjabbink** [comment]
Can we make sure this get’s corrected/updated in the Carbon site.

**Comment by mjabbink** [comment]
@vpicone @sstrubberg Now this is happening on IDL on mobile.
