### ISSUE TITLE
Content & code snippet in list should go to the right margin

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1074]
![Screen Shot 2020-12-09 at 11.35.51 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/06ade6f8-6cae-4d8b-b5ab-254ce1e66191)

————
![Screen Shot 2020-12-09 at 11.40.48 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/2c7569ef-f3d6-4207-b961-ea5dde1caa39)

**Comment by mjabbink** [comment]
FYI: @jeanservaas @sadekbazaraa

**Comment by sstrubberg** [comment]
@mjabbink Can i get specs for this using MD and LG screens?
