### ISSUE TITLE
Lock screen in landscape tablet/mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1079]
If you go landscape the page is loosey goosey and when you back to portrait view the page loads smaller and moves all around.

![ezgif.com-gif-maker (1).gif](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/51f7e80b-fae7-4362-8c5a-6df9260e0600)

**Comment by mjabbink** [comment]
![Uploading ezgif.com-gif-maker (2).gif…]()

**Comment by sstrubberg** [comment]
What browser is this in? (i'm having a hard time recreating it)

**Comment by mjabbink** [comment]
@sstrubberg — Chrome. Drives me nuts. Moves around in landscape and when you rotate back to portrait its all screwed up (small, moveable in all directions and cannot get back to proper fit to screen).

**Comment by alisonjoseph** [comment]
Confirmed this is a bug on Chrome's end. Fixed in version 88 (which isn't out yet) https://bugs.chromium.org/p/chromium/issues/detail?id=1150075

Going to close, we can reopen if this is still an issue after latest chrome release.

**Comment by mjabbink** [comment]
Good to know. Thanks for deep diving into this @alisonjoseph
