### ISSUE TITLE
Switcher: I think the links should create new tab when loading site. 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#108]
@vpicone @alisonjoseph @aagonzales @jeoffw Jeannie should be added to this repo.

Do you all have objections to this behavior? It seems in this case it would be nice to create new tab for the sites to load from switcher. This way you do not loose your place. It seems a nice user experience and a good use of tabbing pages in a browser. The DL site does this and me being a user of these sites certainly appreciate it.

**Comment by alisonjoseph** [comment]
I feel like this question comes up often. My opinion tends to be to _never_ to open links in new windows. If a user wants that behavior then they can ctrl-click and do it themselves. I'd say especially with the switcher though if we are opening new windows aren't we defeating the purpose of being able to "switch" between sites?

Interested to hear others opinions though?

**Comment by vpicone** [comment]
I agree with @alisonjoseph, if folks want to open it in a new tab they can long press on mobile, cmd+click, or middle click. It’s a good point about the Switcher motivation as well, switching context generally means not opening a new tab. That said this is a pretty easy thing to implement, if you'd prefer that behavior @mjabbink

**Comment by vpicone** [comment]
Gonna go ahead and close this and we can revisit it as folks use the Switcher
