### ISSUE TITLE
Enhancement[ expressive list]: add expressive list to component library

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/gatsby-theme-carbon#1083]
The "expressive list" pattern is used a lot throughout gatsby sites. There are variations in how the rule is designed, spacing and behavior on tablet, so a component with predefined specs would help consistency. 

examples of the list in use:
- in full width, top nav, pages:
https://www.ibm.com/design/practices/
https://www.ibm.com/design/teams/
https://www.ibm.com/design/impact/

- in pages with a left nav:
https://w3.ibm.com/design/about/overview/
https://w3.ibm.com/design/leadership/overview/
https://w3.ibm.com/design/community/
https://www.ibm.com/brand/architecture
https://www.ibm.com/brand/systems/services/strategy
https://www.ibm.com/brand/systems/it-infrastructure/expression/strategy/
https://www.ibm.com/design/language/philosophy/principles/
https://www.ibm.com/design/language/layout/overview/
https://www.ibm.com/design/language/illustration/overview/ (with a white background)
https://www.ibm.com/able/toolkit/plan (with a white background and a pictogram)

specs excerpts:

<img width="1049" alt="Screenshot 2021-01-05 at 11 56 45" src="https://user-images.githubusercontent.com/51086727/103632600-35493b80-4f4d-11eb-8808-4187080c96d6.png">
<img width="1020" alt="Screenshot 2021-01-05 at 11 57 01" src="https://user-images.githubusercontent.com/51086727/103632608-367a6880-4f4d-11eb-999e-cb86247563b6.png">
<img width="832" alt="Screenshot 2021-01-05 at 11 57 14" src="https://user-images.githubusercontent.com/51086727/103632610-37ab9580-4f4d-11eb-8107-27c692e2a95d.png">

sketch file:
[Expressive list specs_ds3.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/5769401/Expressive.list.specs_ds3.zip)

**Comment by DianaStanciulescu** [comment]
FYI  @vpicone @jeanservaas @mjabbink

**Comment by mjabbink** [comment]
@DianaStanciulescu Beautiful. These will be super usefu/helpful additions to the theme.

**Comment by mjabbink** [comment]
FYI @alisonjoseph @sadekbazaraa

**Comment by DianaStanciulescu** [comment]
I don't know anything about where these new gatsby components stand, they probably need to be prioritized on the dev side.

**Comment by mjabbink** [comment]
@alisonjoseph Can I assume this is in this sprint?
