### ISSUE TITLE
Landing page: In Safari the arrow is not Plex. Good in Chrome

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#109]
https://gatsby-theme-carbon.now.sh/

Safari:
<img width="378" alt="Screen Shot 2019-05-24 at 6 37 34 PM" src="https://user-images.githubusercontent.com/32881239/58374120-39eee680-7f06-11e9-9421-21a782ffcbba.png">

**Comment by vpicone** [comment]
closed with https://github.com/carbon-design-system/gatsby-theme-carbon/pull/118
