### ISSUE TITLE
Update grid to use 16 columns

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1098]
Currently the theme uses a 12 column grid with 25% left padding to mimic a 16 column grid.

### Why do we need to do this?
- When the new [header navigation style](https://gatsby-theme-carbon.now.sh/guides/configuration#navigation-style) for the theme is chosen, it results in a 12 column layout w/ out a left nav. This is incorrect. 
- Carbon is dropping support for 12 columns in next major 2021 release

### Potential problems to solve
- This will likely be breaking change for anyone who has built anything custom.
  - Maybe not if we  can use nested grid, which should be supported in Carbon in the future
- Might be 1000% easier once Carbon supports nested grid? Should we wait?
- Do we need to make a v2 of the theme to release this?
- Migration guide / automation for anyone who needs to upgrade
- Design question - how will our 3 across card layouts work if the left nav is an influence  and not part of the grid?

**Comment by mjabbink** [comment]
@alisonjoseph 12 columns?

**Comment by alisonjoseph** [comment]
This will be addressed with the v11 upgrade, closing as duplicate. 

@mjabbink there is some things going on under the hood with grid we had to do because of lack of nested grid support. Should be gone with the v11 upgrade and the latest grid enhancements.
