### ISSUE TITLE
Image movement from slash design

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#110]
@alison @vpicone 
https://www.ibm.com/design/teams/#find-your-team

This image movement you did for slash design is nice in the right places or site. In addition to slash design, I can see this movement in Brand Center, Design for AI, EDT, Design Research and perhaps the experience sites (Watson, Cloud, Security, Services). Maybe it’s a feature that can be turned on or off because I can image the Carb team NOT wanting this on in Carbon site. I also think NOT in DL since these site or more "productive" oriented.

**Comment by vpicone** [comment]
@mjabbink I really like these animations as well. I'm wary of giving the option to every image, as I think it could be over-used or distracting. Maybe if we supported this collage component it'd be a a great option at that level. 

Another solution is offering some guidance on recommended libraries for achieving this sort of effect in developers' bespoke components they author.

@alisonjoseph do you think the collage is something we would want to make in the next milestone? I can throw together a little addendum to the readme to start assembling library recs.

**Comment by alisonjoseph** [comment]
@vpicone It could very easily be added as a wrapper `<Fade>` component (I think thats sort of what we are doing on /design) that way we could add it with the specific timing we want only to the images we want. 

I think the next milestone needs to be focused on finishing the re-build of the IDL site 😅 but that honestly shouldn't take the entire time.

**Comment by vpicone** [comment]
That's a good point, no need to constrain it to a specific component. Just a helper with default timings to give the same appearance effect across sites.

**Comment by mjabbink** [comment]
I agree maybe too much on every image/page. Maybe just landing pages and in the Gallery (DL) for example

**Comment by vpicone** [comment]
This feature is simple enough to add in a snow flake scenario. I'm not sure this feature would be used responsibly en masse. going to close it out for now.
