### ISSUE TITLE
Add Universal Experiences to switcher with lock icon

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1100]
This was supposed to get added once the site went live. Low priority but at one point it should be added.
https://w3.ibm.com/design/universal-experiences/

**Comment by alisonjoseph** [comment]
@vpicone fyi

**Comment by mjabbink** [comment]
I guess we need to add the lock for this like we did for Brand Center.

**Comment by vpicone** [comment]
@mjabbink I assume it should be under "Practices?"

**Comment by mjabbink** [comment]
yup
 
 
Mike AbbinkExecutive Creative Director,
IBM Brand Experience & Design,
IBM Distinguished Designer
+1 917 291 7516
 
IBM
 
 
----- Original message -----From: Vince Picone ***@***.***>To: carbon-design-system/gatsby-theme-carbon ***@***.***>Cc: Mike Abbink ***@***.***>, Mention ***@***.***>Subject: [EXTERNAL] Re: [carbon-design-system/gatsby-theme-carbon] Add Universal Experiences to switcher with lock icon (#1100)Date: Wed, Mar 31, 2021 8:58 PM      @mjabbink I assume it should be under "Practices?" — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@mjabbink I assume it should be under "Practices?"
