### ISSUE TITLE
Search field is too wide on desktop

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1101]
This [PR](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1050) updated the search styles to stretch across and is correct. Currently however the search is stretching too far to the left. 

What it should look like
![Screen Shot 2021-02-25 at 8 06 07 AM](https://user-images.githubusercontent.com/2753488/109164684-53a70880-7740-11eb-8e27-e28acc85c1c0.png)

**Comment by mjabbink** [comment]
Npt sure what happened there. The preview in PR is looking good.

**Comment by alisonjoseph** [comment]
@vpicone I think we just need to pull latest theme version into Carbon website?

**Comment by mjabbink** [comment]
Theme demo site not right either.
