### ISSUE TITLE
Blockquotes are being rendered in blue text but shouldn't be

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/gatsby-theme-carbon#1102]
## Detailed description
On the **Gatsby theme Carbon** website > [Markdown](https://gatsby-theme-carbon.now.sh/components/markdown#blockquotes-and-citations) page, it shows an example blockquote, where the text is rendered in black (or #161616 to be more precise):

![Screenshot 2021-03-05 at 11 44 43](https://user-images.githubusercontent.com/9316771/110113456-09aacc00-7dab-11eb-8588-24db9e66e64b.png)

![Screenshot 2021-03-05 at 12 07 34](https://user-images.githubusercontent.com/9316771/110113832-95bcf380-7dab-11eb-859d-3cc2ddfb9a51.png)

All well and good. 

But when we use the suggested syntax to create blockquotes in our gatsby-theme-carbon site, the blockquote text is rendered in blue:

![Screenshot 2021-03-05 at 12 08 58](https://user-images.githubusercontent.com/9316771/110113958-ce5ccd00-7dab-11eb-923f-a9ae1b4e23b5.png)

Source: https://pages.github.ibm.com/cdai-design/guidance/voice-and-tone/our-personality

![Screenshot 2021-03-05 at 12 07 19](https://user-images.githubusercontent.com/9316771/110113859-a1101f00-7dab-11eb-825d-2bb4ed22c50c.png)

And I can't work out why this is happening.

The result is obviously not ideal, as blue is commonly used for hyperlinks and some of our users have commented that they thought our blockquotes were meant to be clickable. 

### What browser are you working in?
Google Chrome and Safari

### Steps to reproduce the issue
See this page as an example: https://pages.github.ibm.com/cdai-design/guidance/voice-and-tone/our-personality

**Comment by alisonjoseph** [comment]
Hi @tomwaterton this is likely due to being on an older version of the theme.This update was merged in last summer. https://github.com/carbon-design-system/gatsby-theme-carbon/pull/976

**Comment by tomwaterton** [comment]
Ah, okay. Thanks for the info @alisonjoseph 👍
