### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#112]
@alisonjoseph @vpicone Will this be part of the theme package? Or do the other sites need to build bespoke search as per site?

**Comment by alisonjoseph** [comment]
The icon and styling will be part of the theme, but the sites themselves will need to provide the search functionality if they want to use something other than the free doc search from Algolia. (for now at least)

**Comment by vpicone** [comment]
The pieces are all there for folks to implement search. Like Alison said, setting up actual search requires either using a third party like Algolia. When I took out the default, non-functional search component I added a means for folks to integrate with Algolia or the tool of their choice as well as documentation to the README on how to make that happen. 

Closed via https://github.com/carbon-design-system/gatsby-theme-carbon/pull/94
