### ISSUE TITLE
Update switcher tooltip to “Site switcher”

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1121]
current
<img width="339" alt="Screen Shot 2021-04-29 at 10 42 57 PM" src="https://user-images.githubusercontent.com/32881239/116645837-4541bc80-a93c-11eb-988e-8878cd71107c.png">

change to “Site switcher”

FYI @janchild @alisonjoseph

**Comment by janchild** [comment]
@mjabbink I think `Switch sites` is the better option for this tooltip. It's user-centered and not just a label for what the component is.

**Comment by mjabbink** [comment]
@janchild I’m good with that too.

**Comment by sstrubberg** [comment]
https://github.com/carbon-design-system/gatsby-theme-carbon/commit/74c1fb36e53036477177f75324097a28a619f12d

**Comment by mjabbink** [comment]
in original issue I mentioned in mobile the tooltip is stick and does not go away if you open/use switcher. It just stays there while you scroll through page. It will go away if you click on switcher again or left nav.

**Comment by mjabbink** [comment]
Should we reopen or make the same issue again?
