### ISSUE TITLE
Force a line break in ResourceCard titles or Subtitles

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#113]
For copy & layout purposes it is sometimes necessary to force a line break at a chosen spot in the title or subtitle of a ResourceCard. It doesn't seem to be possible from markdown since the prop is passed in as a string and rendered safely within context.

**Comment by alisonjoseph** [comment]
You're correct, this is not possible currently. I'm not sure of an easy way to implement this, so going to close as won't fix unless you have a suggestion. The width of the text will vary so much at different breakpoints that forcing a line break would be difficult to have it appear correct at all sizes.
