### ISSUE TITLE
Provide option to turn off/disable Switcher

### ISSUE THREAD

**Issue by sid-r-singh** [carbon-design-system/gatsby-theme-carbon#1131]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Request: a configurable way to turn off the switcher like how we can turn off the search

Relating to development only.

### Justification
I had a tough time figuring out how to turn off the Switcher. I request the devs to create an option to disable Switcher in the configuration; just like how to disable search, the documentation says: 
To disable search, set the `isSearchEnabled` option to `false`

**Comment by vpicone** [comment]
Opened https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1132 to resolve this. In the future, reaching out to developers via personal e-mail/twitter will have your request closed without consideration. Thanks for understanding!
