### ISSUE TITLE
No space between text & code when used inside tab

### ISSUE THREAD

**Issue by sid-r-singh** [carbon-design-system/gatsby-theme-carbon#1133]
## Detailed description

Inside tab when I use text & code there is no gap between them. Whereas in general (no tab being used) there exists a gap between text & code (screenshots attached).

### Expected:
Gap between text & code when used inside tab. 
### What happens right now:
There is no gap between text & code when used inside tab. 
### What browser are you working in?
Microsoft Edge

## Steps to reproduce the issue

1. Create a MDX page where text & code is used inside a tab. I have attached my code below
2. Run `gatsby develop` &  see the page in localhost

## Additional information

- Code (that I was working with) : [github gist](https://gist.github.com/sid-r-singh/c4cf8860c778bc77b2a70fee4eb1eb18)
- Screenshots
    #### How code & text within tab appears

![Screenshot from 2021-06-08 08-19-22](https://user-images.githubusercontent.com/68782815/121115436-b37a7880-c832-11eb-99bb-8229ee6c496e.png)

![Screenshot from 2021-06-08 08-19-50](https://user-images.githubusercontent.com/68782815/121115465-bd9c7700-c832-11eb-8d2e-8311e1974d30.png)

#### How code & text should normally appear

![Screenshot from 2021-06-08 08-25-39](https://user-images.githubusercontent.com/68782815/121115785-297edf80-c833-11eb-8e37-656f6f160686.png)

- Notes
As shown in the screenshots, there exists enough gap between text & code when used normally. But when text & code is used inside tab there is no space between them. I thought if I add few empty lines then the space might appear but even after adding 4 empty lines, there was no space observed/created between text & code within a tab.

**Comment by aledavila** [comment]
Hi @sid-r-singh you can just put a <br /> after every block of text and code-block and a space after it. Example below. Alternatively you could wrap the text in a div and give it your own css. The problem here is with markdown and how it works rather than our code. Hope it helps. Let me know if you need additional help. I can also be reached at @aledavila on slack if you need quicker answers.

```The default firewall tool on onRHEL 8 / CentOS 8 servers is firewalld (Dynamic Firewall Manager).
Check if https is already enabled using
<br />

[code block]
