### ISSUE TITLE
Article Card font size option for 20px

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#114]
Need an option for ArticleCard titles  fonts size to be 20px or for that to  be default.
![example-1](https://user-images.githubusercontent.com/10566194/58386634-762e4f80-7fb7-11e9-802a-549bd7afc2d0.jpeg)

**Comment by alisonjoseph** [comment]
👍 duplicate https://github.com/carbon-design-system/gatsby-theme-carbon/issues/107
