### ISSUE TITLE
Newbie wants to shadowing the NextPrevious component. 

### ISSUE THREAD

**Issue by Kiekerti** [carbon-design-system/gatsby-theme-carbon#1141]
## Shadowing the NextPrevious component to local language

> Describe in detail the issue you’re having.

I want to change the NextPrevious component to Chinese. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Poor English, full of respect. 

> What did you expect to happen? What happened instead? What would you like to see changed?

### to Chinese also wanted to change the Next Previous `color` to`$ui-04`
![tada~](https://user-images.githubusercontent.com/23510431/124392475-6b168380-dd28-11eb-953d-1a10d566b939.png)

**Comment by alisonjoseph** [comment]
Hi, we have documentation on shadowing components here https://gatsby-theme-carbon.vercel.app/guides/shadowing/
