### ISSUE TITLE
Latest release shadowing issue

### ISSUE THREAD

**Issue by Palke** [carbon-design-system/gatsby-theme-carbon#1146]
There seems to be an issue related to the component shadowing (Footer, Header) causing that Shadowed components are ignored and instead default props are rendered. 

You can see the issue on currently deployed GTC doc site: https://gatsby.carbondesignsystem.com/

Expected:
![image](https://user-images.githubusercontent.com/54019675/126444217-8ad1069d-3229-42a5-9467-883b2075f432.png)

Current:
![image](https://user-images.githubusercontent.com/54019675/126444260-fb6f713b-0707-4a1d-9b16-85bbbb80ebfe.png)

This issue seems to be related to the v2 GTC as I had the same result updating one of my site.

@vpicone

**Comment by vpicone** [comment]
This issue is also occurring in the Carbon and IDL PRs:
https://github.com/carbon-design-system/carbon-website/pull/2416
https://github.com/carbon-design-system/design-language-website/pull/968
