### ISSUE TITLE
How to modify the switcher links

### ISSUE THREAD

**Issue by anyav77** [carbon-design-system/gatsby-theme-carbon#1149]
## Detailed description

> The site doesn't load after shadowing the component.  It loads forever.  If I comment out the code, I'm getting a black page.

> General issue: please update documentation for the switcher component. 

> Browser: Chrome, Firefox on Mac

> Product: graduate capstone project for Harvard Extension School

[Codesandbox](https://codesandbox.io/embed/carbon-components-react-forked-8vmv2?fontsize=14&hidenavigation=1&theme=dark)
https://codesandbox.io/embed/carbon-components-react-forked-8vmv2?fontsize=14&hidenavigation=1&theme=dark
## Steps to reproduce the issue
1. create Switcher directory inside gatsby-theme-carbon > components
2. add the following code:
`
import React from 'react';
import { SwitcherLink } from 'gatsby-theme-carbon/src/components/Switcher'; 
import { SwitcherDivider } from 'gatsby-theme-carbon/src/components/Switcher'; 
const CustomSwitcher = (props) => (
    <Switcher {...props}><SwitcherLink href="https://somelinks.id">Japan Festival</SwitcherLink>
      <SwitcherLink href="https://somelinks.id">Japan Festival Media</SwitcherLink>
      <SwitcherLink href="https://somelinks.id">Japan Festival Platfrom</SwitcherLink>
      <SwitcherDivider>Technology Stack</SwitcherDivider>
    </Switcher>
);
export default CustomSwitcher;
`

## Additional information
My code is based on this example/issue
[860]https://github.com/carbon-design-system/gatsby-theme-carbon/issues/860

import Switcher from 'gatsby-theme-carbon/src/components/Switcher'; 
![Screen Shot 2021-07-21 at 6 31 10 PM](https://user-images.githubusercontent.com/1045307/126579226-dcfa5cbc-ba20-4e41-b7ff-dd3485ceec9d.png)
![Screen Shot 2021-07-21 at 6 30 42 PM](https://user-images.githubusercontent.com/1045307/126579228-dce1db00-f95e-48d1-a57e-afa91955fa56.png)

- Is it related to the message about the declaration file?
Could not find a declaration file for module 'gatsby-theme-carbon/src/components/Switcher'. '/Users/user/Documents/Gatsby/my-carbon-site/node_modules/gatsby-theme-carbon/src/components/Switcher/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/gatsby-theme-carbon` if it exists or add a new declaration (.d.ts) file containing `declare module 'gatsby-theme-carbon/src/components/Switcher';`ts(7016)
module "/Users/user/Documents/Gatsby/my-carbon-site/node_modules/gatsby-theme-carbon/src/components/Switcher/index"
No quick fixes available

**Comment by anyav77** [comment]
Following up with the update: 
I removed the directory, restarted Gatsby, and I'm able to see the site.  Then, I recreated the Switcher directory with Switcher.js, but I don't see the links updated.  
Am I missing a step?

**Comment by alisonjoseph** [comment]
Hi, sorry for the late response, you should be able to follow the guide for Shadowing here https://gatsby-theme-carbon.vercel.app/guides/shadowing

this is the folder you would copy over to your components directory and edit, you shouldn't have to change any impots https://github.com/carbon-design-system/gatsby-theme-carbon/tree/main/packages/gatsby-theme-carbon/src/components/Switcher

Additional information from Gatsby https://www.gatsbyjs.com/docs/theme-api/#component-shadowing
