### ISSUE TITLE
FeatureCard: In mobile the Square image cannot be just a crop. It will not work on some specific images

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#116]
@alisonjoseph @vpicone 

Is the current featureCard just cropping the large banner image when it switches to mobile breakpoint? If this is at the case we probably need to control this because we cannot always control what those images will be to crop nicely. 

https://zenhub.ibm.com/app/workspaces/brand-center-5cd486c0708e4406ea1ce362/issues/brand/center/124

**Comment by mjabbink** [comment]
So anchor left, centered or right side I reckon

**Comment by vpicone** [comment]
Top and bottom should also be options. @alisonjoseph I think this might be a legit usecase for using emotion.

**Comment by alisonjoseph** [comment]
Do we just want to anchor left/right etc, or do we want the option to upload a separate image for mobile?

**Comment by mjabbink** [comment]
The ideal would be to get specific images for mobile if the need is there. Secondary would be to be able to indicate a choice of anchor left, centered or right. Is it possible do whatever of these options work best?

**Comment by alisonjoseph** [comment]
Yea, we should be able to do that

**Comment by mjabbink** [comment]
Cool. We can create mobile versions of these images and get that issue in Brand Center.

**Comment by vpicone** [comment]
ArtDirection component closed this issue
