### ISSUE TITLE
Aside strategy

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1165]
The aside when longer than the copy it’s next creates a gap. This should be resolved because it cannot currently behave as it does unless it’s only used next to text that occupies more height than the height of the “aside”

Samples
https://pages.github.ibm.com/ai-applications/design/content-guide/graphics/overview

https://pages.github.ibm.com/ai-applications/design/content-guide/getting-started

![Screen Shot 2021-09-28 at 4.55.33 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/cd28711c-5da6-4ec4-a65b-96289c704cd4)

![Screen Shot 2021-09-28 at 4.57.41 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/4e77cabb-6c64-4fa2-b712-2e7a4b4dcb6b)

**Comment by alisonjoseph** [comment]
This is an issue with how they built the page, not something from the theme. If you look at our example page, it doesn't have the same issue. Not sure where their repo is to open an issue specifically for that site.  

![Screen Shot 2021-10-01 at 9.46.53 AM.png](https://images.zenhubusercontent.com/5667369b638e718c995f3b3e/a3293fe7-3941-411c-95b8-3a4f584c8341)
