### ISSUE TITLE
CTA card in lead space not on grid

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1182]
The CTA card in the leadspace is not expanding on the columns correctly. The two below in the page are correct. 
https://www.carbondesignsystem.com/

current:

![Screen Shot 2021-10-25 at 11.28.53 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/62443355-102f-4bfc-8d26-807258ae1721)

expected:

![Screen Shot 2021-10-25 at 11.30.46 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ab982f9a-6be8-4796-baaa-28050b69930e)

**Comment by alisonjoseph** [comment]
this should be fixed now with the grid fix
