### ISSUE TITLE
Add custom prop to open link based components on new tab

### ISSUE THREAD

**Issue by antonio-pbilby** [carbon-design-system/gatsby-theme-carbon#1184]
### Summary

Add a `isNewTab` optional prop to link based components such as `<ResourceCard>` or `<MiniCard>` that changes the behavior of the component to open the link in a new tab.

### Extra resources

I've already implemented a shadowing for the `<ResourceCard>` that can be of useful: `ResourceCard.js` (omitted unchanged chunks of code - full file [here](https://gist.github.com/antonio-pbilby/8fa707c23010b8a3a7d60774b7c6441f)):
```js
export default class ResourceCard extends React.Component {
  render() {
    const {
      children,
      href,
      subTitle,
      title,
      color,
      disabled,
      aspectRatio,
      actionIcon,
      className,
      //the new optional prop
      isNewTab,
      ...rest
    } = this.props;

    //new condition to use <Link>
    else if (isLink === true && !isNewTab) {
      cardContainer = (
        <Link to={href} className={carbonTileclassNames} {...rest}>
          {cardContent}
        </Link>
      );
    } else {
      const isExternalURL = RegExp(/^(https?:)?\/\//g).test(href);

      const hrefPrefixed = withPrefix(href);

      cardContainer = (
        <a
          href={rest.download && !isExternalURL ? hrefPrefixed : href}
          className={carbonTileclassNames}
          {...rest}
          //implements the new prop
          target={isNewTab && "_blank"}
        >
          {cardContent}
        </a>
      );
    }

```

**Comment by alisonjoseph** [comment]
Hi, this was intentionally left out to discourage users from opening links in new tabs. It overrides the default behavior of the web, users can already middle click or command click or right click open in new tab. By forcing a new tab you don’t give them that choice.

The use cases for that behavior are really small: if there’s media playing or they’re filling out a form and you don’t want them to lose their spot. “Surely they don’t want to leave my beautiful site” isn’t a good enough reason.

More: [https://css-tricks.com/use-target_blank/](https://css-tricks.com/use-target_blank/)

Must include icon to be AA compliant:

- [https://webaccess.berkeley.edu/news/can-i-have-links-my-website-automatically-open-new-tab](https://webaccess.berkeley.edu/news/can-i-have-links-my-website-automatically-open-new-tab)
- [https://www.w3.org/TR/WCAG20-TECHS/G200.html](https://www.w3.org/TR/WCAG20-TECHS/G200.html)
