### ISSUE TITLE
"Code blocks" are documented twice

### ISSUE THREAD

**Issue by rodet** [carbon-design-system/gatsby-theme-carbon#1187]
_There are two different pages documenting the similar "code blocks" functionality_

## Detailed description

The [Code blocks ](https://gatsby.carbondesignsystem.com/components/code-blocks) are part of the side navigation between `Caption` and `DoDontExample`. But they are also documented under [the Markdown page](https://gatsby.carbondesignsystem.com/components/markdown#code-blocks). It seems both are very similar - or might be different things, but then why are they called the same? Also the `Code block` navigation entry doesn't follow the camel case format of all other entries in the navigation, which brings confusion about why it is so. My personal recommendation would be to integrate both under the Markdown page for simplicity and clarity.

**Comment by alisonjoseph** [comment]
This is on purpose, the code blocks are on the markdown page because they are a basic markdown element, the information on the code blocks page lists out the additional optional functionality we've aded within the theme to display more options.
