### ISSUE TITLE
Request for additional aspect ratios in the DoDontExample component

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/gatsby-theme-carbon#1188]
### Background info
This issue relates to the [DoDontExample](https://gatsby-theme-carbon.vercel.app/components/DoDontExample) component.

Currently, this component only supports a square aspect ratio (that is, the only value allowed on the aspectRatio property is 1:1).

Here is a screenshot of this component being used:
![Current_aspect_ration](https://user-images.githubusercontent.com/9316771/141089291-54d6560e-d944-43fb-8479-e75282a273dc.png)

Link to this example: https://pages.github.ibm.com/cdai-design/pal/content/content-principles#be-clear-but-concise

### The request
This issue is to request that development work is done so that other aspect ratios are supported.

Input from Mike Abbink: 
> "I think supporting the various aspect ratios would be good for this component as we have some use cases that could benefit from 16:9, 2:1, 4:3 for example."

**Comment by trentlutmer** [comment]
In part of this enhancement, we'll need to add a background color to any of the examples shown. It will help bring better contrast and clarity. There are also spacing issues in a responsive browser setting. The square ratio adds too much to the example or some of the icons overlap. 

Adding the other aspect ratios will help clean this up, but want to ensure these others have been noted.

**Comment by alisonjoseph** [comment]
@jeanservaas @DianaStanciulescu @mjabbink 

Wanted to check in with design on this issue, do we want to add additional aspect ratios for this component? If so, which ones would be appropriate?

**Comment by DianaStanciulescu** [comment]
@alisonjoseph I had no idea only 1:1 is allowed :)). I think all the approved aspect ratios should be allowed: 6:9, 4:3, 3:2, 2:1, 1:1 , as mentioned here: https://www.ibm.com/design/language/photography/tips-and-techniques#aspect-ratio

and maybe also vertical options: 2:3, 1:2, 3:4? although I have not seen those in use so maybe we can leave them out at least for now.

**Comment by alisonjoseph** [comment]
@DianaStanciulescu I believe the way it works now is it will take the size of any children (image or video), but we can only force 1:1 for text. Shouldn't be too bad to add the additional aspect ratios as options.

**Comment by mjabbink** [comment]
I think these cards just follow the aspect ratio rules which Diana mentioned but thus far I’ve only seen 1:1 and maybe a few 4:3 or 3:2.

**Comment by DianaStanciulescu** [comment]
Yep, it would be useful to have the other aspect ratios.
