### ISSUE TITLE
ResourceCard: component not receiving focus in firefox

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/gatsby-theme-carbon#1189]
## Detailed description

> Describe in detail the issue you’re having.

I noticed that the ResourceCard components are not receiving any focus in Firefox. In chrome, they are able to be navigated to via keyboard with a visible focus state.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to be able to tab to this component via my keyboard in all browsers.

> What browser are you working in?

Firefox

## Steps to reproduce the issue

1. Visit https://pages.github.ibm.com/cdai-design/pal/ in FF
2. Notice that you can't tab to the resource cards at the bottom of the page

**Comment by alisonjoseph** [comment]
Looks like the same thing is happening upstream in the Carbon repo for clickable tile
https://react.carbondesignsystem.com/?path=/story/components-tile--clickable

**Comment by jnm2377** [comment]
And for some reason, it shows up on click but not on keyboard.

**Comment by joshblack** [comment]
I believe this is a setting in Firefox, similar to Safari, where you need to enable this behavior for Firefox to focus links.

Here's an answer on StackOverflow that worked for me in FF: https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox curious if you all notice the same thing when adding that setting to your FF config 👀

**Comment by alisonjoseph** [comment]
Thanks Josh, going to close this issue.

**Comment by matthewgallo** [comment]
Awesome, thanks to everyone for checking this out!
