### ISSUE TITLE
Update “Universal Experiences”  to Experience Standards” in the site switcher

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1191]
Current:
<img width="284" alt="Screen Shot 2021-11-18 at 2 01 13 PM" src="https://user-images.githubusercontent.com/32881239/142519687-3348c5ba-d0f8-4eb0-856f-efcd108ba800.png">

Expected:
<img width="263" alt="Screen Shot 2021-11-18 at 6 47 39 PM" src="https://user-images.githubusercontent.com/32881239/142519830-0595734f-4f46-4db6-b393-78ce3b73e50b.png">

**Comment by jnm2377** [comment]
This issue is just to update the Experience name in the Switcher.
