### ISSUE TITLE
The theme page link on the repo page seems outdated

### ISSUE THREAD

**Issue by rodet** [carbon-design-system/gatsby-theme-carbon#1199]
From what I know, the current official location of the Gatsby theme we want to promote is https://gatsby.carbondesignsystem.com/ .

However, the repo page promotes the former now.sh URL. Which one is right?
<img width="286" alt="image" src="https://user-images.githubusercontent.com/343696/146003833-fcd39126-bde8-4fe2-9ca3-ac5364a5cbbf.png">

Also sorry to not provide a PR, but this is a repo setting that only the admins can change as far as I know.

**Comment by alisonjoseph** [comment]
Good catch, updated. (both links should be identical though just as fyi)
