### ISSUE TITLE
Consume Carbon Motion package in website

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/gatsby-theme-carbon#121]
Currently, we are using the old motion variables `$transition--base` and `$carbon--standard-easing` for motion across the site.

We should work on consuming the motion package from `carbon-elements` and standardizing motion across the website. 

As is:
<img width="538" alt="Screen Shot 2019-04-29 at 11 53 03 AM" src="https://user-images.githubusercontent.com/11928039/56919409-5ddd1a80-6a75-11e9-9209-81e8d7f8edf4.png">

To be: 
<img width="631" alt="Screen Shot 2019-04-29 at 11 54 26 AM" src="https://user-images.githubusercontent.com/11928039/56919502-954bc700-6a75-11e9-9b1d-194e0625665e.png">

**Comment by alisonjoseph** [comment]
moved this to the theme repo

**Comment by vpicone** [comment]
We're using the new duration tokens, but using a sass function for specifying the easing curve for a .11s animation is a little intense haha.

**Comment by vpicone** [comment]
We're doing this already
