### ISSUE TITLE
Sample code of Markdow Table is not working

### ISSUE THREAD

**Issue by dasabhisek** [carbon-design-system/gatsby-theme-carbon#1219]
## Detailed description
While adding sample code https://gatsby-theme-carbon.vercel.app/components/markdown#tables to my .md file and try with git remote source Table structure not rendering properly

Node: v14.18.0
npm: 6.14.15

**Comment by dasabhisek** [comment]
What I found that markdown table is transformed but HTML <table ..> don't have any classname `page-table` and that's why styling is different from the example one.

**Comment by alisonjoseph** [comment]
Closing due to no response, please reopen with more details.
