### ISSUE TITLE
InlineNotification `Error: component should have no interactive child nodes.`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#1230]
## Detailed description

In `next` we've observed that the change made in v11 to disallow interactive children in InlineNotification's provides a warning in development environments when used in .mdx files.

> Describe in detail the issue you’re having.

Using inline notification like this:
```mdx
<InlineNotification>

The reusable code component can be found in
[this React storybook](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-api-key-generation-component--with-core-configuration).

</InlineNotification>
```

Results in a very confusing and unhelpful error message that does not point you towards the .mdx usage: `Error: component should have no interactive child nodes.`

This is because the .mdx is placing an interactive link within the children of the component. This is not allowed for accessibility reasons.

> What did you expect to happen? What happened instead? What would you like to see changed?

Some options include:
1. Modify the theme's `InlineNotification` to recreate the InlineNotification from Carbon using the styles and do not provide a `status="log"`
1. Modify Carbon's InlineNotification to allow an escape hatch to include interactive children
1. Use ActionableNotification from Carbon instead, but this does not allow configuring inline links. It would have to be in a button, with a custom click handler provided to facilitate navigation.
1. No longer use links inside InlineNotifications at all

**Comment by craigyu** [comment]
![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25162561/fcf8f4d3-8683-4f65-bc44-23698d7bcca1)
![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25162561/a4c5a0f4-2b54-427a-b921-b6b13c9f920a)

This problem still exists for me :/

**Comment by mateBe95** [comment]
bump up , i got this same in Toast Notification when pass <Link> component as decription.
  "@carbon/react": "1.53.0",

@tay1orjones fyi

**Comment by AustinGitHub** [comment]
I'm seeing the same error @tay1orjones
