### ISSUE TITLE
Accordion: expanded text column width is too narrow. Should span 7 columns. Also bulleted text within expanded copy is very narrow column

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#125]
Current:

![Screen Shot 2019-05-29 at 6 12 20 PM](https://user-images.githubusercontent.com/32881239/58595610-45f8e200-823f-11e9-95d5-b101893dc5df.png)

Above column too wide and bulleted content also getting strangely more narrow

Expected:

![Screen Shot 2019-05-29 at 6 23 05 PM](https://user-images.githubusercontent.com/32881239/58595644-6163ed00-823f-11e9-8fe0-c198201ed41e.png)

**Comment by alisonjoseph** [comment]
The accordion isn't included in the theme, this would need to get fixed on the Brand center website. Also not seeing the ordered list issue in the theme, probably also Brand center specific. 🤔

**Comment by mjabbink** [comment]
The accordion we’ve specified for BC is the same accordion specs that digital team want to use for sitcom. It’s using 16px body vs. 14px that component uses. I think we need to add this to theme because if others use accordion it will look better in this editorial context.

**Comment by vpicone** [comment]
I made an issue on the brand center repo offering guidance/example on how they could actually make this component reusable. If they're unable to do so, we can definitely dedicate time to building it properly after this milestone.

**Comment by mjabbink** [comment]
@vpicone did this happen the correct way? They resolved it visually but not sure if developed the way you would suggest. If not, they should do so for sure. It will be reusable in other Gatsby theme and dotcom theme sites.
