### ISSUE TITLE
fix[website]: Selected state missing from the left side nav (homepage ONLY)

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#126]
## Selected state missing from the left side nav (homepage ONLY)

I moved this from the Carbon repo, but it's something that came up in QA a long time ago for both the IDL and the Carbon sites.

- [ ] reinstate 4px vertical blue bar on homepage (both IDL and Carbon)

- [ ] reinstate gray 20 background highlight on L1 category when it's selected on homepage (Carbon only for now, IDL does not have selected background highlight)

<br>

Homepage is missing the vertical bar and the hightlight:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/f4913140-e7b2-4ca3-b4f8-fda3600fff8f)

<br>

Interior pages still have the vertical bar and the hightlight:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/f04fa82a-dd3c-4e76-8bbc-3b711ce6c914)

**Comment by vpicone** [comment]
Where should the highlighting and vertical bar be for the homepage? Since none of the left nav items are selected I'm not sure what the intended behavior is.

**Comment by vpicone** [comment]
Closed per in-person convo
