### ISSUE TITLE
How to import Stack component?

### ISSUE THREAD

**Issue by billalive** [carbon-design-system/gatsby-theme-carbon#1264]
I am trying to import the `<Stack>` component, so that I can make a `<Form>` on an MDX page, as described [here](https://carbondesignsystem.com/components/form/usage/).

The example given uses `<Stack>` along with several other components. I am able to import the rest of the components:

```
import { Form, TextInput, TextArea, Select, SelectItem, Button } from 'carbon-components-react'
```

But when I try to import `<Stack>`:

```
import { Stack } from 'carbon-components-react'
```

I get this error:

```
Attempted import error: 'Stack' is not exported from 'carbon-components-react' (imported as 'Stack').
```

But `<Stack>` seems to be defined in the same packages all the other carbon components [here](https://github.com/carbon-design-system/carbon/tree/18ce43cf20c85cd80d963fb792ece0961165b318/packages/react/src/components).

Could this be related to https://github.com/carbon-design-system/carbon/discussions/12179?

This seems like a simple fix, just need to get the path correct.

`<Stack>` looks like an elegant way to space these form components, so I look forward to using it.

Thank you!

**Comment by tay1orjones** [comment]
Hey @billalive - this will be possible after #1252 lands.
