### ISSUE TITLE
Update Gatsby Theme

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/gatsby-theme-carbon#1291]
Issue to update Gatsby Theme

Gatsby theme Carbon is referring to a version before Contained List went stable and because of that it was breaking the styles on the website for Contained List in the Component Demo (we found a work around). Issue can be seen in this PR: https://github.com/carbon-design-system/carbon-website/pull/3421

**Comment by eng618** [comment]
@andreancardona I just released 3.1.5 which has the latest carbon installed. Please validate and close this issue if this resolves the concerns.
