### ISSUE TITLE
Modernization Page 404 Error

### ISSUE THREAD

**Issue by johnjauquet** [carbon-design-system/gatsby-theme-carbon#1321]
<!-- Feel free to remove sections that aren’t relevant.

## Detailed description

> Describe in detail the issue you’re having.
404 error on modernization page https://pages.github.ibm.com/csm-playbook/playbook/common/modernization/csm-iss-modernization
> What did you expect to happen? What happened instead? What would you like to see changed?
content on the page
> What browser are you working in?
Chrome
## Steps to reproduce the issue
1. Navigate to CSM Playbook Home
2. Expand Modernization
3. Click Sustainability
4. Click Modernization Journey link in the content

## Additional information

![image](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/141418209/811f9ade-a082-4518-b52b-a01ac6f2bc32)

**Comment by alisonjoseph** [comment]
please re-open with additional details

**Comment by johnjauquet** [comment]
Looks like it is fixed - thank you!
