### ISSUE TITLE
Automate the release process for `gatsby-theme-carbon`

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#1332]
The release process for this package needs to be automated so that any push to the `main` branch will publish a new minor to npm and create a release on GitHub.

This is required so that we can support the workflow of 
1. Carbon releases it's packages `@carbon/react`, etc.
2. `gatsby-theme-carbon` is updated to latest carbon deps and publish an automatic release
3. `carbon-website` can then pick up both the Carbon dependency updates and `gatsby-theme-carbon` updates into a single PR.

The existing tooling, `release-it`, supports a `--ci` option and should be fairly easy to automate.

**Comment by eng618** [comment]
The PR still needs some adjustments, since it's not able to authenticate to GitHub and actually push/publish the release...

**Comment by eng618** [comment]
3.1.7 was auto published
