### ISSUE TITLE
Enable — “IBM AI”  in Switcher on June 6th to link to ibm.com/design/ai

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#143]
<img width="276" alt="Screen Shot 2019-06-04 at 10 13 07 AM" src="https://user-images.githubusercontent.com/32881239/58886152-6dbdcf00-86b1-11e9-93ef-0746423dc588.png">

**Comment by mjabbink** [comment]
@alisonjoseph yes, this should happen as soon as you guys can tackle. It’s up and running.

**Comment by vpicone** [comment]
Closed by #153

**Comment by alisonjoseph** [comment]
Also have two PRs to update in the following sites

IBM Design https://github.com/IBM-Design/design-website/pull/377
Carbon https://github.com/carbon-design-system/carbon-website/pull/1715

**Comment by mjabbink** [comment]
should update DL too if you’re doing these others. Unless that will happen once migrated to Gatsby theme.

**Comment by alisonjoseph** [comment]
@mjabbink It will happen when we update the Gatsby theme, but I can get the links updated at least for now.
