### ISSUE TITLE
Gatsby v5 : code snippet bugs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1439]
Moving over code snippet specific bugs from #1425 in addition to some new ones.

- [x] Remove new hideCode prop added here: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1422 Show more button needs to show/hide by default, the Carbon component should do this out of the box if we can use that. 
- [x] Copy icon isn't visible (color/token is wrong)
- [ ] Can we find a way to not break code snippets that don't specify a language

**Comment by alisonjoseph** [comment]
Hi @muditjuneja thanks for all your help with this so far! Not sure if you have time to take a look at any of the above issues I noticed. Its so close

**Comment by muditjuneja** [comment]
Hey @alisonjoseph I will look into these soon.

**Comment by muditjuneja** [comment]
can you clarify the this - 
`Remove new hideCode prop added here: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1422 Show more button needs to show/hide by default, the Carbon component should do this out of the box if we can use that.`
What else should we cover in this?

**Comment by muditjuneja** [comment]
Hi @eng618 the styles are not being applied properly on the copy button due to the conflicts in styling. I guess, All those webpack warnings when building and starting the dev loop are playing a role here. Do you know what are all these conflicts?

**Comment by eng618** [comment]
> Hi @eng618 the styles are not being applied properly on the copy button due to the conflicts in styling. I guess, All those webpack warnings when building and starting the dev loop are playing a role here. Do you know what are all these conflicts?

No I’m not familiar with that, and the styling isn’t really my strong area. @alisonjoseph is there anyone who can help take a look at this?

**Comment by muditjuneja** [comment]
Yeah that makes sense. Actually there is already a logic that if there are 9 lines of code, it would automatically show the button and hide the code that we changed in the next branch. I can change the defaultValue to `true` which will provide the same behaviour and remove this regression. And if anyone want the other behaviour, they would pass the value as `false`

**Comment by alisonjoseph** [comment]
@muditjuneja oh ok, yes I think having it default to true would be great. thank you!

**Comment by alisonjoseph** [comment]
@muditjuneja I was just looking at this closer and testing locally and realized if I set hideCode=false then nothing actually happens. Trying to figure out the purpose of adding this prop, why would someone want a long code block but no way to "show more"?

**Comment by alisonjoseph** [comment]
@muditjuneja looking at this locally nad the hideCode prop doesn't appear to be doing anything at all, curious why we need this at all? What would be the use-case for someone to not want the show more button for longer code blocks?

**Comment by muditjuneja** [comment]
If there is a code block having more than 9 lines of code then this would come into play. 
This would be useful if someone wants to show the entire codeblock to give the entire context without letting user do anything (or click)

**Comment by alisonjoseph** [comment]
@muditjuneja got it, I just opened a PR with an update to the docs page, I don't believe it is working.

**Comment by eng618** [comment]
This still seems a little clunky and not intuitive... Just thinking this out... what if instead of this boolean logic, we default to always showing the **Show More** button, but if we add a prop `showAll` then it removes the show all button and shows the full code block.


Similar to Caption: https://gatsby.carbondesignsystem.com/components/Caption with the `fullWidth` prop.

@muditjuneja thoughts?

**Comment by muditjuneja** [comment]
fullWidth is also a bool but I think showAll makes more sense as the prop name. Here is the PR for this change - https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1445
Can you review this?

**Comment by alisonjoseph** [comment]
Testing the release against the Carbon website and looks like bash isn't recognized as a language for some reason.
```
```bash
```

<img width="1136" alt="Screenshot 2024-03-20 at 8 51 32 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/2753488/b8327671-c0e7-40c4-9797-c9c38579617c">

**Comment by eng618** [comment]
> Testing the release against the Carbon website and looks like bash isn't recognized as a language for some reason.
> 
> ```
> 
> ```bash
> 
> ```
> 
> 
> 
> <img width="1136" alt="Screenshot 2024-03-20 at 8 51 32 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/2753488/b8327671-c0e7-40c4-9797-c9c38579617c">
> 
> 

Interesting I've defaulted lately to using sh or shell lately

**Comment by eng618** [comment]
It is a supported language though: https://prismjs.com/#supported-languages

**Comment by eng618** [comment]
Actually, looks like we would have to add that manually... they only include these base languages by default: https://github.com/FormidableLabs/prism-react-renderer/blob/c914fdea48625ba59c8022174bb3df1ed802ce4d/packages/generate-prism-languages/index.ts#L9-L23 

```export const languagesToBundle = <const>[
  "jsx",
  "tsx",
  "swift",
  "kotlin",
  "objectivec",
  "js-extras",
  "reason",
  "rust",
  "graphql",
  "yaml",
  "go",
  "cpp",
  "markdown",
```
