### ISSUE TITLE
Gatsby v5: Search is broken

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1449]
Current search is using an old plugin, hasn't been updated in 5+ years.

Look into migrating to [gatsby-plugin-local-search](https://github.com/angeloashmore/gatsby-plugin-local-search)

**Comment by eng618** [comment]
No, I have not tired or looked into that path as of yet.

**Comment by eng618** [comment]
After a quick look looks like the plugin we are using **gatsby-plugin-lunr** has not been updated in 5+ years. We should probably look into converting to use [gatsby-plugin-local-search](https://github.com/angeloashmore/gatsby-plugin-local-search). There we can provide an updated query that will actually index the pages again.
