### ISSUE TITLE
[ImageCard] The implementation seems to be breaking

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/gatsby-theme-carbon#1487]
### Issue
The code is not working properly and poses an error in .mdx. Not sure what the problem is. @alisonjoseph may take a look at this. 
Link: https://gatsby-theme-carbon.vercel.app/components/ImageCard/

**Comment by alisonjoseph** [comment]
blocking work on https://github.com/carbon-design-system/carbon-website/issues/4058
