### ISSUE TITLE
Video component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#15]
- [x] Need to move all styles related to the video component from the `page.scss` to a `video.scss` file. 
- [ ] Custom play button
- [ ] Custom preview image

**Comment by mjabbink** [comment]
for longer videos we’ll need a video player component. Wedding cake would be our own component but in the meantime we need a player with controls to manipulate the video. See the vimeo player we edited to only the controls we wanted. This is great for user.
https://www.ibm.com/design/language/elements/2x-grid-ui

**Comment by mjabbink** [comment]
this is a good page that demonstrates both types of video; long and short.

The long ones would have player component (for now we’ve been using modified vimeo player) for the shorter we use the blue circle play/pause button. Bother are in the page below.

https://www.ibm.com/design/language/elements/2x-grid-ui

**Comment by alisonjoseph** [comment]
closing in favor of https://github.com/carbon-design-system/gatsby-theme-carbon/issues/59
