### ISSUE TITLE
Ordered lists need more spacing

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#187]
If there are more than 9 items in an ordered list we need more spacing

![Screen Shot 2019-06-20 at 11 36 56 AM](https://user-images.githubusercontent.com/2753488/59865873-c8148c00-934f-11e9-985f-2f351de84d36.png)

**Comment by vpicone** [comment]
1. how
1. does
1. github
1. do it
1. test
1. list
1. please
1. ignore
1. nine
1. ten
1. eleven

**Comment by alisonjoseph** [comment]
Actually, this may be an issue in upstream in core Carbon? 🤔
