### ISSUE TITLE
Bug: Caption tag overwrapping 

### ISSUE THREAD

**Issue by abbeyhrt** [carbon-design-system/gatsby-theme-carbon#190]
The `Caption` tag is wrapping when used for small sentences. 

What's it's doing:

![Screen Shot 2019-06-21 at 3 10 32 PM](https://user-images.githubusercontent.com/17281178/59948768-ca054a80-9436-11e9-97c8-53a7c9bea702.png)

Ideal behavior: 

![Screen Shot 2019-06-21 at 3 12 26 PM](https://user-images.githubusercontent.com/17281178/59948843-033dba80-9437-11e9-8ea7-f1e1a51b287a.png)

**Comment by alisonjoseph** [comment]
@jeanservaas can you confirm the correct width for captions? We currently have it set to 4 columns to match what is on Carbon, but they are longer on IDL.

**Comment by vpicone** [comment]
For reference: the open PR (#192) takes the captions from 4 to 6 col. This means they have the same width as body paragraphs until the lg breakpoint where they stay col – shorter than body paragraphs.

**Comment by jeanservaas** [comment]
Yes, 100% follow IDL caption behavior, we did not get this right in Carbon.
