### ISSUE TITLE
Image enhancements

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#193]
Goals:

* More robust styling, not targeting gatsby-resp classes
* Get blur-up effect back
* Allow captions from markdown `![alt tag](./img.png 'This is a caption')`
* Explore reveal animations
* Explore [image zoom](https://github.com/francoischalifour/medium-zoom)
* Mobile vs Desktop selective image src

**Comment by alisonjoseph** [comment]
Closing, we can open more specific issues for future enhancements
