### ISSUE TITLE
List does not obey line length & no indent

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/gatsby-theme-carbon#207]
A few potential styling errors: 
- [ ] Lists (in MDX) do not obey line length limit as other paragraphs do.
- [ ] Long lines should wrap and indent to keep line starting position consistent.

![image](https://user-images.githubusercontent.com/15144993/60408174-77890400-9b83-11e9-8d41-324436c7af18.png)

**Comment by vpicone** [comment]
@shixiedesign this was fixed a few days ago https://github.com/carbon-design-system/gatsby-theme-carbon/pull/205

**Comment by vpicone** [comment]
I'll put out a new release to include the fix
