### ISSUE TITLE
Card components (the component formerly known as ClickableTile)

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#21]
Create a reusable tile component. Determine which options are needed, look at IDL, ibm.com/design, Carbon, IDR, AI sites to make sure it covers all of them.

**Comment by alisonjoseph** [comment]
![Screen Shot 2019-04-30 at 3 29 12 PM](https://user-images.githubusercontent.com/2753488/56991368-1b8f0880-6b5d-11e9-8cf0-c361466353fb.png)
![Screen Shot 2019-04-30 at 3 31 29 PM](https://user-images.githubusercontent.com/2753488/56991369-1b8f0880-6b5d-11e9-975b-adac24c51499.png)
![Screen Shot 2019-04-30 at 3 31 24 PM](https://user-images.githubusercontent.com/2753488/56991370-1c279f00-6b5d-11e9-88f1-1f60ebe754b9.png)
![Screen Shot 2019-04-30 at 3 31 17 PM](https://user-images.githubusercontent.com/2753488/56991371-1c279f00-6b5d-11e9-8ced-375a043b13ec.png)
![Screen Shot 2019-04-30 at 3 30 27 PM](https://user-images.githubusercontent.com/2753488/56991374-1c279f00-6b5d-11e9-9fd1-465a89cc0943.png)
![Screen Shot 2019-04-30 at 3 30 00 PM](https://user-images.githubusercontent.com/2753488/56991375-1c279f00-6b5d-11e9-830a-87cfb1feb5c7.png)
![Screen Shot 2019-04-30 at 3 29 50 PM](https://user-images.githubusercontent.com/2753488/56991376-1cc03580-6b5d-11e9-8cfd-e95ddde47309.png)
![Screen Shot 2019-04-30 at 3 29 34 PM](https://user-images.githubusercontent.com/2753488/56991377-1cc03580-6b5d-11e9-9803-b517f842d5d7.png)
![Screen Shot 2019-04-30 at 3 29 30 PM](https://user-images.githubusercontent.com/2753488/56991379-1cc03580-6b5d-11e9-86fb-43321fac249b.png)
![Screen Shot 2019-04-30 at 3 29 21 PM](https://user-images.githubusercontent.com/2753488/56991380-1cc03580-6b5d-11e9-9b67-932ae22b5365.png)

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/56992856-9a397500-6b60-11e9-95be-533391840929.png)

![image](https://user-images.githubusercontent.com/15822070/56992904-b2a98f80-6b60-11e9-93da-1124aaaaee01.png)

![image](https://user-images.githubusercontent.com/15822070/56992938-cb19aa00-6b60-11e9-91d5-367dc38be7f9.png)

**Comment by alisonjoseph** [comment]
@sstrubberg are those subpage tiles square?

**Comment by alisonjoseph** [comment]
first stab at outlining props needed to cover above use-cases


property | propType | default | required | description
-- | -- | -- | -- | --
children |   |   |   | expecting 32x32px icon/image
href | string |   |   | url (needs to be href for external links and link component for internal)
disabled | bool | false |   | disabled tile
dark | bool | false |   | set to true for dark tile
hidden | bool | false |   | set to true to hide text until hover (only used on IDL homepage currently)
subTitle | string |   |   | subtitle, smaller text above title (only used on IDL homepage currently)
title | string |   |   | card title
aspectRatio | string | 2:1 | yes | sets aspect ratio for the tile, default is 2:1, 1:1, 4:1, 6:1, 1:2, 3:1, 3:2, 4:3, 16:9
icon | string |   |   | default is no icon, choose from, `Launch` `ArrowRight` or `Download`
imageStyle | string | icon | yes | default is icon (expects 32x32 image as child and displays bottom left)fill (displays image behind the tile to fill container with tile in bottom right)top (displays image above tile)background (displays as background of tile, expects aspect ratio to match)
hoverStyle | string |   |   | used with `imageStyle="background"` lighten/darken
caption | string |   |   | shows in bottom left (author, date, readtime, etc)

**Comment by lawhump** [comment]
<img width="1183" alt="Screen Shot 2019-05-01 at 8 54 03 AM" src="https://user-images.githubusercontent.com/5386917/57020664-9a348600-6bef-11e9-8177-8b310b0ad421.png">
<img width="1172" alt="Screen Shot 2019-05-01 at 8 56 05 AM" src="https://user-images.githubusercontent.com/5386917/57020667-9a348600-6bef-11e9-928e-a83db9e53224.png">

**Comment by vpicone** [comment]
@alisonjoseph that looks great, this is gonna be a fun one to build. I think my main concern is with `imageStyle` being a catch all prop for a wide variety of different kinds of tiles. Every time someone wants to add a new type of tile it could turn into a monster component. 

The style with the tile in the bottom right seems like a totally different component when compared to the standard navigation tiles. Tucking everything into that one prop makes requests like "what if the tile is in the top left?" much more of a bummer to keep up with.

**Comment by alisonjoseph** [comment]
Yea, the more I think about it, it might be cleaner to have separate tile components instead of trying to cram everything into one.

**Comment by vpicone** [comment]
Is this closed?

**Comment by alisonjoseph** [comment]
Yep, closing. Will open new more specific issues for any additional card/tiles needed.
