### ISSUE TITLE
ArticleCard rendering issues

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#214]
Documentation site lists `aspectRatio` as a prop, although I'm not seeing it respected in my site when I configure it to one of the listed options.

**Comment by tay1orjones** [comment]
Going to broaden this one a bit to general ArticleCard rendering issues.

We have some long(er)form content we're putting into ArticleCard and it causes rendering issues with `title` and `subTitle`:

![image](https://user-images.githubusercontent.com/3360588/60618156-0de34280-9d9b-11e9-935e-a2278d529915.png)

**Comment by alisonjoseph** [comment]
Looks like this is an error in the documentation, we don't actually have aspect ratio options for this component, the cards are `2x1`. 

Based on the designs above I wouldn't use the article card, it would either be a custom component, or you could probably achieve the above with adding a classname to the column component and some custom styles.

**Comment by alisonjoseph** [comment]
Also, something that we're working on adding to core Carbon is an aspect ratio component https://github.com/carbon-design-system/carbon/pull/3297
