### ISSUE TITLE
Accordion Item Children type class

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#232]
![image](https://user-images.githubusercontent.com/15822070/60997504-92464000-a31c-11e9-9c5a-dafa3bdeb60c.png)

Children probably need body-long-02.

**Comment by alisonjoseph** [comment]
Should be pulling from core Carbon styles here

**Comment by alisonjoseph** [comment]
We don't specify any html/styles by default here. I think if you wrap in a `<p>` tag it will work the way you want.

```
<AccordionItem title='Title 3'>
    
<p>Content Section</p>
    
</AccordionItem>
```

Thoughts @vpicone ? Do we want to set the type token by default for the Accordion content? Either we way need to either update the code or update the docs.

**Comment by vpicone** [comment]
If you want any children to our MDX components to be processed by MDX and receive things like text emphasis or w/e it needs to have whitespace around it and be left aligned. Kind of like in the DoDontExample or any of the image components.

let me know if that doesn't work

**Comment by vpicone** [comment]
Solution is to add white space around the text for proper formatting.
