### ISSUE TITLE
Gallery component enhancements

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#237]
**Internal issue:https://github.ibm.com/brand/design-language/issues/40**

Moved from https://github.ibm.com/duo/website/issues/1223 & https://github.ibm.com/duo/website/issues/1506

> We need to begin to start considering this since the gallery already needs to grow and get updated. At one point it will be nice to be able to search or filter. After DL migration is complete we should talk this one over and plan to make this happen.

here's where we left off with the filters for the gallery.

[IBM_Gallery_filter_study_sb.zip](https://github.ibm.com/duo/website/files/382521/IBM_Gallery_filter_study_sb.zip)

![screen shot 2019-06-17 at 11 56 55 am](https://media.github.ibm.com/user/30208/files/06633e80-90f7-11e9-8e89-5428a2036916)

![screen shot 2019-06-17 at 11 57 48 am](https://media.github.ibm.com/user/30208/files/2abf1b00-90f7-11e9-96f7-dd1a912f9310)

**Comment by jnm2377** [comment]
@jeanservaas @carbon-design-system/brand  is there a sketch file for this? What is the expected UX for this? If I click a tag to select it, and then click it again does it de-select? Or can they only be de-selected through the refresh button? If there are categories selected, does the closed state look the same as when they're unselected? Asking because this is essentially a different variation of our filterable MulitiSelect and the unselected-closed state for that one looks different than the selected-closed state (there are tags that show you how many items you've selected).

**Comment by alisonjoseph** [comment]
@jnm2377 I would reach out to @sadekbazaraa with questions. Might be worth scheduling a meeting to go over this to make sure we have specs/requirements that are dev-ready.

**Comment by sadekbazaraa** [comment]
Hi @jnm2377 — these are all great questions that you've asked above. These sketches were done a  good while back to illustrate the concept. Long before Carbon components were more flushed out as they are to date. The sketch file is at the top of this thread. 

We may have better solutions implemented for filtered searches at this point. @jeanservaas have you come across any examples along these lines?

**Comment by sadekbazaraa** [comment]
Just had a meeting with @jnm2377 and @jeanservaas. Next steps are for me to refine the design further and share back.

**Comment by jnm2377** [comment]
@sadekbazaraa any updates on the design?

**Comment by sadekbazaraa** [comment]
Hi @jnm2377 — the design explorations got pushed further back in our backlog as suggested by @rw-us perhaps it can be resurrected next sprint.

FYI @mjabbink

**Comment by mjabbink** [comment]
@sadek to pick back up for this quarter

**Comment by sadekbazaraa** [comment]
Yup, it's back on the radar. I had a meeting with Rohit, our new UX specialist to look at some of the details like the categories that we're considering and the details of the user flow so we can better pass off for development. The latest designs use a checkbox to filter with vs. tag clouds and should be more in sync with Carbon components.

**Comment by alisonjoseph** [comment]
Going to close, please create a new issue if the gallery search and filter is still needed with design specs. Thanks!
