### ISSUE TITLE
Need to only hide header bar on mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#248]
not wed to this but I thought after huge discussion we settled on keeping bar visible in desktop and hiding in mobile. Correct me if I’m wrong. @vpicone @alisonjoseph Jeannie Servaas as well. Don’t see her showing up in here?

**Comment by alisonjoseph** [comment]
There might be some confusion around correct behavior, tagging @jeanservaas

**Comment by jeanservaas** [comment]
Hey guys, I just circled back with @vpicone about this issue. We had a very long slack thread about this issue and I think we lost some clarity as a result

This is what's happening in the Gatsby theme now, the header bar remains on scroll in mobile like it does in desktop.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/43144260/61398979-bcef4600-a892-11e9-8edf-cc0e54131dfa.png">

It sounds like the desired behavior is for the header bar to go away on scroll in mobile when there are tabs (they will be replace by the tabs). Is this correct? If so, @vpicone says he has no problem making that change.


This is what IDL does it looks like...
<img width="504" alt="image" src="https://user-images.githubusercontent.com/43144260/61399199-40a93280-a893-11e9-9486-cc982f794881.png">

**Comment by vpicone** [comment]
I have just two small concerns:

1. The language of the shell usage guidelines seem to indicate the header should always be present
> The header spans the full width of the viewport and is the topmost element in the browser window. Header elements are persistent throughout the product experience.
2. _some_ pages would have access to the main navigation at all times (pages without tabs) and other pages would require an extra swipe gesture (tabbed pages). This seems like an inconsistant UX

**Comment by vpicone** [comment]
For the first one, that would make the current desktop implementation incorrect.

**Comment by alisonjoseph** [comment]
from @mjabbink in #328 

> I’m pretty confident we settles to have header bar hide on scroll in mobile but remain in desktop.

**Comment by mjabbink** [comment]
Where I thought we landed is what Carbon in now in mobile—top bar hides on scroll consistently. And tabs when appropriate are sticky. This was to maximize real estate in mobile.

In desktop we though to keep the shell present at all times. The same sticky tabs would be under the top bar which is always visible. More real estate so keep the main nav bar present. 

In that long Slack aftervdebate we all agreed maintaining a consistent pattern within each experience was important

**Comment by mjabbink** [comment]
To hide top bar in mobile (consistently) is extremely common pattern. IBM dot does and will continue this pattern. 

In desktop it’s important to keep it visible. Desktop is primary use case.

**Comment by mjabbink** [comment]
It’s just like this in mobile:
https://www.carbondesignsystem.com/
