### ISSUE TITLE
Image component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#249]
We need to be able to define mobile specific images in a way that makes sense in markdown. Needs to work for card components and standalone images.

**Comment by emyarod** [comment]
@alisonjoseph is there a specific page/specific images I can use to test solutions for this?

**Comment by alisonjoseph** [comment]
So I just realized that IDL has some images replaced by two images on mobile. 
https://www.ibm.com/design/language/elements/pictograms/

Look at this image under corners at desktop and mobile.
<img width="1080" alt="Screen Shot 2019-07-23 at 3 21 13 PM" src="https://user-images.githubusercontent.com/2753488/61744694-8b2c2280-ad5d-11e9-9cd2-5b624b5a2e1a.png">

We could push back on this and combine the two images into one stacked on top of the other if we need to.

**Comment by emyarod** [comment]
@alisonjoseph it looks like the current IDL site has two different sections with different images, and they pick which section to display with media queries

**Comment by emyarod** [comment]
closed by https://github.com/carbon-design-system/gatsby-theme-carbon/pull/294
