### ISSUE TITLE
Explore live code snippets behavior and design

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#250]
Need design input on displaying errors and perhapse a new container component that handles variable component contents.

**Comment by vpicone** [comment]
This work is being explored in carbon-website for now. https://github.com/carbon-design-system/carbon-website/pull/561

May become a theme component in the future

**Comment by apdrsn** [comment]
Hi @vpicone 
Will the live code component be available in the Gatsby theme?
