### ISSUE TITLE
Spacing/vertical rhythm refactor

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#252]
We have multiple bugs/issues around spacing, need to sync up w/ @jeanservaas and @sadek to make sure spacing above/below components and headings are correct. Need to look at the site/components as a whole and not just individually.

**Comment by alisonjoseph** [comment]
We have a meeting planned for Tuesday 7/30 to solve this. 

@abbeyhrt would it be possible for you to create a demo page in the theme with al(as many as possible) variations on components before/after headings, paragraphs etc prior to this meeting? We don't need to merge it in, we can keep it in a draft PR / branch, but just somewhere we can work from and see things.

**Comment by vpicone** [comment]
Adding #271 to the list of review needs. Spacing in and among lists needs to be better defined when they contain things like code snippets or images.

**Comment by abbeyhrt** [comment]
@alisonjoseph Sorry i didn't see this earlier! But yes, I can get that done ASAP and definitely before Tuesday 7/30

**Comment by vpicone** [comment]
Adding this here for discussion: https://csswizardry.com/2012/06/single-direction-margin-declarations/

Definitely worth the read before we discuss the sort of design direction would be most scaleable

**Comment by vpicone** [comment]
Another great resource: https://every-layout.dev/layouts/stack/

**Comment by rcwakelin** [comment]
@alisonjoseph @vpicone Is this closed?

**Comment by rcwakelin** [comment]
Adding Matt @mattrosno to chain

**Comment by vpicone** [comment]
closed by #373
