### ISSUE TITLE
Hover-over icon on H2 clipped on mobile

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#253]
![image](https://user-images.githubusercontent.com/15822070/61389698-f6b65180-a87e-11e9-8202-e3a9cd5fa662.png)

**Comment by alisonjoseph** [comment]
There is no "hover" on mobile, should we just remove this icon at that breakpoint?

**Comment by sstrubberg** [comment]
> There is no "hover" on mobile, should we just remove this icon at that breakpoint?

works for me.
