### ISSUE TITLE
Next/Prev broken depending on tabbed page title

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#255]
We have a section/folder `design-system`, within are three pages: `about`, `start developing`, `start designing`. 

If these tabbed pages have the same title, `title: Design System`, the next/previous links do not resolve properly. If the titles are different from one another, the next/previous buttons work as expected.

**Comment by alisonjoseph** [comment]
Was just coming here to make this same issue. Right now we are limited and need the tab and page title to match, but thats not ideal.

**Comment by vpicone** [comment]
closed with #278
