### ISSUE TITLE
Left Nav duplicate selection when similar page titles

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#265]
When two left nav/pages in a section have similar titles, like`/components/list-builder` and `/components/list`, the nav applies selected state to more than one item at a time.

When `list-builder` is selected, the nav improperly highlights both `list` and `list-builder`

![Screen Shot 2019-07-19 at 9 05 42 AM](https://user-images.githubusercontent.com/3360588/61541141-b1239100-aa04-11e9-848b-543756388a3a.png)

The nav behaves as expected when `list` is selected

![Screen Shot 2019-07-19 at 9 08 35 AM](https://user-images.githubusercontent.com/3360588/61541192-d1ebe680-aa04-11e9-8b3a-af9790ed860a.png)

**Comment by SilverFox70** [comment]
We are seeing similar behavior on the Brand Center site, although we are currently using 1.5.0

**Comment by tay1orjones** [comment]
I'd like to provide an additional test case for this. Below is the behavior we're seeing with 4 items containing the same `UI shell` substring. I added the numbers for clarity on which is selected:

| `#1` selected | `#2` selected | `#3` selected | `#4` selected |
| - | - | - | - |
| ![1](https://user-images.githubusercontent.com/3360588/62388293-89fbb200-b522-11e9-9ed4-607fe21c7060.png) | ![2](https://user-images.githubusercontent.com/3360588/62388294-89fbb200-b522-11e9-9492-15ee9be27e0c.png) | ![3](https://user-images.githubusercontent.com/3360588/62388295-89fbb200-b522-11e9-89e3-7f8fc734c293.png) | ![4](https://user-images.githubusercontent.com/3360588/62388296-89fbb200-b522-11e9-8ef5-8cb63b1c971c.png) |

**Comment by vpicone** [comment]
@tay1orjones thanks for the extra case. We're in the midst of migrating the idl and carbon sites over but this ones definitely a priority.
