### ISSUE TITLE
Accordion Spec

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#266]
Per Mike's feedback..

Currently looks like this..

![image](https://user-images.githubusercontent.com/15822070/61543017-470ceb00-aa08-11e9-8188-808f681b3695.png)

Needs to looks like this..

![image](https://user-images.githubusercontent.com/15822070/61543077-61df5f80-aa08-11e9-8d2e-69d9715404c4.png)

**Comment by alisonjoseph** [comment]
@sstrubberg did you want to contribute this fix back to the theme? 🙏

**Comment by alisonjoseph** [comment]
I think this has already been fixed.
