### ISSUE TITLE
Internal anchor links: when you copy/paste an anchor link, the page does not scroll to the correct position on load

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#275]
For example, if I send someone this as a link: 
https://www.ibm.com/design/ai/fundamentals#design-factors-for-ai-4

And they open in new tab, they end up with:
<img width="1109" alt="Screen Shot 2019-07-24 at 9 34 32 AM" src="https://user-images.githubusercontent.com/10566194/61811492-6b950880-adf6-11e9-980e-fc27fc44da77.png">

**Comment by vpicone** [comment]
@SilverFox70 the AI site is using an older version of the theme. If you can, use [the theme's demo site](https://gatsby-theme-carbon.now.sh) for reproductions.

Linking is fixed as of #186 last month
