### ISSUE TITLE
Grid component page: need hairline gap between images in the "no gutter" sample.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#301]
the image you’re using may not be the best choice to demonstrate what you’re showing. I recommend an image or something with less activity inside the image.

**Comment by alisonjoseph** [comment]
@jeanservaas do we need to update the grid code in the core Carbon library to add this gap for no-gutter? Or is this a website-only interpretation?

**Comment by vpicone** [comment]
Closing this out for now since Carbon doesn't have a hairline gap in the grid
