### ISSUE TITLE
Feature cards should support other aspect ratios

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#304]
Right now we hard code 1x1, but carbon uses 2x1 on the home page for their feature cards.

**Comment by mjabbink** [comment]
we should also have 16:9 and maybe 4:3. These are the aspect ratios we lean on very heavily. No other aspect ratios are recommended unless the above do not work or there needs to be fluid height

**Comment by vpicone** [comment]
In the past year, there hasn't been any demand for this feature and teams have figured out better ways of handling aspect ratios for feature cards at the site level.

**Comment by mjabbink** [comment]
Are they using the above aspect ratios? If not what they’ve done is wrong.
