### ISSUE TITLE
Typeface page: resource card type needs better breaks

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#308]
current:

![File (52)](https://user-images.githubusercontent.com/32881239/62230396-b632f980-b38f-11e9-9b54-bb2d3594ce8f.jpg)

——————

expected:

![File (53)](https://user-images.githubusercontent.com/32881239/62230413-be8b3480-b38f-11e9-8c51-c2ac46992a8b.jpg)

**Comment by alisonjoseph** [comment]
moved to the theme repo so we can adjust the card spacing / allow for breaks here.

**Comment by mjabbink** [comment]
This was opened on July 31. That was **6 months** ago. Please can we get this one done.

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/76222421-90ed5000-61e8-11ea-9f1a-56f845735806.png)

This looks resolved. I'm at https://www.ibm.com/design/language/typography/typeface
