### ISSUE TITLE
Homepage component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#31]
@vpicone to add details

**Comment by vpicone** [comment]
The Homepage template should be able to be overridden entirely by the user, however it should accept some default props that offer an out-of-the-box shadowing opportunity.

Certain components need to run the full width of the visible page: the `Callout` and `Banner` components in particular.

The rest of the content of the Homepage should be controlled with the same sort of mdx as the rest of the pages. The same core Layout component will be used to provide the wrapper. The DOM of the Homepage will look roughly as follows. 

```yaml
Banner #full-width
Callout-1 #full-width
Main Content (MDX) from `/pages/index.mdx` #padded
Callout-2 #full-width
Footer #padded
```
