### ISSUE TITLE
Dependencies warning while installing gatsby-theme-carbon

### ISSUE THREAD

**Issue by lalasmuathasim** [carbon-design-system/gatsby-theme-carbon#310]
Hi i have following dependency warning while doing 

`npx gatsby new gatsby-theme-carbon https://github.com/carbon-design-system/gatsby-starter-carbon-theme`

> warning gatsby > @reach/router > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> warning gatsby-theme-carbon > gatsby-plugin-sharp > potrace > jimp > @babel/polyfill@7.4.4: �🚨 As of Babel 7.4.0, th
> package has been deprecated in favor of directly

And

> [3/4] Linking dependencies...
> warning "gatsby-theme-carbon > @mdx-js/mdx > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "gatsby-theme-carbon > @mdx-js/mdx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "gatsby-theme-carbon > carbon-components-react@7.4.1" has incorrect peer dependency "carbon-components@10.3.1".
> warning "gatsby-theme-carbon > carbon-components-react@7.4.1" has unmet peer dependency "carbon-icons@^7.0.7".
> warning "gatsby-theme-carbon > gatsby-plugin-react-helmet@3.1.3" has incorrect peer dependency "react-helmet@^5.1.3".
> warning "gatsby-theme-carbon > gatsby-plugin-emotion > @emotion/babel-preset-css-prop@10.0.14" has unmet peer dependency "@babel/core@^7.0.0".
> warning "gatsby-theme-carbon > gatsby-plugin-sass > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
> warning "gatsby-theme-carbon > gatsby-plugin-emotion > @emotion/babel-preset-css-prop > @emotion/babel-plugin-jsx-pragmatic@0.1.3" has unmet peer dependency "@babel/core@^7.0.0"

What should i do to eliminate these warning and continue

**Comment by vpicone** [comment]
@lalasmuathasim those warnings are just warnings, not errors. In addition, they're not from us but from some of our dependencies. Just ignore them and carry on.
