### ISSUE TITLE
Configuration page - Letters touching

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#318]
![image](https://user-images.githubusercontent.com/15822070/62648471-7aaca800-b918-11e9-9c9f-c9b0b81d19d1.png)

The letters are touching here. Is that expected?

**Comment by alisonjoseph** [comment]
We're using the `display-01` token here. @jeanservaas is this an issue? would be something we'd need to update in the core Carbon type pacakge.

**Comment by jeanservaas** [comment]
Awwww that's a ligature! It's intentional. That's an expected behavior. It's something you see a lot in good editorial but not much online. Very nice to see.
