### ISSUE TITLE
Pages with Tabs-NextPrev breaks

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#324]
![image](https://user-images.githubusercontent.com/15822070/62732797-db0c1a00-b9ea-11e9-810f-c3d8426d0201.png)

The previous tile gets a link to Home and the next tile gets a mashup of the 2nd tab name and the first page title in the YAML.

**Comment by jnm2377** [comment]
@sstrubberg is this still an issue? I am not seeing it happening in the Gatsby theme
