### ISSUE TITLE
Homepage callout type too big

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#326]
Staging:

![IMG_3853](https://user-images.githubusercontent.com/32881239/62734320-5a7b0700-ba46-11e9-865f-b397d28e45f1.JPG)

Expected:
![IMG_3849](https://user-images.githubusercontent.com/32881239/62734300-4b945480-ba46-11e9-8e9c-42e67b72300c.JPG)

**Comment by mjabbink** [comment]
oops, I thought I was in IDL repo. My bad

**Comment by alisonjoseph** [comment]
@mjabbink you were, I moved it because this callout component is a global thing 😄
