### ISSUE TITLE
Mobile: top header bar hides on scroll

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#328]
@alisonjoseph 
I’m pretty confident we settles to have header bar hide on scroll in mobile but remain in desktop.

**Comment by vince** [comment]
Wrong Vince!

**Comment by mjabbink** [comment]
Oops!

**Comment by alisonjoseph** [comment]
Thanks for the clarification! Was just wondering about this one 😄

**Comment by alisonjoseph** [comment]
duplicate #248
