### ISSUE TITLE
Navigation bugs/enhancements

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#33]
- [ ] Need the ability to have a disabled item in navigation (see live IDL site)
- [x] Top level page loses active state when there are 2 or more tabs selected
- [ ] Nav accordion needs to be able to be open by default
- [x] Nav should be closed on mobile by default

**Comment by vpicone** [comment]
Couple other enhancements:

1. Left nav items should persist expanded state between page navigation.

![Screen Recording 2019-05-16 at 8 21 59 PM](https://user-images.githubusercontent.com/4078018/57897256-9ae93100-7819-11e9-89a3-bed234f9537f.gif)

2. Consider not scrolling all the way to the top if the nav isn't stuck.

**Comment by josiahayres-ibm** [comment]
Another related issue with navigation on Safari _Version 12.1.1 (14607.2.6.1.1)_

Icon positions are not updated when the navigation list is expanded. Position is correctly updated only when user scrolls:
 
![ScreenRecording20190612at5-2](https://user-images.githubusercontent.com/24281643/59325504-6a70b600-8d37-11e9-9031-42237bf2e3b3.gif)

**Comment by vpicone** [comment]
@josiahayres-ibm this is an issue in UI-shell in carbon, I opened an issue for this 9 days ago.

https://github.com/carbon-design-system/carbon/issues/2928

**Comment by tay1orjones** [comment]
I just opened an issue that could probably be contained here, #265 

I searched issues for `nav` instead of `navigation` and missed this issue.

**Comment by alisonjoseph** [comment]
Thanks for making the issue @tay1orjones we knew about that one, but I guess never made an issue
