### ISSUE TITLE
bug(Link): Link font size is incorrect

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/gatsby-theme-carbon#334]
An embedded link is too small:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/44656921/62980591-9e765f00-bdec-11e9-87d5-0a9e6ef6e199.png">

Font size is 0.875rem, while body copy is 1.5rem.

**Comment by connor-leech** [comment]
Body copy:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/44656921/62980678-d8476580-bdec-11e9-8969-b8482cddf910.png">

Link component:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/44656921/62980702-e39a9100-bdec-11e9-80b9-756f391f3bde.png">

**Comment by alisonjoseph** [comment]
Weird. I'm not seeing this issue in the theme but I am seeing it on the new Carbon site. 🤔 

opened a PR that I think will fix

**Comment by alisonjoseph** [comment]
@connor-leech no need to assign anyone to issues, we will self-assign when we start working on stuff

**Comment by alisonjoseph** [comment]
this was fixed!
