### ISSUE TITLE
Site titles too close to hamburger 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#355]
Current IDL and Gatsby theme seem correct but all site using theme are too close? Ai, IDL, IBC, IDR

![38F908A9-79A4-4FAF-B754-520A031AECE2](https://user-images.githubusercontent.com/32881239/63205653-b14f9480-c075-11e9-9af5-85893f282405.jpeg)

![0FE40361-DA97-496F-9058-DEDF545FAAC4](https://user-images.githubusercontent.com/32881239/63205654-b1e82b00-c075-11e9-9c95-8f380c55b9e9.jpeg)

![1530902E-C564-4923-859B-EF06A2B8BCA5](https://user-images.githubusercontent.com/32881239/63205655-b1e82b00-c075-11e9-80b2-9fcba6fb5144.jpeg)

**Comment by vpicone** [comment]
@mjabbink we haven’t released the update yet. If it’s correct on the theme site, it’ll get fixed in the theme sites once we publish a release and the site updates to that release.
