### ISSUE TITLE
Left nav: Keep homepage nav opened if already opening coming from another page with nav opened.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#358]
not sure possible but would be nice not to have to open the nav again if you went back to homepage.

**Comment by jnm2377** [comment]
I'm not sure I understand what you're asking for here. Can you show a visual example of what you expect?

**Comment by vpicone** [comment]
Clicking the logo will take you back to the home page

**Comment by mjabbink** [comment]
This was resolved I think
