### ISSUE TITLE
Body text width: some areas where it seems not to span usual width in Ai site. Not sure if Gatsby of specific to Ai site

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#359]
https://www.ibm.com/design/ai/ethics/explainability

Looks like the text has room to be longer but something preventing it from going wider.

<img width="829" alt="Screen Shot 2019-08-18 at 2 43 17 PM" src="https://user-images.githubusercontent.com/32881239/63228802-a3f5ef80-c1c6-11e9-88f5-103d03c3b37a.png">

**Comment by alisonjoseph** [comment]
There is a bug with paragraph spacing within columns. I believe it will be fixed when this PR is merged, but I will double check its the same issue. https://github.com/carbon-design-system/gatsby-theme-carbon/pull/350
