### ISSUE TITLE
Anchor links should be same color as intro text and needs more spacing above anchor links

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#369]
@alisonjoseph and Jeannie Servaas

![Screen Shot 2019-08-22 at 2 04 33 PM](https://user-images.githubusercontent.com/32881239/63539453-2133a400-c4e8-11e9-8910-5ca196616539.png)

**Comment by alisonjoseph** [comment]
👍 moving this to the theme repo to make sure this fix makes it into all sites
