### ISSUE TITLE
Tab component: Height and type size should match content switcher

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#380]
@alisonjoseph @jeannie (I cannot see Jeannie here?)

The height and type size should match the content switcher

<img width="852" alt="Screen Shot 2019-08-28 at 12 02 25 PM" src="https://user-images.githubusercontent.com/32881239/63875424-6b59d100-c991-11e9-8a59-b8c74ee6963a.png">

**Comment by mjabbink** [comment]
@alisonjoseph status on this?

**Comment by alisonjoseph** [comment]
@jeanservaas is there an updated spec for tabs for the website?

**Comment by mjabbink** [comment]
Digital team specs

**Comment by mjabbink** [comment]
@alisonjoseph @jeanservaas

**Comment by mjabbink** [comment]
Can we resolve this @alisonjoseph @jeanservaas Issue first created Aug 28

**Comment by mjabbink** [comment]
This tab design (with blue line) should either be removed from Gatsby and we commit to the black ones used in IDL. And for this blue line tab we need to add an option so the height matches the black tab which I think is 48px. The one in Carbon is only in one size which is 40px. @jeanservaas correct me if I’m wrong.

**Comment by jnm2377** [comment]
Can this be closed since we're switching to the black content switchers like the IDL site?

**Comment by alisonjoseph** [comment]
closing, duplicate #478
