### ISSUE TITLE
LeftNav/Tabs active selection bugs

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#386]
Continuing problems we're seeing with the left nav selection states:

#### 1. Duplicate selection when page names are similar (similar to #44)
  - ![image](https://user-images.githubusercontent.com/3360588/63955611-99e7b280-ca4a-11e9-8d83-7e06bc761048.png)
</details>

#### 2. Single pages with tabs lose left nav selection when a tab non-first tab is selected (similar to #168)
  - > First tab selected, has appropriate active state:
![image](https://user-images.githubusercontent.com/3360588/63955784-e59a5c00-ca4a-11e9-96f5-5dd1a1d7d082.png) 
  - > Second tab selected, _does not_ have appropriate active state:
![image](https://user-images.githubusercontent.com/3360588/63955880-0ebaec80-ca4b-11e9-843f-b63d4dbc3879.png)

**Comment by ENG618** [comment]
Same issue occurs when there is a subfolder in **pages/**.  i.e. **pages/notes/myNewNote**

The nav will be created but, the entire section is active as below image depicts 

![image](https://user-images.githubusercontent.com/3827863/64884911-cf86c100-d630-11e9-98f4-f2e4760560b9.png)

**Comment by vpicone** [comment]
@ENG618 is this still an issue for you? We made some changes to the way these are handled.

**Comment by ENG618** [comment]
@vpicone no seems to be resolved.

**Comment by SimonFinney** [comment]
@vpicone I've observed this issue still existing when pages are named the same, but fall under separate sections - here's an example of it on the Carbon Design System:

<img width="1680" alt="Nav" src="https://user-images.githubusercontent.com/3846874/79435668-dc550400-7fc7-11ea-85e0-99231ee55831.png">

**Comment by vpicone** [comment]
Ah the issue that never ends thank you @SimonFinney will take a look at it!

**Comment by tay1orjones** [comment]
We're also experiencing an issue where tabbed pages get sent to 404 occasionally when the titles are similar. This is for https://pages.github.ibm.com/ai-applications/design/

Here's the bug report, [ai-applications/design#8](https://github.ibm.com/ai-applications/design/issues/8):

>To recreate:
>Open this page - https://pages.github.ibm.com/ai-applications/design/team/tools-and-resources/tools
>Click on Resources tab
>Click on Tools tab = 404 - it's pointing to https://pages.github.ibm.com/ai-applications/design/team/tools-**and-tools**/resources/
>Designer toolkit doesn't work either. https://pages.github.ibm.com/ai-applications/design/team/tools-**and-designer-toolkit**/resources/
>
>Is appending the wrong url to the tab link for some reason.
