### ISSUE TITLE
Component Request – image example card 

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/gatsby-theme-carbon#394]
In the IDL color UI page, there were these cards that opened up images in a modal (like gallery images). Could this be a component we can use elsewhere? Trying to get it to work on a page I'm working on but no luck

<img width="864" alt="Screen Shot 2019-09-03 at 4 02 35 PM" src="https://user-images.githubusercontent.com/47458576/64209092-3fdd5780-ce65-11e9-8dca-bf78af3b9d8a.png">

**Comment by mjabbink** [comment]
Would be a nice to have.

**Comment by vpicone** [comment]
Gonna close this for now, new components need to be used in Carbon/IDL or a few theme sites before being lifted up into the theme,
