### ISSUE TITLE
vimeo player conflicts with blue play button

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#395]
this is a priority fix since it’s been an issue for over a week. 

The lead videos need to have only the vimeo player as we used to have with IDL. This included scrubbing slider and play button at the bottom. We do not need the blue play button on these lead videos.

The blue button should only appear on all other videos.

Below shows example of where blue button should be removed:
<img width="1196" alt="Screen Shot 2019-09-03 at 7 18 29 PM" src="https://user-images.githubusercontent.com/32881239/64214756-a7a09c00-ce7f-11e9-8047-44fedcfa9295.png">

**Comment by alisonjoseph** [comment]
@jnm2377 @vpicone can we get the blue button removed from Vimeo videos
