### ISSUE TITLE
bug(tab): URL created by tab is broken

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/gatsby-theme-carbon#405]
The tabs for [Code snippet](https://www.carbondesignsystem.com/components/code-snippet/code) are broken. 

The page is replacing the word "code" in with "style" and "usage" outputting links like https://www.carbondesignsystem.com/components/usage-snippet/code.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/44656921/64569297-a7424e00-d322-11e9-8631-10762de69b3f.png">

**Comment by jnm2377** [comment]
closing as duplicate: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/320
