### ISSUE TITLE
Focus is always set on search input unless the search bar is manually collapsed

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/gatsby-theme-carbon#412]
refs #384

continuation of an open question about focus behavior

when the user opens the search bar and then navigates to a new page, focus is reset on the input field on subsequent page navigations unless the search bar is manually collapsed

steps to reproduce:

1. expand search bar
2. navigate to a different page (either by making a search and selecting a result or tabbing to a link on the sidebar or page and selecting it)

focus will jump back to the search bar. this seems fine if the user is selecting a search result, but I just wanted to make sure this was alright for users that were selecting sidebar or body links. maybe we can collapse the search bar if the navigation is not triggered by the list of search results?

**Comment by alisonjoseph** [comment]
cleaning out new issues, this seems like non-issue but can reopen if needed
