### ISSUE TITLE
DoDontExample caption uses incorrect apostrophe/quote

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#419]
It appears the caption does not properly utilize apostrophe, but instead uses a quote. Normal paragraphs use the appropriate mark.

![Screen Shot 2019-09-12 at 10 15 24 AM](https://user-images.githubusercontent.com/3360588/64797088-6cb8fb00-d546-11e9-9fa3-7c5274eaa473.png)

Internal links:
https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/guidelines/app-icons/usage
https://github.ibm.com/Watson-IoT/IoT-Design-ProjectHub/issues/261

**Comment by creckling** [comment]
carbon system site is somehow doing this.
![image](https://user-images.githubusercontent.com/50208035/64868612-b0c30300-d60d-11e9-97f4-56c1ce4818d8.png)

**Comment by tay1orjones** [comment]
I believe the current carbondesignsystem.com is not using the theme. The migration is still WIP.

**Comment by alisonjoseph** [comment]
@tay1orjones Carbon site is fully on the theme as of a couple weeks ago!

**Comment by tay1orjones** [comment]
Awesome! [Searching usages of DoDontExample components](https://github.com/carbon-design-system/carbon-website/search?q=DoDontExample&unscoped_q=DoDontExample) on `carbon-website`, I don't see any with captions containing an apostrophe. 

I believe the screenshot example above is regular paragraph text.

**Comment by creckling** [comment]
It figures it would be different inside the component. Should we go with "Do not" instead to avoid the issue ?

**Comment by tay1orjones** [comment]
Yeah, [I've removed contractions from our site](https://github.ibm.com/Watson-IoT/IoT-Design-ProjectHub/issues/269#issuecomment-14743679). Still a bug here to fix on the theme.

**Comment by kellychurchill** [comment]
@tay1orjones I don't know if this helps you but you can use `’` in the usage of the DoDontExample component and that comes through in the caption.

**Comment by vpicone** [comment]
Yeah, unfortunately the remark plugin doesn't know how to parse MDX components for text it can change. The rec is to do what Kelly said, just use a smart quote in the component rather than leaning on the plugin
