### ISSUE TITLE
Allow for nav menus that don't contain any submenu items

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/gatsby-theme-carbon#423]
### Details
It seems that if the `nav-items.yaml` file does not have any submenu (i.e. nested) items in it, the following error is shown: 

```
- Unknown field 'title' on type '[NavItemsYamlPages]'. Source: document `LEFT_NAV_QUERY` file: `GraphQL request`

File: node_modules/gatsby-theme-carbon/src/components/NextPrevious/NextPrevious.js
```

From @vpicone via Slack:
We need to extend the graphql schema to tell gatsby about that property for the case where folks don’t have any sidebar menus/drop downs.

**Comment by vpicone** [comment]
closed by https://github.com/carbon-design-system/gatsby-theme-carbon/pull/556
