### ISSUE TITLE
Focus state for hamburger is missing a side

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/gatsby-theme-carbon#425]
![image](https://user-images.githubusercontent.com/19270502/64978058-3cd96280-d87a-11e9-8321-bdfdf07dfc27.png)

## Detailed description

> Describe in detail the issue you're having.

The focus state for the hamburger X opened state is missing its right side. 

> What did you expect to happen? What happened instead? What would you like to see changed?

The whole icon button would have the focus.

> What browser are you working in?
Chrome 

## Steps to reproduce the issue

1. Open the site in a narrow width so the left nav collapses into the hamburger
2. open the left nav by using the hamburger icon.

**Comment by jnm2377** [comment]
was this issue resolved? I'm not seeing it on the website or gatsby site. @alisonjoseph @designertyler @vpicone

**Comment by sstrubberg** [comment]
I think this is resolved.

![image](https://user-images.githubusercontent.com/15822070/67496574-36d95d00-f642-11e9-9722-b0547b6673e2.png)

Using Chrome 77.0.3865.120
