### ISSUE TITLE
Text width in mobile goes for not right margin

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#435]
High priority. The width in body copy goes into margin space in iPhone mobile

**Comment by jnm2377** [comment]
@mjabbink I think we just merged a fix the other day for this: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/424

Is that what you were seeing?

**Comment by mjabbink** [comment]
Yes, looks resolved
