### ISSUE TITLE
Navigation - active state bug

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#44]
<img width="793" alt="Screen Shot 2019-05-10 at 3 49 45 PM" src="https://user-images.githubusercontent.com/2753488/57555955-463a4780-733b-11e9-8589-7df8ca4e801c.png">

Looks like we need to be more specific somehow with the active nav matching?

@vpicone

**Comment by SilverFox70** [comment]
![Screen Shot 2019-05-22 at 2 28 01 PM](https://user-images.githubusercontent.com/10566194/58210398-23465680-7c9e-11e9-8829-bcb43f33ceb9.png)
Yes, seeing a similar issue @alisonjoseph

**Comment by SilverFox70** [comment]
Hi, we are still seeing this issue in the one particular case on our site. The behavior is when you select **Requests:Naming**, the **Naming** item above also gets highlighted. Interestingly, this sort of thing does not happen when selecting **Requests:Logos**.

**Comment by tay1orjones** [comment]
@SilverFox70 We're seeing that as well, in addition to another bug with left nav selection state and tabs. I've opened a new issue, #386.
