### ISSUE TITLE
enable better integration with repository field of a consumer's package.json

### ISSUE THREAD

**Issue by boneskull** [carbon-design-system/gatsby-theme-carbon#443]
# Summary

Rename the theme option `repository.baseUrl` to `repository.url`.

### Justification

It'd enable the following.  Given a `package.json` containing:

```json
{
  "repository": {
    "url": "https://github.com/some/where",
    "type": "git",
    "subDirectory": "if/needed"
  }
}
```

A site consuming this theme could, in `gatsby-config.js`,

```js
const {repository} = require('./package.json');

module.exports = {
  plugins: [
    {
      resolve: 'gatsby-theme-carbon',
      options: {repository}
    }
};
```

This obviously has little material impact, since the workaround is trivial, but would be "nice" regardless.

### Desired UX and success metrics

Ensure that use of the `baseUrl` option doesn't break; prefer `url` but also support a deprecated `baseUrl`.  Could eventually be dropped entirely.

### Available extra resources

I'm happy to send a PR to implement.

**Comment by vpicone** [comment]
Good idea! Feel free to open a PR

**Comment by jnm2377** [comment]
@vpicone looks like a PR for this was closed, does this mean we are not interested in this? Should this issue be closed?
