### ISSUE TITLE
[Global] Incorrect spacing after en dashes and numbers in Lists

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/gatsby-theme-carbon#445]
> Somehow the spacing after the en dashes in lists increased.
> https://ibm-brand-center-preview.mybluemix.net/brand/naming#naming-process
> 
> Left is staging (incorrect)
> Right is current live site (correct)
> 
> ![screen shot 2019-09-24 at 5 38 13 pm](https://media.github.ibm.com/user/30208/files/66d1fb00-def2-11e9-92f8-6ed001c1bb98)

**Comment by alisonjoseph** [comment]
fixed w/ latest release
