### ISSUE TITLE
enhancement: add a changelog or release notes

### ISSUE THREAD

**Issue by boneskull** [carbon-design-system/gatsby-theme-carbon#448]
### Summary

Add a changelog (or "release notes" if you want to be fancy)

### Justification

Given the current rapid pace of development, a changelog would be helpful to consumers.

### Desired UX and success metrics

A consumer is able to read the changelog see what has been changed from version to version, and understand what to expect when upgrading.

### Must-have functionality

A `CHANGELOG.md` which is updated upon each npm publish, with a heading for each version, etc., etc.

The changelog would _ideally_ contain features, bug fixes and usability improvements, but (nice-to-have) also omit stuff that doesn't matter ("chore"-type tasks).  

### Specific timeline issues / requests

before the next set of breaking changes :smile:

### Available extra resources

Given this project seems to be using conventional commit (-ish?) messages, it shouldn't be too terribly difficult to generate something automatically using available tooling--I could look into this

**Comment by jnm2377** [comment]
Hi! You can find our release notes here! https://github.com/carbon-design-system/gatsby-theme-carbon/releases 😄

**Comment by jnm2377** [comment]
We could probably do a better job of surfacing this, maybe through a link on our site or something.

**Comment by boneskull** [comment]
My reasoning is that a `CHANGELOG.md` would be more easily discovered and referenced (e.g., offline use) than github releases.  Release notes on GH are paginated and also not searchable afaik.  I tend to use both whenever possible.

**Comment by vpicone** [comment]
We use the official Github releases for documenting changes. While I definitely understand the ask for offline changelogs, I'm not sure that feature is worth needing to update the changelog in two places. Thank you for opening the issue though!
