### ISSUE TITLE
Accordion: text too wide. 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#451]
Text goes too far to the right edge. Should be 32px from the chevron. 

current:
<img width="862" alt="Screen Shot 2019-09-25 at 9 58 33 PM" src="https://user-images.githubusercontent.com/32881239/65654938-028d6500-dfe0-11e9-89a4-c240b990d220.png">

See Brand Center which I thought was Gatsby so not sure if the update was lost from weeks ago?
https://www.ibm.com/brand/help/faq

expected:
<img width="798" alt="Screen Shot 2019-09-25 at 10 02 04 PM" src="https://user-images.githubusercontent.com/32881239/65654996-2e104f80-dfe0-11e9-84f7-ce3f2b39b78f.png">

**Comment by sstrubberg** [comment]
I think PR #454 fixed this.
