### ISSUE TITLE
IDL/Carbon Pictogram/Usage page: Remove margin around images in mini gallery

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#452]
The mini gallery at the bottom of usage page seems to have margin around some images. Both in IDL and Carbon. Duplicated page.

<img width="1073" alt="Screen Shot 2019-09-25 at 6 51 30 PM" src="https://user-images.githubusercontent.com/32881239/65655076-8e9f8c80-dfe0-11e9-82d3-2bd921f52238.png">

<img width="1037" alt="Screen Shot 2019-09-25 at 6 51 22 PM" src="https://user-images.githubusercontent.com/32881239/65655077-8e9f8c80-dfe0-11e9-93d6-4a02159463fd.png">

**Comment by jnm2377** [comment]
Just for clarification: this is a bug with the `ImageGallery`/`ImageGalleryImage` components and they should **not** have margins? i.e. like the `ImageCard` component.

 Or is this a feature request, as in there should be an option for no margin?
cc: @jeanservaas @mjabbink

**Comment by jnm2377** [comment]
Closing per: https://github.com/carbon-design-system/design-language-website/issues/292#issuecomment-545621533
