### ISSUE TITLE
[Aside] Support no-rule option

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/gatsby-theme-carbon#457]
The Aside component (https://gatsby-theme-carbon.now.sh/components/Aside/) comes with a hanging rule. Design would like an option to not have the rule. 

![image](https://user-images.githubusercontent.com/15144993/65779054-a411d500-e10c-11e9-9df9-7abf9dd6fb4b.png)

**Comment by luizamendes** [comment]
Hello, I would like to do this one, if that's okay.

**Comment by vpicone** [comment]
@shixiedesign @jeanservaas can you clarify what the design intent is here? Is there justification for introducing variability?
