### ISSUE TITLE
Code block needs show more/show less functionality

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#463]
@alisonjoseph @jeanservaas 
https://gatsby-theme-carbon.now.sh/components/ResourceCard/

**Comment by mjabbink** [comment]
it exists in Carbon site but not seeing this in the Gatsby component page for code block.

**Comment by alisonjoseph** [comment]
We can get this added back in but @jeanservaas / @vpicone do you remember the history behind why we removed it here?

**Comment by mjabbink** [comment]
Carbon site uses that feature which is nice. Not sure why it would be removed? I can image an on or off so there is both options.

**Comment by jnm2377** [comment]
Related: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/460
Would the design specs for this be the same design specs as carbon components? I can work on this. @jeanservaas @mjabbink

**Comment by vpicone** [comment]
@alisonjoseph The Carbon component only supported 2 or 3 languages for syntax highlighting so had to be re-written. The code examples still use that old component. I don't remember the reason why that feature wasn't added; it kinda doesn’t make sense to me, just the top half of a code snippet isn’t worth much.

I'd prefer our snippets and examples on the site were actually a reasonable length instead of big globs that no one could be expected to digest.

Example: https://getbootstrap.com/docs/4.3/layout/grid/

@jnm2377 @jeanservaas has a revised spec that just uses a single chevron I believe.

**Comment by alisonjoseph** [comment]
@jnm2377 this is a high priority issue for Mike

**Comment by mjabbink** [comment]
status on this?

**Comment by alisonjoseph** [comment]
duplicate #74

**Comment by mjabbink** [comment]
@vpicone if the code snips were only as long as the bootstrap example I’d be fine with no "show more" function but looking at the 2x Grid implementation page they are big globs of code which in this case could use the show more feature. 

It can’t hurt to have this if we will consistently have the long snips.

**Comment by vpicone** [comment]
@mjabbink they have really long snippets there as well. In my opinion, if you need to hide some of the content, then the example is too long for someone to digest anyway.

**Comment by vpicone** [comment]
We can def take another look at this, but expanding the 'show more' pushes the rest of the page content in a weird way. Would it be better to just scroll?

**Comment by mjabbink** [comment]
not better to scroll for those who are wanting to Not expand certain snippets in this page for example.
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation

one can choose which to expand with intent and then it’s ok for content to get pushed down. We need this feature added.

**Comment by mjabbink** [comment]
@alisonjoseph @vpicone @jeanservaas Another oldie that we need to get off the list. Not understanding why this is still around or why there was any discussion over this. There is absolutely no argument against adding this. All it needs is maximum lines of code before the option is added.

**Comment by mjabbink** [comment]
Excellent.
