### ISSUE TITLE
Feature Request: Body Paragraph in Card

### ISSUE THREAD

**Issue by datwd** [carbon-design-system/gatsby-theme-carbon#466]
I wanted to check in about adding a short descriptive paragraph below the title of a card. I'm not sure if this would be outside of standards for an Article Card, and would need to be considered a new component as a Content Card as described here: https://www.carbondesignsystem.com/experimental/cards/usage#content-cards

My team is going to begin working on moving our Z Content Solutions pages into this theme from Northstar, and I wanted to know if it was possible to retain the current structure of including the short paragraph from our current landing page layout, or if we should look to get away from doing that at all.
https://www.ibm.com/support/z-content-solutions/
(Example cards under Featured and All)

Thank you!

**Comment by alisonjoseph** [comment]
My suggestion would be to create a custom component, tagging @jeanservaas however to see if this is something design would want to support.

**Comment by vpicone** [comment]
tagging @peter-garvin for some input on how this might look/work. Would love a design spec using the content from https://www.ibm.com/support/z-content-solutions/

**Comment by peter-garvin** [comment]
I captured some card design examples that do this sort of thing. Not sure what spec we'd want to go with if we want to have this as a feature. @jeanservaas @mjabbink what do you think?
<img width="702" alt="Screen Shot 2020-01-14 at 10 28 54 AM" src="https://user-images.githubusercontent.com/47458576/72362671-32f52e00-36b9-11ea-810b-5b2efe311af8.png">
<img width="941" alt="Screen Shot 2020-01-14 at 10 28 28 AM" src="https://user-images.githubusercontent.com/47458576/72362674-338dc480-36b9-11ea-86cf-e60b0f55fb2b.png">
<img width="927" alt="Screen Shot 2020-01-14 at 10 27 32 AM" src="https://user-images.githubusercontent.com/47458576/72362676-338dc480-36b9-11ea-8336-2dcf71a5d8f5.png">
<img width="821" alt="Screen Shot 2020-01-14 at 10 27 19 AM" src="https://user-images.githubusercontent.com/47458576/72362677-338dc480-36b9-11ea-9e1f-33dde0c3e721.png">
<img width="1016" alt="Screen Shot 2020-01-14 at 10 27 08 AM" src="https://user-images.githubusercontent.com/47458576/72362678-338dc480-36b9-11ea-9da0-74020388056c.png">
<img width="1077" alt="Screen Shot 2020-01-14 at 10 26 18 AM" src="https://user-images.githubusercontent.com/47458576/72362679-34265b00-36b9-11ea-9ac1-55736edf8d40.png">
<img width="832" alt="Screen Shot 2020-01-14 at 10 25 35 AM" src="https://user-images.githubusercontent.com/47458576/72362680-34265b00-36b9-11ea-81a3-363d6d5a8665.png">
<img width="1076" alt="Screen Shot 2020-01-14 at 10 24 44 AM" src="https://user-images.githubusercontent.com/47458576/72362681-34265b00-36b9-11ea-995c-5a8671b45872.png">
<img width="947" alt="Screen Shot 2020-01-14 at 10 23 52 AM" src="https://user-images.githubusercontent.com/47458576/72362682-34265b00-36b9-11ea-972e-5e7479d50eee.png">
<img width="1119" alt="Screen Shot 2020-01-14 at 10 21 23 AM" src="https://user-images.githubusercontent.com/47458576/72362684-34bef180-36b9-11ea-8639-3275d5f8e356.png">
<img width="1134" alt="Screen Shot 2020-01-14 at 10 17 32 AM" src="https://user-images.githubusercontent.com/47458576/72362686-34bef180-36b9-11ea-98df-5516182ca8ac.png">
<img width="984" alt="Screen Shot 2020-01-14 at 10 16 32 AM" src="https://user-images.githubusercontent.com/47458576/72362688-34bef180-36b9-11ea-942e-a0e066a2f9f2.png">
<img width="804" alt="Screen Shot 2020-01-14 at 10 15 47 AM" src="https://user-images.githubusercontent.com/47458576/72362689-34bef180-36b9-11ea-9ca2-b12a090f22f1.png">
<img width="1060" alt="Screen Shot 2020-01-14 at 10 15 19 AM" src="https://user-images.githubusercontent.com/47458576/72362690-34bef180-36b9-11ea-99b0-9254165a4777.png">

**Comment by mjabbink** [comment]
Nice samples @peter-garvin. Is Developer using your designs now?

**Comment by vpicone** [comment]
Going to close this for now, adding body copy to cards is supported and relatively simple. It'd be impossible for us to accomodate all the possible card permutations and would make for a worse component when the user can compose it exactly as they need.
