### ISSUE TITLE
[mobile lists] text should not go into right margin

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#470]
https://www.carbondesignsystem.com/guidelines/pictograms/contribute/

![0FB770E4-942B-420E-8C1F-B3973401C7EB](https://user-images.githubusercontent.com/32881239/66753923-6629e600-ee5a-11e9-8f8b-53304066c199.jpeg)
![B6CC8F0A-BA4F-44B0-A421-17B8D7AE5CF2](https://user-images.githubusercontent.com/32881239/66753925-6629e600-ee5a-11e9-953d-1542eb0da354.png)

**Comment by alisonjoseph** [comment]
Looks like this is an issue w/ ordered lists (should double check unordered also)

**Comment by mjabbink** [comment]
goo to go
