### ISSUE TITLE
Update tab design/styles

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#478]
Per @mjabbink we need to update the tabs in the theme to match the tabs used on the IDL website. 

Example
https://www.ibm.com/design/language/elements/color/#specifications
<img width="466" alt="Screen Shot 2019-10-24 at 4 43 52 PM" src="https://user-images.githubusercontent.com/2753488/67527826-7ec9a580-f67d-11e9-98d3-72de283e1939.png">

VS current tabs

<img width="693" alt="Screen Shot 2019-10-24 at 4 46 59 PM" src="https://user-images.githubusercontent.com/2753488/67527996-e97ae100-f67d-11e9-8d81-f29677eb5b57.png">

@jeanservaas to confirm/provide updated spec for tabs 

@jnm2377 FYI once we have a spec

**Comment by mjabbink** [comment]
why blocked?

**Comment by jnm2377** [comment]
> once we have a spec

Label is bc blocked on the dev side until spec is provided.

**Comment by mjabbink** [comment]
I think we decided to go with ones in IDL and remove the one with the blue line. My only fear there is some have used that blue line tab in their sites. But let’s go for it! 

So in this case it’s not blocked. Just use the IDL tab

**Comment by mjabbink** [comment]
This issue is 4 weeks old. @jeanservaas can confirm but the specs exist in Design Language site because the tab is already in use.
