### ISSUE TITLE
Anchor link arrow - not pulling in correct font (Plex)

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#48]
![Screen Shot 2019-05-13 at 12 10 57 PM](https://user-images.githubusercontent.com/2753488/57640812-02cd1c80-7579-11e9-9cdc-59334cae3552.png)

**Comment by alisonjoseph** [comment]
this one again @vpicone 😭

**Comment by vpicone** [comment]
Closing this in favor of https://github.com/carbon-design-system/gatsby-theme-carbon/issues/68
