### ISSUE TITLE
Nested list item width

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#495]
Continuation of #494

- [ ] figure out what things, if any, should be list-width and what should be full width (minus the list's indentation).
- [ ] better document how to nest MDX elements within lists

<img width="1772" alt="Screen Shot 2019-08-12 at 4 39 10 PM" src="https://user-images.githubusercontent.com/47458576/62902317-de720f00-bd24-11e9-864b-e992223b89ed.png">
<img width="1772" alt="Screen Shot 2019-08-12 at 4 38 50 PM" src="https://user-images.githubusercontent.com/47458576/62902321-e03bd280-bd24-11e9-9ab9-5a179487fef6.png">

<img width="1772" alt="Screen Shot 2019-08-12 at 4 37 01 PM" src="https://user-images.githubusercontent.com/47458576/62902326-e3cf5980-bd24-11e9-8589-c31e745d60a3.png">
<img width="1772" alt="Screen Shot 2019-08-12 at 4 36 19 PM" src="https://user-images.githubusercontent.com/47458576/62902329-e631b380-bd24-11e9-84d2-78952863ae2f.png">

**Comment by jeanservaas** [comment]
@mjabbink wondering if this can be a brand project to explore? Unless it's a super quick decision... like indenting all images / components (like code snippet) that are within the list... that was the blanket call the carbon team made earlier, but we didn't really have time for guidance or vetting.

**Comment by mjabbink** [comment]
I think so.

**Comment by peter-garvin** [comment]
just adding a note here - I think we'll need to have the option of having items within lists outside of list formatting. Sometimes its good to have the indent, as with code snippets for example. But sometimes we may need to have an image large across 12 columns. Whats happening now is that anything within the list is miniaturized. Check out these cute resource cards 

<img width="768" alt="Screen Shot 2019-11-05 at 11 50 42 AM" src="https://user-images.githubusercontent.com/47458576/68317354-955dfc80-0080-11ea-94f1-6a8f9f3f75cc.png">

**Comment by alisonjoseph** [comment]
@mjabbink which designer on Brand should we assign this issue to? Do we need to create an issue on the internal repo to get it prioritized?

**Comment by mjabbink** [comment]
I think @vpicone resolved this issue but confirming?

**Comment by vpicone** [comment]
@mjabbink negative, we need to decide if _everything_ is indented while inside of a list item. 

For example, @peter-garvin’s resource card case. We want to avoid list one-off exceptions. Whether or not resource cards should be used in the middle of an ordered list is uncertain I think.

**Comment by mjabbink** [comment]
Let’s connect with @jeanservaas on this and try to get this wrapped

**Comment by mjabbink** [comment]
@vpicone @peter-garvin is this still active? Should be move this up the chain?

**Comment by vpicone** [comment]
@mjabbink  Yeah, I think this issue might have been a little too loosely defined. It’s been a while since we wanted something weird in a list. Gonna close it for now until we have a better/non theoretical example of where the current behavior can be improved.

**Comment by peter-garvin** [comment]
@vpicone heres another example
<img width="808" alt="Screen Shot 2020-05-15 at 9 25 51 AM" src="https://user-images.githubusercontent.com/47458576/82061283-20522c00-968e-11ea-9f66-97e83f2c6bd3.png">

We need to have the ability to either continue numbering in a list once it is broken, or have components within lists not bound by list sizing (Things like images, tables, cards, etc. – right now anything in a list gets miniaturized)

**Comment by vpicone** [comment]
Yeah I think that’s intentional, otherwise you lose track of what’s in a list and what’s out. Everything becomes flat.

**Comment by vpicone** [comment]
I would bring the ordered list up to be headings rather than stuffing everything into a tiny list here. Use H3s.

**Comment by mjabbink** [comment]
I don’t think it needs to be nested though? That imagery can sit in the grid the same as all the content above it.

**Comment by peter-garvin** [comment]
if I make an h3 that starts with "4. Copy the blah blah blah" would it follow the list markdown and always be number 1?

**Comment by peter-garvin** [comment]
im not certain doing it with h3s works in every context. Is it weird if you have a page full of list instructions, then one section's lists are all in h3s just to avoid the list indentation and miniaturization?

**Comment by mjabbink** [comment]
the list is fine as is but is there no way to disconnect the images from the list and have them follow the columns structure?

**Comment by mjabbink** [comment]
@sstrubberg @andreancardona This needs some love but especially this problem. https://github.com/carbon-design-system/gatsby-theme-carbon/issues/495#issuecomment-629266698

**Comment by vpicone** [comment]
@mjabbink bump it up on the list and we'll assign someone to it!

**Comment by mjabbink** [comment]
the thing with this part is just the images should not be getting be getting smaller and should be on grid *each image spanning 4 columns). https://github.com/carbon-design-system/gatsby-theme-carbon/issues/495#issuecomment-629266698

**Comment by jnm2377** [comment]
for clarification, are we saying only nested images will not follow list width? any other item (i.e. resource card, code snippet, etc) will follow nested list width? Or are we saying everything will not follow nested list width?

**Comment by peter-garvin** [comment]
@jnm2377 tables are another component that should not be affected I think. Is there any way we could make it where we can use custom numbering for lists? So that we could just break it, use a component, and continue numbering? I know theres some tricks to break numbering with markdown, but it makes it where we lose the formatting of the list (proper indentation and such)

**Comment by jnm2377** [comment]
> tables are another component that should not be affected I think. Is there any way we could make it where we can use custom numbering for lists? So that we could just break it, use a component, and continue numbering? I know theres some tricks to break numbering with markdown, but it makes it where we lose the formatting of the list (proper indentation and such)

@peter-garvin tagged you for review in a PR that adds this functionality!

**Comment by peter-garvin** [comment]
@jnm2377 Amazing! I think this solves everything, and still gives us the option to have indented photos when needed. Thanks!

**Comment by mjabbink** [comment]
@peter-garvin These changes should also solve the App icons production nesting too.
https://www.ibm.com/design/language/iconography/app-icons/production

**Comment by peter-garvin** [comment]
yep just waiting on this issue to be resolved and merged and I can update that
https://github.com/carbon-design-system/gatsby-theme-carbon/pull/893
