### ISSUE TITLE
[Component status & Table pages] — Remove horizontal scrolling in "mobile"

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#496]
see slack channel for video recording.

**Comment by mjabbink** [comment]
<img width="420" alt="Screen Shot 2019-11-05 at 2 25 15 PM" src="https://user-images.githubusercontent.com/32881239/68243444-1b723880-ffd8-11e9-81df-4ce90bbb0457.png">

**Comment by mjabbink** [comment]
<img width="419" alt="Screen Shot 2019-11-05 at 2 24 51 PM" src="https://user-images.githubusercontent.com/32881239/68243450-1f9e5600-ffd8-11e9-87ae-228ad35914a2.png">

**Comment by jnm2377** [comment]
I think this may require changes in the Carbon site. As far as I know, data tables aren't horizontally scrollable unless they're `display: block` (not the default style for tables) or are in a container that allows for horizontal scrolling. `overflow: auto`. This was an issue I ran into when trying to figure out scrolling functionalities for our own data table component in Carbon. The issue with display block is that it messes with the natural fluidity of html tables. Usually, people only use that when they can set hard-coded width values for the columns. Not really ideal. I think the best solution would be to have the container scroll. 

There's a `PageTable` component in the Gatsby theme that actually does this:
 ```css
.page-table__container {
  overflow-x: auto;
}
```

**Comment by rcwakelin** [comment]
Create PR in carbon. @jnm2377 to add
