### ISSUE TITLE
[Spacing] Vertical spacing between image clusters should be 32px

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/gatsby-theme-carbon#497]
Spacing in between images should be consistent both horizontally and vertically
https://www.carbondesignsystem.com/guidelines/accessibility/overview

![Screen Shot 2019-11-05 at 4 43 47 PM](https://user-images.githubusercontent.com/33162280/68248919-c7714f00-ffeb-11e9-948a-d928529e9786.png)

It should behave more like this:
https://gatsby-theme-carbon.now.sh/components/ImageGallery

![Screen Shot 2019-11-05 at 4 48 20 PM](https://user-images.githubusercontent.com/33162280/68249118-220aab00-ffec-11e9-8c2e-9118a5186ae0.png)

FYI 
@vpicone 
@mjabbink

**Comment by jnm2377** [comment]
This will need a custom component similar to the `ImageGallery` [wrapper](https://gatsby-theme-carbon.now.sh/components/ImageGallery#markdown-code). The spacing here is just coming from the rows & columns that contain the DoDont component. It's not a bug in the spacing, as we can't actually target row styles based on whatever is inside them, thus the need for a custom container that will target the row styles automatically for DoDont clusters. Hope that makes sense!
