### ISSUE TITLE
Update[Do/Don't component]: Change don't color from magenta to red

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#499]
## Update[Do/Don't component]: Change don't color from magenta to red

We want to use the magenta spectrum in our Usage images for annotations / call outs / coachmarking but when usage images are near Do / Don't component, the use of magenta makes it look like we're telling the user NOT to do something rather than annotating etc.

- [ ] Change the Don't component color from Magenta 60 to Red 60 

**Annotation example:**

![image](https://user-images.githubusercontent.com/43144260/68253156-dc021700-ffec-11e9-888d-65e4b6079102.png)

**Do / Don't component now:**

![image](https://user-images.githubusercontent.com/43144260/68252958-5ed6a200-ffec-11e9-8864-588fadfc9146.png)

**Do / Don't component update:**

![image](https://user-images.githubusercontent.com/43144260/68252999-7150db80-ffec-11e9-877a-77d77f3f310e.png)

Just landed on this solution today with Mike in light of the work we're doing with patterns @alisonjoseph ... not sure who this update would go to... @jnm2377  ?

**Comment by alisonjoseph** [comment]
Whats priority on this @jeanservaas so @jnm2377 can triage this into her support stream?
