### ISSUE TITLE
Table column width control.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#502]
This is a biggie for me and we should dial this effort up. It’s a major aspect to basic typography and information design. Can we aim to solve this by end of 2019? Or at the very least sometime in Q1.

**Comment by rcwakelin** [comment]
@alisonjoseph to meet wit @alisonjoseph for progress update

**Comment by jnm2377** [comment]
This is a duplicate of: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/421
