### ISSUE TITLE
body copy width too wide.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#503]
The length of body in many places seems to still go 100% full width of the 8 columns. It should never do this in any body copy situations.

Below are examples where body text goes all the way to the right edge of grid.

https://gatsby-theme-carbon.now.sh/getting-started
![Screen Shot 2019-11-06 at 11 31 37 AM](https://user-images.githubusercontent.com/32881239/68322577-3bae0000-0089-11ea-9926-276f69ed4853.png)

https://gatsby-theme-carbon.now.sh/guides/configuration#global-search
![Screen Shot 2019-11-06 at 11 34 09 AM](https://user-images.githubusercontent.com/32881239/68322755-9e9f9700-0089-11ea-8f3c-53ccb162b71e.png)

![Screen Shot 2019-11-06 at 11 34 46 AM](https://user-images.githubusercontent.com/32881239/68322782-a8c19580-0089-11ea-90f1-8a6ec8d0d484.png)

![Screen Shot 2019-11-06 at 11 35 11 AM](https://user-images.githubusercontent.com/32881239/68322856-d1e22600-0089-11ea-8262-4cb76c7dc1dc.png)

**Comment by mjabbink** [comment]
This issue keeps coming back.

**Comment by sadekbazaraa** [comment]
And here is another example on the IDL Photography page. You can see the body copy extending the full 8 columns over the image.

![Screen Shot 2019-11-04 at 3 29 16 PM](https://user-images.githubusercontent.com/33162280/68338628-eb4a9880-00b0-11ea-959d-7402091cc81e.png)

The way we always design and the intended outcome is for the full width copy to be 8 columns minus 2rem (32px). In mobile, it goes to full width across all 4 columns. Here is an example of how this is laid out in Sketch. 

![Screen Shot 2019-11-04 at 3 30 36 PM](https://user-images.githubusercontent.com/33162280/68338935-8b082680-00b1-11ea-8bea-6a852f8bd90a.png)

FYI @mjabbink

**Comment by mjabbink** [comment]
Status?

**Comment by mjabbink** [comment]
good to go
