### ISSUE TITLE
Footer width too wide on the text on the right side of footer.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#504]
We should not allow this text to span this long. Se Carbon site and IDL site for width. @jeanservaas to help spec a max width.

**Comment by rcwakelin** [comment]
@mjabbink to add list of sites with issue in this story

**Comment by mjabbink** [comment]
https://gatsby-theme-carbon.now.sh/

<img width="949" alt="Screen Shot 2019-11-14 at 1 27 03 PM" src="https://user-images.githubusercontent.com/32881239/68889487-a7741680-06e2-11ea-89ba-e26f655142f2.png">



<img width="1149" alt="Screen Shot 2019-11-14 at 1 27 12 PM" src="https://user-images.githubusercontent.com/32881239/68889504-acd16100-06e2-11ea-91b6-bd0b6f478376.png">



<img width="1551" alt="Screen Shot 2019-11-14 at 1 27 23 PM" src="https://user-images.githubusercontent.com/32881239/68889526-b2c74200-06e2-11ea-99c9-39a2893b0779.png">

**Comment by jnm2377** [comment]
Just for clarification, what is the expected design spec for this?

**Comment by mjabbink** [comment]
@jeanservaas how can we best spec this? In tablet the text seems to span too many columns. The type cluster of information can be the same across all the break points. Not need to have this content flow.

**Comment by mjabbink** [comment]
@jeannie see above question to you.

**Comment by vpicone** [comment]
Resolved
