### ISSUE TITLE
[Spacing]: Image caption spacing is too large

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/gatsby-theme-carbon#505]
Ref: https://github.ibm.com/brand/design-language/issues/26#issuecomment-15787525

<img width="888" alt="Screen Shot 2019-11-06 at 11 25 10 AM" src="https://user-images.githubusercontent.com/32556167/68324030-32726280-008c-11ea-8839-9e0d3bdd4df5.png">

**Comment by jnm2377** [comment]
Related: https://github.ibm.com/brand/design-language/issues/67

**Comment by jnm2377** [comment]
Rel: https://github.ibm.com/brand/design-language/issues/68#event-65817645

**Comment by rcwakelin** [comment]
@jnm2377 are https://github.ibm.com/brand/design-language/issues/67 and https://github.ibm.com/brand/design-language/issues/68#event-65817645 part of this story?
