### ISSUE TITLE
Add fade to Gatsby Leadspace title (Security has executed this in Experience Guide site)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#507]
Let’s add this to Gatsby. What say you @jeanservaas? 

@jendowns Is this a speedy enhancement we can do ?

https://security-design-guide.stage1.mybluemix.net/brand/essentials/aurora/

**Comment by jendowns** [comment]
Hey @mjabbink! I believe @SimonFinney is the one who originally added that to our site, so he would have more insight.

**Comment by sstrubberg** [comment]
I've been wanting to add this to the theme..

**Comment by SimonFinney** [comment]
For Security's Experience Guide, this is just a fade-in CSS animation on the content's container that runs when the view is loaded - I'm not entirely sure how that works in the Gatsby world, but the principle should still be the same.

**Comment by mjabbink** [comment]
thanks @jendowns and @SimonFinney

**Comment by rcwakelin** [comment]
@jnm2377 to meet with @alisonjoseph for and update on progress

**Comment by jnm2377** [comment]
@sstrubberg did you want to work on this?

**Comment by sstrubberg** [comment]
@jnm2377 yes plz! But i would love to tag team it with someone. I has having trouble figuring out how to configure the plugin for the theme.

**Comment by jnm2377** [comment]
@sstrubberg This is probably something we can work on together during mob programming time over the next few weeks. This is a low priority, so it can also be pushed back since we have a lot of other issues to work on before the end of the year.

**Comment by vpicone** [comment]
Going to leave this off for now since it's implementable by individual sites and after demoing it for @mjabbink we're actually preferring the instant page load from native theme.
