### ISSUE TITLE
fix[spacing]: paragraphs following h4s need 0 margin top

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#508]
## fix[spacing]: paragraphs following h4s need 0 margin top

After pushing the new spacing fix, we have to tweak the H4s in the theme:

- [ ] all paragraphs following h4s should have 0 margin top 
- [ ] create a FigureTitle component so folks don’t have to  hijack h4's to get a figure title (leaving images, figures, videos etc. to still get the sapce)

This is what's happening right now... creating super confusing hierarchies across the Carbon site:

![image](https://user-images.githubusercontent.com/43144260/68422591-1d6a0200-0166-11ea-9740-e5756434d218.png)

**Comment by jnm2377** [comment]
Looks like the spacing in the paragraph is actually coming from the row. Row's are now receiving a margin-top: 1.5rem coming from these styles: https://github.com/vpicone/gatsby-theme-carbon/blob/d9e6fdc0d80228b6c1326968cba2f0663772d7a6/packages/gatsby-theme-carbon/src/components/Main/Main.module.scss#L11-L18

**Comment by rcwakelin** [comment]
PR request to come soon.

**Comment by mjabbink** [comment]
See second bullet above. This seems to have been missed.

references:

<img width="408" alt="Screen Shot 2019-12-04 at 5 34 33 PM" src="https://user-images.githubusercontent.com/32881239/70190769-7b81fa80-16bc-11ea-9a34-728859b530c0.png">


—



<img width="444" alt="Screen Shot 2019-12-04 at 5 34 29 PM" src="https://user-images.githubusercontent.com/32881239/70190774-8046ae80-16bc-11ea-8633-24fd25c76b36.png">


—

<img width="359" alt="Screen Shot 2019-12-04 at 5 20 55 PM" src="https://user-images.githubusercontent.com/32881239/70190797-889ee980-16bc-11ea-97b2-37aff19136dd.png">

**Comment by vpicone** [comment]
@mjabbink opened https://github.com/carbon-design-system/gatsby-theme-carbon/issues/591 to track this. Is there something visually wrong with those figure titles or are you just saying they shouldn't be h4s?

**Comment by mjabbink** [comment]
the spacing under the header is too tight. Not sure what the exact spec is but by best guess is 16 or 24px. @jeanservaas can provide exact pixels.

**Comment by mjabbink** [comment]
also effects here with this header size too. Needs more space under neath above text and image in this case https://www.ibm.com/brand/advertising

<img width="964" alt="Screen Shot 2019-12-09 at 10 35 54 AM" src="https://user-images.githubusercontent.com/32881239/70462514-e7bf7e00-1a6f-11ea-836f-2b6074a4458d.png">

**Comment by jeanservaas** [comment]
the space after the figure title should be 24px -- or rather, allow the image to have the 24px margin top in this scenario.

**Comment by mjabbink** [comment]
What about the larger header in above sample?
