### ISSUE TITLE
Global [Spacing]

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#509]
Issue captured in IDL site repo

- [ ]  https://github.ibm.com/brand/design-language/issues/66

**Comment by jnm2377** [comment]
We have quite a few spacing issues opened. What is this one supposed to be referencing? I think this is linking to the wrong thing (that issue isn't related to spacing).

**Comment by mjabbink** [comment]
Referencing this issue:
https://github.ibm.com/brand/design-language/issues/67
