### ISSUE TITLE
Margin top applied to descendents of `.main` causes vertically misaligned content

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#513]
## Detailed description

Check out the `ImageCard` example page: https://gatsby-theme-carbon.now.sh/components/ImageCard

Content is vertically misaligned, and it does not look intentional.

The `margin-top` makes it so `ImageCard` components are not locked up.

![Screen Shot 2019-11-11 at 11 39 03 AM](https://user-images.githubusercontent.com/9057921/68608548-d0916e80-0478-11ea-9dcb-032f7c759832.png)

Culprit appears to be:

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/7ad684f52441975d4452d33d96cfd3093f7733b6/packages/gatsby-theme-carbon/src/components/Main/Main.module.scss#L11-L14

Possibly related to work done for #500

**Comment by jnm2377** [comment]
Thanks for opening this issue! I'm currently looking into all the spacing issues that resulted from the latest spacing update. 👍
