### ISSUE TITLE
FeatureCard has nested anchors

### ISSUE THREAD

**Issue by techtolentino** [carbon-design-system/gatsby-theme-carbon#517]
## The FeatureCard component has nested anchors

When implementing the `<FeatureCard>` component, I noticed a warning in the console that says `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.` 

What browser are you working in?
Chrome, Version 78.0.3904.97 (Official Build) (64-bit)

## Steps to reproduce the issue

1. import FeatureCard
2. implement the thing
3. give it an href
4. peep the console 

## Screenshot

<img width="1680" alt="anchor_descendent_of_anchor" src="https://user-images.githubusercontent.com/6276074/68784042-8e476900-0601-11ea-8e91-9ef937043558.png">

![featurecard_browser_console](https://user-images.githubusercontent.com/6276074/68784149-c189f800-0601-11ea-87f3-97d9439b4b30.png)

:heart: the work y'all do

✊

**Comment by jendowns** [comment]
Hey everyone, I have an idea to fix this & can open a PR shortly 👍

**Comment by jnm2377** [comment]
@jendowns thanks for jumping in! Look forward to seeing your PR!
