### ISSUE TITLE
Spacing within lists is too tight

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/gatsby-theme-carbon#520]
Spacing for content within lists is too tight 
https://www.ibm.com/design/language/elements/app-icons/production/

<img width="1423" alt="Screen Shot 2019-11-14 at 9 07 20 AM" src="https://user-images.githubusercontent.com/47458576/68869223-75e95400-06be-11ea-858c-2bd34231f89c.png">

**Comment by jnm2377** [comment]
What is the expected spacing?

**Comment by mjabbink** [comment]
@peter-garvin please provide more details for Josefina.

**Comment by peter-garvin** [comment]
Sorry just saw this. @jnm2377 Are you able to use the same spacing that images have around them when theyre in regular body copy?

<img width="1242" alt="Screen Shot 2019-11-19 at 9 19 47 AM" src="https://user-images.githubusercontent.com/47458576/69159601-c80aea80-0aad-11ea-8571-5092042aa72e.png">

**Comment by jnm2377** [comment]
@peter-garvin so anything that is a sibling in `main` body copy, has a `margin-top` of `1.5rem`, that's what you see in the example above. Did you want that spacing for all content within a list item or specifically just images?

**Comment by peter-garvin** [comment]
@jnm2377 I think the spacing for elements within lists should be the same as if they were outside of lists. For example, the table is pretty cramped within the list, and should have the same spacing around it as if it were outside the list. @jeanservaas does that seem right?

<img width="888" alt="Screen Shot 2019-11-20 at 10 00 16 AM" src="https://user-images.githubusercontent.com/47458576/69255161-ee4b8b80-0b7c-11ea-9815-5c4afa04e7ba.png">
<img width="915" alt="Screen Shot 2019-11-20 at 10 02 02 AM" src="https://user-images.githubusercontent.com/47458576/69255166-f0ade580-0b7c-11ea-9c33-a679ec94c314.png">

**Comment by jnm2377** [comment]
@peter-garvin opened a PR for you to review
