### ISSUE TITLE
[lists] List styling

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#559]
List styles seem very different and don't seem to fit the page layout any more.

## Detailed description
See pics below:
<img width="1440" alt="Screen Shot 2019-11-22 at 4 37 32 PM" src="https://user-images.githubusercontent.com/10566194/69469666-ed665580-0d46-11ea-9b92-a49e4e46e3fb.png">

and in columns:
<img width="1440" alt="Screen Shot 2019-11-22 at 4 36 11 PM" src="https://user-images.githubusercontent.com/10566194/69469675-f820ea80-0d46-11ea-8199-9956fa00565f.png">

When trying to use lists their formatting suddenly appears to be very different from what we have come to expect. Perhaps we have some wrapper that is bonking the styles?

> What did you expect to happen? What happened instead? What would you like to see changed?
We would like to see the lists formatted as they were before when we were using 1.14.3

> What browser are you working in?
Chrome primarily.

## Steps to reproduce the issue

1. Use a typical markdown list
2. Be using the latest GTC 1.17.2
3. Spool up the dev environment or do a build
4. View the page with a list in browser

**Comment by SilverFox70** [comment]
I also happened to notice this is happening here as well:https://www.ibm.com/design/language/elements/pictograms/contribute/
![Screen Shot 2019-11-27 at 12 20 53 PM](https://user-images.githubusercontent.com/10566194/69758859-86b1b500-1115-11ea-8ed4-41a942fb4b42.png)

**Comment by mjabbink** [comment]
Mobile:
![Screenshot 2019-12-01 at 3 42 16 PM copy](https://user-images.githubusercontent.com/32881239/69920908-16779c00-1453-11ea-958c-f24c4631b483.jpg)

**Comment by jnm2377** [comment]
Thanks for opening this issue! 
@peter-garvin do you know what the expected spacing is for li?

**Comment by mjabbink** [comment]
this used to be fine a few weeks back so has recently gone buggy.

**Comment by mjabbink** [comment]
Seems to be fine here but this is likely not the latest Gatsby version.
https://deploy-preview-342--design-language-website.netlify.com/design/language/help/support/

![Screen Shot 2019-12-02 at 3 10 17 PM](https://user-images.githubusercontent.com/32881239/69995622-0c6aa180-1516-11ea-9cce-382262a6e332.png)

**Comment by mjabbink** [comment]
Looks like it’s maybe 8px between "en dash" and type

**Comment by SilverFox70** [comment]
On Brand Center (https://www.ibm.com/brand/naming):
- en dash is left aligned with text
- margin-left is 8px (where dash is)
- padding-left is 16px (between dash and text
![Screen Shot 2019-12-02 at 2 29 03 PM](https://user-images.githubusercontent.com/10566194/70000593-3325d980-1510-11ea-90f2-3873dfbdd668.png)

**Comment by mjabbink** [comment]
is 16px too large of a space? Seems like older versions were tighter.

<img width="733" alt="Screen Shot 2019-12-04 at 5 22 51 PM" src="https://user-images.githubusercontent.com/32881239/70190119-b8e58880-16ba-11ea-8343-32f18a281d56.png">

**Comment by mjabbink** [comment]
@vpicone @jnm2377 
@jeanservaas and I discussed and we’d like to also indent the bullets 24px versus left aligned with text.

**Comment by mjabbink** [comment]
also issue here:
<img width="1086" alt="Screen Shot 2019-12-06 at 7 01 47 AM" src="https://user-images.githubusercontent.com/32881239/70334517-328c8c00-180b-11ea-84cc-53c56c8e2ec5.png">

**Comment by mjabbink** [comment]
<img width="798" alt="Screen Shot 2019-12-06 at 2 57 18 PM" src="https://user-images.githubusercontent.com/32881239/70355860-be68dd00-1838-11ea-892f-65b4d1b5c245.png">

**Comment by mjabbink** [comment]
@jeanservaas give this a once over but I think this is what we agreed on. Let me know if different idea.

Since 3 digits will be rare I think we base the space after 2 digits as the base spacing also for single digits. Not sure how to spec this correctly though.

<img width="872" alt="Screen Shot 2019-12-06 at 3 01 02 PM" src="https://user-images.githubusercontent.com/32881239/70356112-451dba00-1839-11ea-89c2-07326f5ec8ab.png">

**Comment by vpicone** [comment]
@SilverFox70 @mjabbink this was caused by a patch upstream in Carbon. Should have a fix published today.

**Comment by mjabbink** [comment]
👍

**Comment by mjabbink** [comment]
@vpicone Did this get published? I still see all these issues across all the sites using theme
