### ISSUE TITLE
[Homepage]: Gutter bug

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#565]
I'm not sure how just yet, but [this commit](https://github.com/carbon-design-system/gatsby-theme-carbon/commit/a66191820ffe37411e2e17fbafb58fc3ddc8e936) is throwing off gutters on the homepage.

Below is an example of the new MediumPosts component on the Example page. Notice the extra rem of padding even though the `noGutterMdLeft` prop is being passed to the component.

![image](https://user-images.githubusercontent.com/15822070/69556207-fe42e100-0f69-11ea-8b94-c4765017569d.png)

When I remove `theme="dark"` from the Homepage template, everything starts working again.

**Comment by jnm2377** [comment]
🤔 hmmm.. that's so strange.

**Comment by sstrubberg** [comment]
I dropped in a custom style [identical to the one on IDL](https://github.com/carbon-design-system/design-language-website/blob/master/src/styles/_grid-temp.scss) and it fixed it right up.

**Comment by alisonjoseph** [comment]
this is fixed
