### ISSUE TITLE
Support other aspect ratios for the DoDontExample component

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/gatsby-theme-carbon#568]
### Summary

The **DoDontExample** component is great... but at present the only supported `aspectRatio` property value `1:1`:

![Screenshot 2019-11-26 at 09 15 03](https://user-images.githubusercontent.com/9316771/69615842-7f16e100-102d-11ea-948f-ead91679e850.png)

It would be great if other aspect ratios were supported. 

### Justification

I am wanting to add more positive and negative examples to the Carbon [Content](https://www.carbondesignsystem.com/guidelines/content/general) guidance, as users love seeing clear, concrete examples (and not having to rely solely on reading lots of guidance text). 

If I use the default aspect ratio (`1:1`) it means that these examples take up huge amounts of vertical real estate: 

![Screenshot 2019-11-26 at 09 29 26](https://user-images.githubusercontent.com/9316771/69617050-88a14880-102f-11ea-975a-b85781c31c86.png)

I've found that specifying an aspect ration of `1:2` does result in the vertical height of the component being reduced, however, the implementation isn't perfect as the green tick / red cross icons overlay the text in some cases, which I guess is why this option isn't listed on the gatsby-theme-carbon site ([here](https://gatsby-theme-carbon.now.sh/components/DoDontExample)):

![Screenshot 2019-11-26 at 09 17 49](https://user-images.githubusercontent.com/9316771/69616092-ea60b300-102d-11ea-8826-352cb29a55cb.png)

**Comment by jnm2377** [comment]
Thanks for opening this issue. I'm would like to get our designer's thoughts on this before saying yes. @jeanservaas would we be interested in supporting different aspect ratios for do/dont?

**Comment by tomwaterton** [comment]
**Update:** 
I had a call with Jean Servaas today and we discussed this request. 
Jean explained that the Carbon team would actually like to add a new type of "Do / Don't" example component that is more suited for simple strings of text. 

I showed an example from the [CD&AI voice and tone guide](https://cdai-design.w3ibm.mybluemix.net/design-system/voice-and-tone?tab=guide), and Jean said they haven't designed it yet, but it could end up being something similar - i.e. simple, built to just contain a string of text, and to not take up huge amounts of screen real estate: 
![Screenshot 2019-12-12 at 20 36 10](https://user-images.githubusercontent.com/9316771/70747210-642bb880-1d1f-11ea-875b-0f5510cb145e.png)

**Comment by vpicone** [comment]
@tomwaterton going to close this out for now.

We typically like to see components used at least in Carbon/IDL or several of the theme sites before adding it to the theme. If you'd like to spec and build it, that would be a great next step to adding it to the theme.
