### ISSUE TITLE
Next/Prev alignment

### ISSUE THREAD

**Issue by lawhump** [carbon-design-system/gatsby-theme-carbon#569]
The Next/Prev text isn't on the grid, as shown in the picture.

<img width="1294" alt="Screen Shot 2019-11-26 at 7 52 33 AM" src="https://user-images.githubusercontent.com/5386917/69640106-6bff1380-1023-11ea-87d9-6ec5bec8bfec.png">

**Comment by jnm2377** [comment]
@jeanservaas are these the correct design specs for next/prev? What should the spacing be?

**Comment by alisonjoseph** [comment]
The text should align. Might just be missing a row wrapper class to calculate the %% correctly.
