### ISSUE TITLE
enhancement [app switcher]: truncate app switcher

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#57]
## enhancement [app switcher]: truncate app switcher

**Why:**
The app switcher now is mirroring the left nav behavior almost exactly which is confusing to the user; by keeping the left nav anchored and floating the global app switcher we create a clearer hierarchy between the two.  

<br>

**Where:**
This floating app switcher remains a global element across all practices... we just want to make that function clearer. It does not change color when the local content changes, it operates on a separate logic / independent of the local left nav. 

- [x] All type and core / interative color tokens, dropshadow and most geometries remain the same

- [x] Add subheads

- [ ] shorten app switcher in Max, XL, Lrg and tablet breakpoints (truncate app switcher 24px after the last link item block

- [ ] 1px, Gray 80 stroke animates up 90 degrees to include the "close" icon in the component when the floating app switcher opens

- [ ] In desktop, panel should animate on like an overflow menu; in mobile, the animation remains a side push and still takes over the screen vertically

![image](https://user-images.githubusercontent.com/43144260/58050697-ad16e800-7b15-11e9-8e13-fd8556bb198b.png)

### Design specs:
https://github.com/carbon-design-system/carbon-website/issues/1200

**Comment by rcwakelin** [comment]
@jeanservaas Whats the status of this issue. Can I work with a demo or test site?

**Comment by jeanservaas** [comment]
@rcwakelin I just synced up with @vpicone and the problem is, we don't have anyone assigned to the Gatsby theme for this release... so no one's working on this stuff at the moment. Vince is working on the icon library project and Alison and Andrew Wang are still migrating IDL. 

We have the same problem on the Carbon site, we haven't had a dev resource on the Carbon site for three minor releases. We just don't have enough people at the moment.
