### ISSUE TITLE
pause button on lead space video and height inconsistent sizes

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#575]
- [ ]  IDL/Event sites are one size and Carbon, Brand Center, Security are a larger size. This should be included in Gatsby so we all can have the same size button.

- [ ] Lead space video height inconsistent heights. @jeanservaas @sadek can confirm the exact height but pretty sure IDL is correct height.

<img width="662" alt="Screen Shot 2019-12-01 at 3 50 35 PM" src="https://user-images.githubusercontent.com/32881239/69920840-568a4f00-1452-11ea-9325-eed6eb0346b3.png">

**Comment by jnm2377** [comment]
@mjabbink Is this a request for a new gatsby component then? A homepage video component? Right now these videos are components in each specific repo. They have different designs, so on the dev side my question is are we supposed to have two variations of this?

**Comment by mjabbink** [comment]
@jnm2377 I reckon. Each homepage has a video playing and has the little pause button. If a component with pause button already in place and scaled right it will be useful.

**Comment by mjabbink** [comment]
Why is this blocked?

**Comment by mjabbink** [comment]
@jeanservaas Currently the little pause button in our lead spaces is different sizes. The size in Carbon is fine by me so we need the spec you did here so we can get the same spec applied across the Gatsby sites that use it. @vpicone I reckon this needs to be part of the GT package?

**Comment by mjabbink** [comment]
@jnm2377 Nothing new. It’s just getting the pause icons the same size. Currently IDL site is smaller than the latest Gatsby theme spec.

**Comment by vpicone** [comment]
@mjabbink what's the preferred size?

**Comment by mjabbink** [comment]
Use the theme one so the only thing changing is IDL. All other sites have used the larger theme one so less of an issue to change

**Comment by mjabbink** [comment]
Looks resolved but one minor issue I see now the icons is moving between all the XG sites, Carbon, IDL by like 1–2 pixels. Seems like it should not be moving at all. Watson and Cloud are exactly the same and not sure if it is even possible to have them all be in the same place.

**Comment by mjabbink** [comment]
https://www.ibm.com/brand/systems/cloud/
https://www.ibm.com/brand/systems/watson
https://www.ibm.com/brand/systems/developer/
https://www.carbondesignsystem.com/
https://www.ibm.com/design/language/

**Comment by vpicone** [comment]
@mjabbink The home page video isn't a theme component. Those sites implemented their own version when they made their home page. so they'll each need to make their own updates to their homepage (like I did with IDL) if you wanna wrangle that pixel.
