### ISSUE TITLE
[Video]: HTML5 video element must contain a track element with kind="captions"

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#580]
## Detailed description

On the demo/documentation site, the `Video` component has a `track` without `kind="captions"`.

This generates the following DAP error:

<img width="1583" alt="Screen Shot 2019-12-03 at 9 43 39 AM" src="https://user-images.githubusercontent.com/9057921/70065968-84d27080-15b1-11ea-8b27-e6b3ab436739.png">

This error occurs on any pages utilizing the `Video` component with an inner `track` element (i.e., https://gatsby-theme-carbon.now.sh/components/Video/).

The [`kind` attribute defaults to `subtitles`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track#attr-kind), but it would be best to specify this value.

I think it would be ideal in this case to have the demo/documentation site demonstrate best practices with a `kind` attribute on every `<track>` element. It would also be ideal for the `Video` component page to include a brief explanation of the `kind` attribute, as well as `default` and `srcLang`.

### Relevant checkpoints

* [1.2.1 Audio-only and video-only](https://www.ibm.com/able/guidelines/ci162/audio_and_video.html)
* [1.2.4 Captions (live)](https://www.ibm.com/able/guidelines/ci162/captions_live.html)

**Comment by vpicone** [comment]
@jendowns this is a docs thing right? We don't do anything with the track since it's developer provided.

**Comment by jendowns** [comment]
Yeah @vpicone it looks like you'd be good if you added a `kind="captions` to the example page, as you did in your PR 👍
