### ISSUE TITLE
Enhancement[Video Component]: Making video component more robust

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#59]
@shixiedesign commented on [Wed Jan 02 2019](https://github.com/IBM/carbon-elements/issues/216)

- [x] custom play button
- [x] caption support
- [x] need to support mulitple aspect ratios

Dev issue for issue https://github.com/carbon-design-system/carbon-website/issues/473

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/ac7721c2-df30-45f2-8b1f-2bc52946a72a)

**Comment by alisonjoseph** [comment]
@abbeyhrt this was the video component we were talking about. there will be more to it, but the basic enhancement to start with is to be able to have a custom play button the same as we have here https://www.ibm.com/design/language/elements/2x-grid (on the second video down, the first one is vimeo and doesn't have it)

**Comment by vpicone** [comment]
@alisonjoseph @abbeyhrt is this closed?

**Comment by alisonjoseph** [comment]
yep
