### ISSUE TITLE
Update blockquote to roman (no italic)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#596]
The large blue quote should be roman not italic. Only the attribute "Paul Rand" should be in italic.

<img width="856" alt="Screen Shot 2019-12-02 at 10 17 01 AM" src="https://user-images.githubusercontent.com/32881239/70024082-f03f2280-155e-11ea-9dd6-96c7bdc3f4d7.png">

**Comment by vpicone** [comment]
closed as duplicate of #612
