### ISSUE TITLE
A few styling inconsistencies

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/gatsby-theme-carbon#6]
_Sorry I know this is still a WIP so feel free to ignore/close this if it's a known issue._

I noticed a few styling inconsistencies from the Carbon site:
- [ ] left nav should not have a drop shadow because it's pinned open. 
- [ ] right side app switcher drop shadow visible. App switcher should have a drop shadow, but only when open. This drop shadow should not be visible when app switcher is closed. 
![image](https://user-images.githubusercontent.com/15144993/56869003-e4372500-69bf-11e9-975a-8256931f9c51.png)
- [ ] footer is nudged right. Footer type should left align with main content.
![image](https://user-images.githubusercontent.com/15144993/56869023-4bed7000-69c0-11e9-982c-d666cc41dd77.png)

**Comment by vpicone** [comment]
I'll hop on these tomorrow thanks! Some others I'll cover with this issue

[ ] - dropdown carat issues on mobile
[ ] - body should be dark by default
