### ISSUE TITLE
[Tabs] Tab dropdown flickers on mobile.

### ISSUE THREAD

**Issue by SilverFox70** [carbon-design-system/gatsby-theme-carbon#604]
## Detailed description

We see a flicker when we select different tabs/options for all dropdowns: for example, this can be seen in the [Logo page](https://wwwtest.ibm.com/brand/systems/cloud/brand/logo#logotype-placement) on mobile devices. The flicker is on the new selected label. Logotype placement has 4 options. If you are selecting option 2 then you see that the label shifts/flickers when on mobile devices. 

Is there a way to update the underlying data after the dropdown collapses so that we don't see the flicker?

You can view this phenomenon on iPhone, Androids, and even on an in browser mobile emulator by navigation to a section with tabs and interacting with them.

**Comment by vpicone** [comment]
closed with #611
