### ISSUE TITLE
Header link off screen and undiscoverable on mobile

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#605]
It's really hard to find these links on mobile, since there's no hover effect. They're also off screen some.

<img width="307" alt="Screen Shot 2019-12-11 at 1 07 34 PM" src="https://user-images.githubusercontent.com/4078018/70652082-9d790100-1c17-11ea-93a8-2280c5033350.png">

**Comment by vpicone** [comment]
@carbon-design-system/design any input on how these should behave on mobile? Would having them be visible on phones all the time be an option?

**Comment by aagonzales** [comment]
I'm not a huge fan of them being always present on mobile. Unless we made the smaller and gray or something. Their too eye catching right now to always be present. 

What do other sites with anchor links to mobile?

**Comment by vpicone** [comment]
@aagonzales yeah I reduced the opacity in the screen shot, but I think you're right. Gatsby doesn't show them and wikipedia doesn't have them at all so I think it's kind of the wild west. I'm good with them being hidden like they are on desktop. I think you have to know they're there either way.

What do you think about them being cut off?

**Comment by aagonzales** [comment]
I would be +1 for hiding them on mobile as well if that's allowed.

**Comment by mjabbink** [comment]
Hidden in mobile I reckon

**Comment by luizamendes** [comment]
Hello, I would like to do this one, if that's okay. 😃

**Comment by vpicone** [comment]
@aagonzales @mjabbink i routinely link folks to content using these links on mobile, I’m not sure hiding them is the best option
