### ISSUE TITLE
[SkipToContent]: does not target any part of the page to allow skipping

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#606]
## Detailed description

The `SkipToContent` component is meant to link out to the main section of a page, to allow keyboard users to skip directly to that content.

Unfortunately, while the `SkipToContent` component currently links to `#main-content`, there is currently no element/target with that id on any of the pages. As a result, the `SkipToContent` link does not go anywhere. 

Ideally, there would be an element on the page somewhere with the `id="main-content"` so that when a user activates the `SkipToContent` link, they can jump to that element/target.

**Comment by jendowns** [comment]
I can open a PR to propose a fix for this shortly 👍

**Comment by jendowns** [comment]
Also FYI this affects the Carbon website as well -- but I assume that a change here would ultimately be absorbed into the website after a version bump?

**Comment by alisonjoseph** [comment]
Thanks @jendowns! and yep the change would be applied to all the websites using the theme once updated.
