### ISSUE TITLE
[build process] not able to use dev-server when using Yarn

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/gatsby-theme-carbon#609]
Hi,
NPM seems to be working when running the `getting started` instructions for `carbon-gatsby-theme`, however when using yarn I get this error:
![image](https://user-images.githubusercontent.com/14989804/70814866-5b2bfd00-1d9a-11ea-82ca-ba36d6c65e54.png)

When installing `gatsby-plugin-sass` I would get this error:
![image](https://user-images.githubusercontent.com/14989804/70814890-6b43dc80-1d9a-11ea-8b05-0fc3f4106b0b.png)

And installing both will result in one missing.

I'm not able to use NPM in this project as it runs on Yarn workspaces.

Yarn version: 1.16.0
NPM version: 6.12.1

**Comment by vpicone** [comment]
@theiliad I'm a bit confused, are you trying to do theme development or to use the theme? We use yarn for everything, so you should definitely be able to run dev server when using yarn.

**Comment by theiliad** [comment]
I'm using the theme based off of these instructions https://gatsby-theme-carbon.now.sh/getting-started

**Comment by vpicone** [comment]
Seems like this has been resolved

**Comment by theiliad** [comment]
Yeah my bad, not sure why I didn't close this
