### ISSUE TITLE
Aside: update large blue quote. Attribute should not be italics. Only the publication titles should be italic

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#612]
<img width="793" alt="Screen Shot 2019-12-14 at 2 56 58 PM" src="https://user-images.githubusercontent.com/32881239/70854531-b1746b00-1e82-11ea-8c72-1fa154511895.png">

**Comment by mjabbink** [comment]
Is it possible to hang the quote?
Like for these for example?

<img width="814" alt="Screen Shot 2019-12-14 at 2 55 13 PM" src="https://user-images.githubusercontent.com/32881239/70854593-67d85000-1e83-11ea-9f47-bf42db139ad2.png">

**Comment by mjabbink** [comment]
<img width="494" alt="Screen Shot 2019-12-14 at 3 11 37 PM" src="https://user-images.githubusercontent.com/32881239/70854649-12e90980-1e84-11ea-86a5-780d4f0c93d9.png">

**Comment by vpicone** [comment]
@mjabbink in https://github.com/carbon-design-system/gatsby-theme-carbon/issues/596

You mentioned the entire citation should be italic. If I understand correctly we want the entire thing to be roman except for a publication title if provided?

**Comment by mjabbink** [comment]
you are correct. Preserve italics for publications and titles of things like art objects or products i.e. Selectric.

**Comment by mjabbink** [comment]
and sorry. I made a mistake. I think they should remain the blue.

**Comment by mjabbink** [comment]
@jeanservaas I think this should still have an indent in mobile. Maybe 24 or 32px?
