### ISSUE TITLE
Switcher change for w3 Design launch

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#623]
![Screen Shot 2019-12-18 at 6 13 21 PM](https://user-images.githubusercontent.com/32881239/71134082-8c556480-21c2-11ea-8f23-346311dfe3fd.png)

**Comment by vpicone** [comment]
@mjabbink is this correct? 
<img width="252" alt="Screen Shot 2020-01-08 at 6 45 38 PM" src="https://user-images.githubusercontent.com/4078018/72028143-1daa7a80-3247-11ea-8651-ac4711619cc7.png">

**Comment by mjabbink** [comment]
I think so. I’ll triple check.

**Comment by mjabbink** [comment]
leave as it was. Do not execute this issue.
