### ISSUE TITLE
Image cards need label example

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#624]
The visual examples in Gatsby demo site are missing the actual use cases designed with labels on top of header.

The current as examples (below link) are not really used on the image cards to date. We have not been using the subtiltes on the bottom left.
https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/ImageCard/

<img width="1108" alt="Screen Shot 2019-12-28 at 1 37 02 PM" src="https://user-images.githubusercontent.com/32881239/71548685-4729f300-2977-11ea-8b76-2ff5fb0f3dfe.png">

or

no label

<img width="1146" alt="Screen Shot 2019-12-28 at 1 38 31 PM" src="https://user-images.githubusercontent.com/32881239/71548692-72acdd80-2977-11ea-85c1-66d46a71e78a.png">

—

<img width="1118" alt="Screen Shot 2019-12-28 at 1 38 59 PM" src="https://user-images.githubusercontent.com/32881239/71548693-77719180-2977-11ea-9c07-c6eced32f1c5.png">

**Comment by jnm2377** [comment]
so are we changing the subtitle from bottom left to top left, over the header? Or are we saying there should be 2 options? currently, the only option we have is subtitle on the bottom left. @mjabbink

**Comment by mjabbink** [comment]
@jnm2377 should keep both options, jut adding the option to have label above as in IDL homepage.

**Comment by mjabbink** [comment]
@jnm2377 Actually, I told you wrong. The “Image card” does not need the little subtitle at the bottom.
