### ISSUE TITLE
Link discrepencies

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#633]
Column links should not have an underline while the content links _should_. Carbon website has this correct.

Links inside of callouts should default to currentColor. They can be styled to match the background appropriately (like in the second, blue Carbon callout)

**Comment by jnm2377** [comment]
What do you mean by column links? Is there an example somewhere? @vpicone

**Comment by vpicone** [comment]
@jnm2377 the columns on the left (social links etc) in contrast to the links that are within the content on the right.

I actually accidentally include the fix for this in my open dependency update pr: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/632
