### ISSUE TITLE
fix[aside component]: breaks on top of body copy in mobile

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#634]
Rule in the aside component is breaking and appearing on top of the body copy in mobile.

desktop view:

![image](https://user-images.githubusercontent.com/43144260/71996138-4f98ee00-3201-11ea-823a-15b7fd9bee08.png)

mobile behavior:

![image](https://user-images.githubusercontent.com/43144260/71996157-5aec1980-3201-11ea-8202-ce119eb35049.png)

**Comment by jnm2377** [comment]
Closing for duplicate #574 
I've opened a PR for it.
