### ISSUE TITLE
Footer text off grid

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#636]
footer text and next button text to be vertically align. 

<img width="782" alt="Screen Shot 2020-01-08 at 3 01 31 PM" src="https://user-images.githubusercontent.com/32881239/72020327-2d1ec900-3231-11ea-91b9-2b5480087010.png">

**Comment by jnm2377** [comment]
Closing as a duplicate https://github.com/carbon-design-system/gatsby-theme-carbon/issues/569
