### ISSUE TITLE
UI icons page: missing images

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#642]
Missing images found here:
https://www.ibm.com/design/language/iconography/ui-icons/design#strokes

current:
![Screen Shot 2020-01-09 at 7.41.17 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/868122c0-252f-4737-a7e2-c2abe09740a3)

**Comment by mjabbink** [comment]
sorry, created this in wrong repo. Should be in IDL.

**Comment by vpicone** [comment]
Issue moved to [carbon-design-system/design-language-website #409](https://github.com/carbon-design-system/design-language-website/issues/409) via [**ZenHub**](https://www.zenhub.com/)
