### ISSUE TITLE
favicon for dark and light mode

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#651]
@Peter-Garvin to supply spec and artwork.

**Comment by mjabbink** [comment]
IDL and Brand Center “Bee” supplied by Pete
Carbon “Hexie” supplied by @jeannie

**Comment by peter-garvin** [comment]
This is the Bee UI icon at Gray 50

<img width="1792" alt="01_Bee_unPlated-G50_ChromeDark" src="https://user-images.githubusercontent.com/47458576/72390616-c564f400-36f0-11ea-8f50-76f8d6d3a662.png">
<img width="1792" alt="01_Bee_unPlated-G50_ChromeLight" src="https://user-images.githubusercontent.com/47458576/72390617-c564f400-36f0-11ea-9d2a-537fb38f730a.png">
<img width="1792" alt="02_Bee_unPlated-G50_FirefoxDark" src="https://user-images.githubusercontent.com/47458576/72390618-c564f400-36f0-11ea-9bad-e51cd7e51888.png">
<img width="1792" alt="02_Bee_unPlated-G50_FirefoxLight" src="https://user-images.githubusercontent.com/47458576/72390621-c564f400-36f0-11ea-8250-f1ba0cdc15a8.png">

**Comment by mjabbink** [comment]
@vpicone — When will these new light gray favicons show up on IDL and Brand Center?

**Comment by mjabbink** [comment]
@vpicone this issue was also about updating IDL not just the them and Carbon.

**Comment by vpicone** [comment]
Yeah brand center too, it’s on the list.
