### ISSUE TITLE
IDL/Carbon: Add overflow to icon & pictogram library

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#652]
Add overflow to to libraries. 

.
.
.

——————————————
Copy
——————————————
Download
——————————————

**Comment by mjabbink** [comment]
@jeanservaas if you need to add any specs please do.

**Comment by mjabbink** [comment]
@jeanservaas @aagonzales can one of you help to create any specs needed so @vpicone can rock on this feature enhancement

**Comment by vpicone** [comment]
@mjabbink busy on ComponentDemo, this is a website issue there's already an open issue for it: https://github.com/carbon-design-system/carbon-website/issues/766

**Comment by mjabbink** [comment]
this was not applied to IDL icons or pictograms library.

**Comment by vpicone** [comment]
@mjabbink the PR to add it to IDL is here: https://github.com/carbon-design-system/design-language-website/pull/439

This isn't a theme issue/feature.
