### ISSUE TITLE
fix[callout component]: H3 sitting too high; needs to break to two lines

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#664]
## fix[callout component]: H3 sitting too high; needs to break to two lines

- [ ] Move H3 in Gatsby Callout component down 3px so it optically aligns with the larger paragraph to the right.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/07c91436-a80b-4d02-ac61-c925f3880cba)

- [ ] H3 in Callout component needs to break to two lines

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/414b9886-a02c-4691-b760-daaad0acc592)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/7006834b-4c47-4f7c-80fd-d3b19fa10f07)

**Comment by xxxle0** [comment]
Should we reduce width of first column ?
