### ISSUE TITLE
Broken UI icon in IDL/Carbon icon library

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#665]
https://www.ibm.com/design/language/iconography/ui-icons/library

![Screen Shot 2020-01-16 at 5.42.56 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3ed9aef4-67b0-4f7f-9bb5-240085f76bb9)

**Comment by xxxle0** [comment]
hmm i think it's related to carbon/icons. It does not support for 32 icons size

**Comment by xxxle0** [comment]
This issue will be closed after @axon/icons package publish new version.

**Comment by vpicone** [comment]
closing in favor of @chrisconnors-ibm issue is with metadata upstream: https://github.com/carbon-design-system/carbon/issues/5224

**Comment by mjabbink** [comment]
@vpicone This is still broken in IDL.

**Comment by mjabbink** [comment]
if I make an issue in Gatsby that means both IDL and Carbon get’s updated. Not just Carbon. This seems to be happening on a handful of issues. You deploy in Carbon first and it can be days later before IDL gets the update.
