### ISSUE TITLE
Gatsby article card: include 1:1 image over card

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#668]
Maybe include a row of cards with 1:1 aspect ratio image

**Comment by mjabbink** [comment]
![Screen Shot 2020-01-17 at 8.38.14 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3f49c0f5-da12-4964-9da8-ec4033e76a48)

**Comment by vpicone** [comment]
The article card takes the aspect ratio of the image so this is possible today ![Screen Shot 2020-10-09 at 1.21.53 AM.png](https://images.zenhubusercontent.com/5deea65833c75ca22dbfaca3/7966aafc-b80c-4f51-bb13-c5f1e78ffc93)
