### ISSUE TITLE
Why not also export `carbon-components-react` components?

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#677]
## Summary

Right now components from `carbon-components-react` are passed through the mdx provider so that they can be used in `.mdx` files without having to add `carbon-components-react` as a dependency.  However, those components are not exported.

If a consumer is trying to use any Carbon react components (alongside this theme's components) in a new component they are creating in a `.js` file in their downstream site, there's no way to utilize something from `carbon-components-react` unless the consumer adds that library as an additional dependency.

So you can have a situation where you are using one version of `carbon-components-react` in mdx files, and then another version of `carbon-components-react` if you have to add it as a dependency in order to import something into a `.js` to create your own component, for example, to use your site.

So my question is -- **why not export all components (that make sense to export) from `carbon-components-react`?**

**Comment by vpicone** [comment]
@jendowns you don't have to install your own version of carbon-components-react, just disable the any eslint warnings and you'll get the themes version. If you install your own version, it the theme will use that version so long as it adheres to the semver-requirements.

**Comment by vpicone** [comment]
I opened this a bit ago: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/512

It seems that might be the correct way to go about it but would also be a breaking change.

**Comment by jendowns** [comment]
Thanks for the info @vpicone -- let me process this & get back to you 😅 
Admittedly it's not 100% intuitive so I want to go back and test a few things, given what you said above https://github.com/carbon-design-system/gatsby-theme-carbon/issues/677#issuecomment-577901691

**Comment by jendowns** [comment]
Okay just tried to experiment with this and I'm not getting ideal results...

Imagine this structure:
```
- my-components
  - CustomComponent.js
- pages
  - index.mdx
```

If I want to import `StructuredList` from `carbon-components-react` into my `CustomComponent.js`, I must add `carbon-components-react` as a dependency and import from there, otherwise I get a big error and the page breaks.

If I want import `StructuredList` into my `index.mdx`, I also still have to add `carbon-components-react` as a dependency and add import statements at the top of the file. If I don't and if I just try to use `StructuredList` with no import, the page build won't fail but the component won't be there.

Either way, whether using a Carbon component in a js or mdx file, it appears as though I need to add `carbon-components-rect` as a dependency and import the component from there. 🤔

**Comment by vpicone** [comment]
@jendowns so you think rexporting from index.js and also providing those components globablly in MDX as the mdx provider? I'm a little apprehensive about the latter since we of some overlap with ccr.

**Comment by jendowns** [comment]
@vpicone Yeah that's what I was thinking... but in the case where you all have redefined/changes a carbon component in some way, I think it would make sense to export that variation instead, like with the `Tabs` (to avoid the overlap).

**Comment by vpicone** [comment]
So something like 
```js
const components = {
  ...carbonComponentsReact,
  wrapper: function Wrapper({ children, ...props }) {
    return <div {...props}>{children}</div>;
  },
  h1: H1,
  h2: H2,
  h3: H3,
  h4: H4,
  h5: H5,
  //...
}
```
