### ISSUE TITLE
Remove target="_blank" from Theme

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#678]
All links created using markdown stay on the same tab, which is the default behavior.

The `ResourceCard` and `FeatureCard` components both need to match this. They currently open in a new tab.

![image](https://user-images.githubusercontent.com/15822070/72914313-1b92f200-3d04-11ea-9f1e-a58a80463580.png)

Users of the theme should be able to pass `target="_blank"` as a prop if they need it.

**Comment by xxxle0** [comment]
hi @sstrubberg, how about ArticleCard and ImageCard ?
