### ISSUE TITLE
Gatsby theme: Set content to columns in tables

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#682]
We gotta figure out a solution here. Not having content on defined columns structures cannot be the solution we continue with.

**Comment by mjabbink** [comment]
@mattrosno @alisonjoseph @jeanservaas 

Design needs the tables to support fitting content into the grid columns. It’s the entire premise of the grid and system and not a complicated demand as tables can do this. It has been pushed back for like 6–8 months so we cannot continue to push this back any longer. We need to figure out a way to accomplish this.

**Comment by vpicone** [comment]
@mjabbink first I’ve heard of it. Was there something before this Jan 23rd issue? There’s been lots of other priorities during that time.

**Comment by vpicone** [comment]
Gonna close this out for now until we can get a spec and figure out how things are supposed to look and feel on mobile
