### ISSUE TITLE
Broken UI icons

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#683]
![Screen Shot 2020-01-23 at 6.44.58 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/e8795155-7548-4338-8b11-ef51bd38aafb)

.
![Screen Shot 2020-01-23 at 6.45.04 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/6639fd83-ed64-4236-bf95-3c939db980aa)

**Comment by alisonjoseph** [comment]
Looks like this icon was just updated 7 days ago (https://github.com/carbon-design-system/carbon/tree/master/packages/icons/svg/32) @joshblack @vpicone would that be why its not showing up? should be fixed in next release, or is something else happening here?

**Comment by joshblack** [comment]
@alisonjoseph honestly not sure, the new icons should be published in our January release but I don't think any patches in the meantime have shared things like metadata that would cause them to show up here (but could be the case). Just not sure.

**Comment by mjabbink** [comment]
There are three missing. Not sure either but maybe @conradennis knows?

**Comment by jnm2377** [comment]
Closing this as a duplicate. @mjabbink you've already opened an issue for it here: https://github.com/carbon-design-system/gatsby-theme-carbon/issues/665
