### ISSUE TITLE
IDL: Pictograms: Alignment

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#691]
https://www.ibm.com/design/language/iconography/pictograms/usage#alignment

I believe in mobile we made this image stack? @conradennis can confirm. If I’m correct @conradennis can provide missing mobile images. If I’m wrong should we do it since it will be consistent with other similar guidance and images. Or leave it as is?

![Screen Shot 2020-01-17 at 4.48.14 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/a19bbd40-c740-4dc2-a722-e6af92d25242)

**Comment by conradennis** [comment]
@mjabbink This is one of the few in mobile I didn't make a stacked version for. Makes sense to make this one stacked too. 

image is here: https://ibm.box.com/s/hbqdlzul3wdgpzo3c0yjwyblxxid8njg

![Screen Shot 2020-01-29 at 10 37 29 AM](https://user-images.githubusercontent.com/16782944/73371274-74720580-4283-11ea-8409-c7bd4d39f728.png)
