### ISSUE TITLE
Is it possible to fully disable gatsby-source-medium-feed?

### ISSUE THREAD

**Issue by weslleyaraujo** [carbon-design-system/gatsby-theme-carbon#692]
## Summary

Hi folks, I was wondering if there is a way to completely disable `gatsby-source-medium-feed` during build process

The problem that I am currently facing is that I am working behind a corporate proxy, during build process I believe this http call is being executed:

https://github.com/devs-group/gatsby-source-medium-feed/blob/master/src/gatsby-node.js#L11

(this plugin is being used at: https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/gatsby-config.js#L125)

Which causes my build to fail 😅

```
$ gatsby build
success open and validate gatsby-configs - 0.098s
success load plugins - 1.420s
success onPreInit - 0.015s
success delete html and css files from previous builds - 0.014s
success initialize cache - 0.012s
success copy gatsby files - 0.044s
success onPreBootstrap - 0.017s
success createSchemaCustomization - 0.003s
error "gatsby-source-medium-feed" threw an error while running the sourceNodes lifecycle:

connect ENETUNREACH 104.16.122.127:443

  Error: connect ENETUNREACH 104.16.122.127:443
```

For my use case I don't have the need for medium integration, would be nice if I could disable it completely

**Comment by vpicone** [comment]
Not at the moment, but it prevents offline development which is a bit of a pain. Will try and prioritize this.

**Comment by vpicone** [comment]
@sstrubberg you wanna work on this together?
