### ISSUE TITLE
How are ComponentDemos actually written

### ISSUE THREAD

**Issue by helmutgranda** [carbon-design-system/gatsby-theme-carbon#695]
##  Summary

What is the proper way to write ComponentDemo samples, I have tried to replicate how the ComponentDemo works but when I write it as it is in your documentation it fails:

<ComponentDemo>{`<Button>Hello World!</Button>`}</ComponentDemo>

When I write it as such it works as expected:

<ComponentDemo><Button>Hello World!</Button></ComponentDemo>

## Relevant information

I was following the following document to extend the functionality of a ComponentDemo:

https://raw.githubusercontent.com/carbon-design-system/carbon-website/390b4fe9d6281add5ae30e4fcb1262873d8d5b61/src/pages/components/button/code.mdx

However, that was only rendering the data provided but not actually the HTML elements. 

I have tried to follow the code as much as possible, even as to add all my defaultComponents to my gatbsy-browser.js and it still doesn't work as it does on yours.

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js

Is this functionality only available when we inject the defaultComponents into a template?

**Comment by vpicone** [comment]
@helmutgranda this component is built in and for the carbon design system website. We're working out the API/ux there and will eventually migrate it to the theme once things are ironed out.

I opened https://github.com/carbon-design-system/carbon-website/issues/870 on the carbon-website repo if you wanna track it. It might be a few weeks before we have the chance to prioritize it.

**Comment by vpicone** [comment]
closing this in favor of https://github.com/carbon-design-system/carbon-website/issues/870

**Comment by helmutgranda** [comment]
No problem at all and thanks for the clarification. It did hold me back a couple of hours because I couldn't get it to work per the comment above until I tried on its own. Looking forward to see the development on your end.
