### ISSUE TITLE
Carbon Components: Tag not pulling correct component

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#699]
Looks like this is pulling some janked component. The type is inspecting at 16px vs. 12px

![Screen Shot 2020-02-03 at 3.29.41 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ad702483-87fb-4422-a614-4b2f3b293e96)

**Comment by xxxle0** [comment]
https://github.com/carbon-design-system/carbon/pull/5182 this issue is fixed by this PR

**Comment by vpicone** [comment]
Closing per above, will be fixed next Carbon release.

**Comment by mjabbink** [comment]
@mattrosno @jeanservaas Our release dates need to change. This has been 18 days. We need to be able to deploy certain issues as soon as they’re fixed or within a week.
