### ISSUE TITLE
Where do we add new custom components

### ISSUE THREAD

**Issue by helmutgranda** [carbon-design-system/gatsby-theme-carbon#705]
## Summary
Looking at the documentation it talks about Shadowing but it does not talk about brand new components, is it safe to assume we can add them into gatsby-theme-carbon/components/ ?

## Relevant information

I am happy to update the documentation once we know what is the best place recommended to be used for our custom components.

**Comment by helmutgranda** [comment]
I would imagine if we are to create custom components in the location above we should be shadowing this file as well?

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/index.js

**Comment by helmutgranda** [comment]
One more file that would have to be updated?

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/src/components/MDXProvider/defaultComponents.js

**Comment by vpicone** [comment]
@helmetgranda yeah you got it. You only need to shadow the second file you linked. We import `defaultComponents` so the theme will grab yours rather than it's own. Be sure to spread the theme's default components into your own. 

Checkout out the carbon website for an example:

https://github.com/carbon-design-system/carbon-website/blob/master/src/gatsby-theme-carbon/components/MDXProvider/defaultComponents.js

**Comment by vpicone** [comment]
Closing this, feel free to let me know if you have any other questions!

**Comment by helmutgranda** [comment]
Thanks for the confirmation and for linking me to the defaultComponents.js file. I forgot about the spread operator! So I manually updated the link resources. 

One more question, are you all going to update the gatsby theme to include the way you show off code? 

This:
https://gatsby-theme-carbon.now.sh/components/Accordion

vs this:
https://www.carbondesignsystem.com/components/accordion/code

I know how to add the tabs which I am using on our custom version but I am looking more on how the knobs and the code demo area is implemented.

**Comment by vpicone** [comment]
@helmutgranda we’re still iterating on that component and rolling it out to the rest of the Carbon website. 

It’s not a priority for us at the moment, but we have this issue open to try and tackle it eventually: https://github.com/carbon-design-system/carbon-website/issues/870

Might be something like Q3.
