### ISSUE TITLE
Spacing after intro is too tight [Gallery page]

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#709]
https://www.ibm.com/design/language/gallery

Gatsby theme issue. Effects the gallery page here as well (need to log in with IBM credentials):
— https://www.ibm.com/brand/systems/watson/brand/gallery 
— https://www.ibm.com/design/event/gallery

The spacing the intro copy and the first row of images is too tight. I’ll let @sadek or @jeanservaas respond with more exact specs.

![Screen Shot 2020-02-05 at 10.01.52 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fb99c36f-309b-4f0e-88db-83e62428ebff)

**Comment by mjabbink** [comment]
@sadekbazaraa What should the space spec be between bottom of text and images?

**Comment by sadekbazaraa** [comment]
@mjabbink this is one of those areas that we'll need to override. I believe the images are using the default spacing of 24px **above** which is what is dictating this space. I know we're having separate conversations with Vince about making 32 the default for images.

Of course, in this case, we'd like to have more breathing room. There used to be 80px there. This 80px logic matches what we're doing after the intro paragraph and/or anchor links on most of our pages. It's actually the spacing **above** the large header that is creating the customary 80px though. In this case we're following the intro quote with an image so we need to add more. Make sense?

![Screen Shot 2020-07-24 at 10 55 19 AM](https://user-images.githubusercontent.com/33162280/88405936-f14aeb80-cd9d-11ea-9b28-6a47e1d6302e.png)

It should be like this:

![Screen Shot 2020-07-24 at 10 55 47 AM](https://user-images.githubusercontent.com/33162280/88405979-032c8e80-cd9e-11ea-908b-f1732d12b408.png)

And while we're refining and cleaning things up, we should probably apply the same thinking to the home page which seems a little wonky currently. My suggestion there to keep everything consistent would be this:

![Screen Shot 2020-07-24 at 11 01 22 AM](https://user-images.githubusercontent.com/33162280/88406221-5ef71780-cd9e-11ea-979d-ff312b72ab29.png)
