### ISSUE TITLE
Feature request: Large page header (lead space) size variant

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#71]
We need to look into how devs could signal from MDX to use the larger page header for a specific page. One approach is to provide an alternate layout for them to export. This is how the Homepage is handled atm. This would be appropriate if the layout was dramatically different.

Another is option is to export a variable/options object that would be passed down on the page context: https://gatsby-mdx.netlify.com/misc

> The lead space should have two options. the shortie that Carbon uses on component pages for example and the one the DL site uses which is the next size up. I think it’s 320. Both sizes will be needed I think.

**Comment by mjabbink** [comment]
@vpicone  There was an issue created by @jeanservaas to make lead space height same as IDL as well. I believe there was only an 80px difference and taller is nicer. I cannot seem to find that issue any longer?

**Comment by alisonjoseph** [comment]
I think this can be closed since we want to keep the header size standard.
