### ISSUE TITLE
Footer and PageHeader alignment issues

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#72]
There are some alignment bugs occurring around some core components. Notably the PageHeader and Footer components.

### PageHeader 
The title text is different than the IDL implementation

![54e69a00-7826-11e9-82b2-fc20a1c71f00](https://user-images.githubusercontent.com/4078018/57942864-2a352980-7898-11e9-9cce-6717191b0b32.png)

### Footer
Looks to be some padding issues in relation to the content

![Screen Shot 2019-05-17 at 11 35 57 AM](https://user-images.githubusercontent.com/4078018/57942897-3e792680-7898-11e9-9903-ba2b4eec6f85.png)

**Comment by alisonjoseph** [comment]
Footer still looks off, but the header should be fixed https://github.com/carbon-design-system/gatsby-theme-carbon/pull/66
