### ISSUE TITLE
Should the InlineNotification hang into the gutter?

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/gatsby-theme-carbon#724]
See any of the Carbon website tutorials that have lots of code snippets and inline notifications. Should the background of the inline notifications hang into the gutter like the code snippets?

(Double border on inline notifications has already been fixed, but not visible in this screenshot yet. https://github.com/carbon-design-system/gatsby-theme-carbon/issues/718)

![image](https://user-images.githubusercontent.com/1691245/74452831-34944c00-4e47-11ea-94a6-02f584823d1d.png)

**Comment by jnm2377** [comment]
cc: @jeanservaas @mjabbink

**Comment by vpicone** [comment]
Closing this, I think @mjabbink and @jeanservaas would have identified this by now if it was off. Feel free to open again if this behavior isn't intended.
