### ISSUE TITLE
Add download functionality to UI icons and pictograms

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#727]

**Comment by vpicone** [comment]
@mjabbink you're killing me! This isn't a theme issue, it's already live in Carbon and the PR to add it to IDL is open.

**Comment by mjabbink** [comment]
can we deploy. I have been pinged 4–5 times now with people telling me it’s broken

**Comment by mjabbink** [comment]
@vpicone I know this was not a theme issue but it was a IDL issue to add to IDL. It went live in Carbon first for days before it showed up in IDL. I hope you recovered from me killing you.

**Comment by mjabbink** [comment]
I see, this is Gatsby board. I’m confused as I thought his was for IDL too.
