### ISSUE TITLE
replace “pictogram grid” resource card on “no results found” filter w/ “Download pictogram master” resource card

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#728]
https://www.ibm.com/design/language/iconography/pictograms/library

![Screen Shot 2020-02-17 at 5.04.45 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/0e5c6fc8-e862-403d-9d1e-c007a913d3df)

change to:

![Screen Shot 2020-02-17 at 5.04.57 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/50d0eb1c-d0cd-4e48-a86d-8e074a7a7eeb)

correct resource card can be seen here:
https://www.ibm.com/design/language/iconography/pictograms/design#resources

**Comment by sstrubberg** [comment]
Can i get that Illustrator logo?
