### ISSUE TITLE
Apply recent spacing updates to theme demo site

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#729]
some examples of where in the site:
https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/DoDontExample/

https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/Caption#code

https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/InlineNotification#example

—————————

<img width="631" alt="Screen Shot 2020-02-17 at 5 00 09 PM" src="https://user-images.githubusercontent.com/32881239/74691448-e5387d80-51b0-11ea-9be6-a0846c19e018.png">

—————————

<img width="895" alt="Screen Shot 2020-02-17 at 5 00 04 PM" src="https://user-images.githubusercontent.com/32881239/74691451-e9649b00-51b0-11ea-81eb-e084f23d92ef.png">

—————————

<img width="854" alt="Screen Shot 2020-02-17 at 4 59 58 PM" src="https://user-images.githubusercontent.com/32881239/74691460-ee294f00-51b0-11ea-9ee9-9d10618a35f6.png">

**Comment by sstrubberg** [comment]
Just checked the site and it looks resolved. @mjabbink can you confirm?
