### ISSUE TITLE
Next/Prev buttons alignment

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#730]
The next buttons in footer are out of sync.

<img width="905" alt="Screen Shot 2019-12-17 at 2 00 00 PM" src="https://user-images.githubusercontent.com/32881239/71029739-9ea5a480-20d5-11ea-8f3c-a03bf934b2d7.png">

**Comment by mjabbink** [comment]
Not resolved in live site

**Comment by vpicone** [comment]
@mjabbink which live site?

**Comment by vpicone** [comment]
@mjabbink are you still seeing this somewhere that has the latest theme? Gonna close this for now since I’m pretty sure it’s resolved.
