### ISSUE TITLE
Smart quotes are rendering as helvetica neue — yikes!

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#735]
Need to update variable font subsetting to include smart quotes

**Comment by mjabbink** [comment]
Good eye @vpicone! A biggie to resolve and update.

**Comment by sstrubberg** [comment]
@vpicone Hanging out in `_plex.scss`, reading a lot about unicode-ranges, but not seeing where to add the quoteys. Am I sniffing in the right place?

**Comment by vpicone** [comment]
@sstrubberg this likely has to do with the font-file itself not containing the quotes. We subset the variable font file so it's not so large but this character must have slipped the cracks.

**Comment by mjabbink** [comment]
https://www.fileformat.info/info/unicode/char/201c/index.htm

**Comment by mjabbink** [comment]
https://www.fileformat.info/info/unicode/char/201d/index.htm

**Comment by vpicone** [comment]
@mjabbink brilliant, I think single quotes too. They're outside the typical latin range, I got a little overzealous trimming the font file.

**Comment by mjabbink** [comment]
You trimmed the font file? The correct quotes and single quotes are part of every basic Latin font. Removing them would could all editorial copy to not be correct.

**Comment by mjabbink** [comment]
Meaning those glyphs are critical to copy

**Comment by mjabbink** [comment]
And please do not edit of remove glyphs!

**Comment by vpicone** [comment]
@mjabbink We split it up for for latin, cyr, greek so you don't download all of the glyphs if a site only uses latin. I get that they're critical to copy, that's why this issue exists!

**Comment by mjabbink** [comment]
Isn’t that how we delivered in GitHub?

**Comment by mjabbink** [comment]
I understand what font files need to be delivered as what you see is a reflection of that.

But I understand from your earlier post you removed those glyphs being over zealous. I may have misunderstood but I thought you made new files which should not be done.
