### ISSUE TITLE
UI Icons: Update library (and Sketch kit) with new weather icons.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#737]
There are 35 or more weather channel icons @conradennis created and are now in the repo but need to be added to library. The weather channel peeps are ready to use these bad boys.

![64835280-1b6b-11ea-87d6-83821c03a723](https://user-images.githubusercontent.com/32881239/74977960-b82adb80-53f9-11ea-996e-5cd3b4590294.png)

**Comment by vpicone** [comment]
@mjabbink they're in the Carbon repo but not release yet. When Carbon publishes their icons package we'll get the new icons.

**Comment by vpicone** [comment]
Blocked by https://github.com/carbon-design-system/carbon/issues/5398

**Comment by mjabbink** [comment]
They seem to also be in the library which is good. So they only still need to be added to the Sketch kit?

**Comment by vpicone** [comment]
@mjabbink not sure, we don't interact with the sketch kit in the gatsby theme. I'd ask @laurenmrice and open an issue in the Carbon repo if these aren't in the sketch kit yet.

Gonna close this one, since the icons were added to Carbon and IDL.

**Comment by laurenmrice** [comment]
@mjabbink @vpicone Yes i am seeing those in the latest icon plugin generation that josh gave me to review, those will be in the sketch libraries once we release it. 👍🏻

**Comment by mjabbink** [comment]
Sweet.
