### ISSUE TITLE
Code snip component should have horizontal rule above ”Show more“ action

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#74]
Current:

<img width="767" alt="Screen Shot 2019-05-17 at 1 54 48 PM" src="https://user-images.githubusercontent.com/32881239/57946956-9ec59380-78ab-11e9-8404-a0d43f1345bc.png">

Expected:

<img width="954" alt="Screen Shot 2019-05-17 at 1 55 34 PM" src="https://user-images.githubusercontent.com/32881239/57946970-a84efb80-78ab-11e9-9a68-4e7e583b93a9.png">

I think the container should go into gutter as well. Seems to do so in Carb site

<img width="422" alt="Screen Shot 2019-05-17 at 2 00 55 PM" src="https://user-images.githubusercontent.com/32881239/57947187-3c20c780-78ac-11e9-9718-d0e7e7eb80ca.png">

**Comment by alisonjoseph** [comment]
The "expected" code snippet is a more advanced one currently only being used on component pages.  

This component is however still a WIP and we just ported over the most basic styles. You're correct, it will hang in the gutter. and the font needs to be updated etc.

**Comment by mjabbink** [comment]
the horizontal line above the "Show more w/ chevron" is a nice touch too.

**Comment by jnm2377** [comment]
Closing, as we don't have this feature in our code snippet anymore (though, we have plans to bring it back)

**Comment by mjabbink** [comment]
This is used on Carbon pages in Components and needs to be used on the “2x Grid” page here for example:
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation#responsive-options

This was a priority for @jeanservaas and me and missed it was closed.

**Comment by alisonjoseph** [comment]
duplicate, closing in favor of newer issue #473
