### ISSUE TITLE
remove double outline and diagonal edge for inline notification 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#748]
There should not be the two lines with different colors or the left thick line with diagonal ends

![Screen Shot 2020-03-02 at 11.53.20 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/a61ff597-293a-4a76-b9d9-cb74ec8a5276)

![Screen Shot 2020-03-02 at 11.53.13 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/0a05beae-d6c4-4760-b46b-759ce51e580f)

**Comment by mjabbink** [comment]
![Screen Shot 2020-03-02 at 11.53.07 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3748df96-f61e-4156-bff4-2c90a8eec667)


![Screen Shot 2020-03-02 at 11.51.08 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/0e22b83f-3602-4918-8db8-ca3c2dd1b78f)

**Comment by mjabbink** [comment]
Also the purple visited link is still showing up here.

**Comment by vpicone** [comment]
@mjabbink are you sure you're looking at the current version of the theme?

I can't replicate either of these problems in Safari, Chrome or Firefox.

**Comment by mjabbink** [comment]
I’ll double check. Could be I have not updated.

I did notice this morning in mobile the page horizontally scrolls. Should I make issue?

**Comment by mjabbink** [comment]
Still shows up in Chrome. I cleared cache.
Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by mjabbink** [comment]
same in Safari. Cleared cache and looks the same as images above.

**Comment by vpicone** [comment]
Hmmm, I'm using the same build but can't replicate this.

![Screen Shot 2020-03-03 at 11 15 53 AM](https://user-images.githubusercontent.com/4078018/75801219-61e66280-5d40-11ea-811c-5e4302518881.png)

Are you also seeing it with in Carbon's [InlineNotification storybook?](https://react.carbondesignsystem.com/iframe.html?id=notifications--inline&knob-The%20notification%20kind%20(kind)=info&knob-Use%20low%20contrast%20variant%20(lowContrast)=true&knob-ARIA%20role%20(role)=alert&knob-Title%20(title)=Notification%20title&knob-Icon%20description%20(iconDescription)=describes%20the%20close%20button&knob-Status%20icon%20description%20(statusIconDescription)=describes%20the%20status%20icon&knob-Action%20(NotificationActionButton%20%3E%20children)=Action)

**Comment by vpicone** [comment]
@mjabbink opened https://github.com/carbon-design-system/gatsby-theme-carbon/issues/749 to fix the overflow issue.
