### ISSUE TITLE
Resource cards: the icon should not have white container visible on hover

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#77]
There should also be a max width. The sample below right is about as long as line should before going to two lines. I also wonder if we limit this to one line to force keeping these very simple, short and sweet. 

<img width="796" alt="Screen Shot 2019-05-18 at 12 04 19 PM" src="https://user-images.githubusercontent.com/32881239/57972199-33d89300-7965-11e9-8df8-4d6af99cc34c.png">

**Comment by mjabbink** [comment]
sample of too long (right resource card)

<img width="810" alt="Screen Shot 2019-05-18 at 12 09 19 PM" src="https://user-images.githubusercontent.com/32881239/57972250-dd1f8900-7965-11e9-8b21-c5299225de42.png">

**Comment by alisonjoseph** [comment]
All these have been fixed already I believe 😄 

We added a padding-right of I believe 25% (to match Carbon/IDL)

**Comment by mjabbink** [comment]
cool. The AKQA team has to catch up. I’ll let them know you fixed.
