### ISSUE TITLE
Scrolling behavior when selecting item in left nav

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/gatsby-theme-carbon#770]
### Summary

The current left nav scrolls back to the top after a menu item is selected. This can be frustrating and disorienting when a user is navigating between items on the lower section of a long nav. This happens in chrome, firefox, edge, and safari.

![Mar-09-2020 13-23-41](https://user-images.githubusercontent.com/19270502/76245746-69a77a80-620a-11ea-9812-d71d22eaf050.gif)

### Desired UX and success metrics
The left nav should maintain it's position after the user makes a selection and not scroll back to the top.

**Comment by jnm2377** [comment]
closing as duplicate for https://github.com/carbon-design-system/gatsby-theme-carbon/issues/345
PR to fix this coming soon
