### ISSUE TITLE
Add modeless feedback dialog for each page

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#771]
### Summary

Add the ability for website users to give low-friction quick feedback on each page.

Examples:
1. [gatsby](https://www.gatsbyjs.org/docs/) – bottom right
2. [watson health](https://pages.github.ibm.com/Watson-Health/index.html) – bottom right

### Justification

Our current team objective is to: 

> Significantly scale the engagement, collaboration, and enthusiastic adoption of Carbon by IBM product teams. 

Allowing per-page feedback will allow us to get real-time feedback on our documentation and components.

### Desired UX and success metrics

Users can click an unobtrusive button to open a modeless dialog which allows them to give feedback (e.g. positive, negative, and neutral) as well as a comment. These survey responses should be viewable in a dashboard.

**Comment by jeanservaas** [comment]
@mjabbink what do you think? Three options, it has to go at least 80 in any color spectrum to really stand out over a 90 background

## Question 1: Color

**Teal 80 with Teal 70 hover (icon stays outlined)**

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/43144260/76478681-788f5800-63d7-11ea-95ae-0a9404491621.png">

<br>

**Purple 80 with Purple 70 hover (icon stays outlined)**

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/43144260/76479063-91e4d400-63d8-11ea-90f0-fb1dd7afda58.png">


<br>

**Gray 70 with Gray 60 hover (icon stays outlined) — I think this is elegant**


<img width="1253" alt="image" src="https://user-images.githubusercontent.com/43144260/76479411-ae354080-63d9-11ea-88b2-89613c67d146.png">


<br>

## Question 2: Solid or outlined icon on hover (Ding Ding Ding)

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/43144260/76479268-38c97000-63d9-11ea-9fa2-f7a0f0523b0d.png">

**Comment by vpicone** [comment]
@jeanservaas should we make any changes to the colors of the back to top button? maybe inverted from the winky?

Maybe we should have the hover states disappear when opened.

**Comment by mjabbink** [comment]
I like the Grey 70. Teal is second choice but would need to see it in a page context.I don’t think you need to fill the icon though. Save that for last if needed.
 
Looks cool. I’m curious how many people will use this. Hopefully we gather useful feedback. Wanna also do think IDL and BC sites.
 
m 
Mike AbbinkExecutive Creative Director,
IBM Brand Experience & Design,
IBM Distinguished Designer
+1 917 291 7516
 
IBM
 
 
----- Original message -----From: jeanservaas <notifications@github.com>To: carbon-design-system/gatsby-theme-carbon <gatsby-theme-carbon@noreply.github.com>Cc: Mike Abbink <mjabbink@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [carbon-design-system/gatsby-theme-carbon] Add modeless feedback dialog for each page (#771)Date: Wed, Mar 11, 2020 8:49 PM 
 
@mjabbink what do you think? Three options, it has to go at least 80 in any color spectrum to really stand out over a 90 background
Question 1: Color
Teal 80 with Teal 70 hover (icon stays outlined)
 

Purple 80 with Purple 70 hover (icon stays outlined)
 

Gray 70 with Gray 60 hover (icon stays outlined) — I think this is elegant
 

Question 2: Solid or outlined icon on hover (Ding Ding Ding)

**Comment by mjabbink** [comment]
Lean on grey 79 but also think teal 80 can work

**Comment by jeanservaas** [comment]
Hey Vince

Couple of tweaks after our crit yesterday (here's the new spec)

- we are actually going to go Gray 60 with the feedback button because Gray 60 is actually our secondary button color in the dark themes. So we might as well make it consistent rather than randomly going Gray 70. 

- Also, the icon will need to stay white at all times, not pop up to white on hover, anything less than white on a Gray 60 background will not be contrast accessible.

- The outlined icon will go filled when the dialog is open

- there is no hover state when the dialog is open

<img width="427" alt="image" src="https://user-images.githubusercontent.com/43144260/76646784-966cd200-6529-11ea-8da6-b6fd8074f427.png">

ps I'm going to come back and add a design for what happens when you hit Send feedback... we will need some kind of visual confirmation.

**Comment by vpicone** [comment]
For the focus, blue-60 (inverse-focus-ui) and gray-60 (secondary) don’t meet the contrast requirements.

I think we need to keep the white line inset that I have now?

**Comment by vpicone** [comment]
@jeanservaas updated with:
- animating checkmark
- full width on mobile
- launch button styles
