### ISSUE TITLE
feedback component: update motion per shixie's specs

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#790]
## Feedback component: update motion per shixie's specs

Shixie's advice on motion:

- (If the circle is filled) Do an outline of the stroke before filling the circle would help. That’s probably the lower hanging fruit. Draw on the check mark (I was too lazy to do it, but drawing it on vs. fading it in is better)

- dialogue can open with CTA sliding in slightly delayed (also according to guidelines, dialogue should open with x-dir expansion starting before y-dir expansion, but that’s prob too hard to do)

- after user click “submit”, dialogue should close automatically after a brief delay (I used 300ms. I think up to 1 second is all okay) 

- Also shouldn’t we avoid ! according to IBM style guidance? I changed “Thanks” to “Thank you.” 

Shixie made an example and included source files (I added to her file so you can see how the interior stuff animates): https://ibm.box.com/s/hap5dmjj5ltt3ztzh7u017w16d9opli6

In Principle you can see curves and frame timing:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/99bc6935-b4a6-4466-9603-5b1abf903599)

**Comment by mjabbink** [comment]
@jeanservaas @vpicone Low priority but seeing this in action for a while and using Acrobat which has multiple buttons that float in the same position I think these need to be the same color. The extra color just adds more noice whilst the same color calms the situation down and easier on the eyes. Basically I thin the face needs to go black and have same background as jump to top of page.

**Comment by vpicone** [comment]
@mjabbink which parts need to be the same color? Maybe @jeanservaas could mock it.

**Comment by mjabbink** [comment]
The circle background should be same between them (the lighter). The con needs to to black or whatever the up icon is (could be G100). The givers are already the same

**Comment by mjabbink** [comment]
@jeanservaas see above. I think the feedback button and jump to top button should be the same color. I think either work so you can choose the light or dark grey. The hovers are already the same. The two colors just adds more noise.

**Comment by jeanservaas** [comment]
@mjabbink 

Is this what you want to see? I think one of the problems with this is the lack of relationship to the feedback component when it's open, when the background on the circle is Gray 30. 

Also, this issue was originally about motion updates for the feedback component. So if we're just doing a quick color change, unless we also do the motion updates, I don't want it to be closed. 

I know you wanted some potential type size changes to @mjabbink so I'm wondering if we open another design issue here. 

**closed**

![image](https://user-images.githubusercontent.com/43144260/85312628-11c51480-b485-11ea-9dde-ecf79de70ca6.png)

**open**

![image](https://user-images.githubusercontent.com/43144260/85312659-21445d80-b485-11ea-88f7-36a439a86f03.png)

**Comment by mjabbink** [comment]
yes. Or they both could be the darker grey you spec’d. Either works for me.
