### ISSUE TITLE
[Gatsby] Component Request: Add mini resource card to Theme

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#794]
Security team (Randy) developed this already and we should finalize and add to the them. @jeanservaas has some additional specs to adjust to the code. She can provide.

@vpicone Once this is a component in the theme we need to make sure the one we’re did in IDL Data visualization pages is the component from the theme. Currently you can see what Greeshma created in staging: https://deploy-preview-471--design-language-website.netlify.com/design/language/data-visualization/design/basics/

Same is true for Security I reckon.
sample here:
https://pages.github.ibm.com/security/experience-guide/consumability/overview

**Comment by mjabbink** [comment]
@jeanservaas can you provide any spec oversight here in the issue

**Comment by jeanservaas** [comment]
## Mini Resource Card

### Mini Resource Card in margin (wide grid mode: no hang)
(type and icon vertically centered)

**1312 XL breakpoint**

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/43144260/77805553-29405d00-7050-11ea-829b-d710e3062225.png">


**1056 L breakpoint**

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/43144260/77805429-d9619600-704f-11ea-8f5a-518709ca8a78.png">

**Comment by mjabbink** [comment]
Thanks @jeanservaas! Bad ass.

**Comment by vpicone** [comment]
@jeanservaas @mjabbink the hardest part about this is likely going to be the aside/margin business. We'll take a crack at it next week.

**Comment by mjabbink** [comment]
@jeanservaas we probably need the little G20 line when two stack in light theme

**Comment by vpicone** [comment]
@sstrubberg Initially I thought we could stuff this logic into ResourceCard but I think it's better to make a MiniCard to avoid stuffing too much logic into the ResourceCard. We can pair on this one to start it going in a good direction if you want.

**Comment by vpicone** [comment]
and resource card group!
