### ISSUE TITLE
Generic spacing selector trumps heading margins

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/gatsby-theme-carbon#796]
### Detailed description

We're currently having an issue in our environment where the generic spacing selector is trumping the heading margins, which means these values end up getting set as `1.5rem` as opposed to something like `5rem` for `h2` - 

<img width="1680" alt="Spacing" src="https://user-images.githubusercontent.com/3846874/78050601-5fdde680-7374-11ea-8017-7ef2642e793f.png">

When debugging, we removed any additional styles we supply to no success - Another thing to note is that when rolling back to `v1.15.3`, the issue no longer manifests itself.

**Comment by SimonFinney** [comment]
As an update - I've been able to isolate this issue down to it occurring when the `Main` component is not imported / used when shadowing the `Homepage` component.

**Comment by agarwaldax** [comment]
@SimonFinney Can you share how you created the workaround in your shadowed `Homepage` component?

**Comment by vpicone** [comment]
@SimonFinney do you know if this issue was resolved? @agarwaldax what version of the theme are you using, do you have a preview somewhere?

**Comment by agarwaldax** [comment]
I'm using the latest, v1.25.0. You can preview the build here: https://pages.github.ibm.com/CPD-Design/home/design-guidelines

**Comment by agarwaldax** [comment]
@vpicone After a little digging, this import in my custom component is causing the issue: 
`import H2 from 'gatsby-theme-carbon/src/components/markdown/H2.js';`

It seems to have a side effect of changing CSS specificity.
Is there another way to add a Heading to my custom component?

**Comment by vpicone** [comment]
@agarwaldax wrather than importing the `H2` react component, try importing the `h2` class from `packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss` and applying it to an `h2` element in your custom component/.

```jsx
import React from 'react';
import { h2 } from 'packages/gatsby-theme-carbon/src/components/markdown/Markdown.module.scss';


export default () => <h2 className={h2}>Title</h2>
```

**Comment by vpicone** [comment]
Gonna close this for now, I believe that class name thing should work! Let me know if not.
