### ISSUE TITLE
Links on the Carbon website do not follow the Link component style

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/gatsby-theme-carbon#805]
## Detailed description

The Carbon [Link](https://www.carbondesignsystem.com/components/link/style/) component suggests that link text should not be underlined apart from when the link text is in the hover state: 
> ![Screenshot 2020-04-03 at 15 51 49](https://user-images.githubusercontent.com/9316771/78374145-657d3b80-75c3-11ea-9ef7-20dce72f53c5.png)

Yet throughout the Carbon website, links are shown with the link text underlined: 
> ![Screenshot 2020-04-03 at 15 54 43](https://user-images.githubusercontent.com/9316771/78374275-8ba2db80-75c3-11ea-8782-c9aa5204d8a7.png)

This is likely to confuse people  - and might well result in them (incorrectly) believing that the Carbon style is to have underlined link text in their product UIs.

**Comment by alisonjoseph** [comment]
@jeanservaas @mjabbink I believe you had us change this intentionally. What was the reasoning and do we want to change it back as suggested?

**Comment by alisonjoseph** [comment]
Hi @tomwaterton we are currently working on updating all of our component usage and style docs on the website, we haven't gotten to `Link` yet,  if you look at the code demo https://www.carbondesignsystem.com/components/link/code/ you will notice there is an `inline` version of the component that has the underline by default. Usage docs should be updated soon to reflect this, and explain when to use each.

**Comment by mjabbink** [comment]
We changed this intentionally because inline text links must have underline for accessibility. The blue against the text color does not offer the contrast ration needed to differentiate the link from the text. Basically it’s not seen as a link by color alone so an underline is required for inline links

**Comment by tomwaterton** [comment]
Okay, that makes sense, @mjabbink. 

So, it looks like the Carbon Link component guidance needs to be updated to reflect this then. 
(See, for example, the examples shown on the Style tab: https://www.carbondesignsystem.com/components/link/style)
