### ISSUE TITLE
[FeedbackDialogAnimation]: Wiggling enter animation in Safari

### ISSUE THREAD

**Issue by hendriku** [carbon-design-system/gatsby-theme-carbon#812]
## Detailed description

The animation on devices smaller than "md" in Safari wiggles. So the animation reaches its end state, moves back and then reanimates into the end state.

> Describe in detail the issue you’re having.

This looks not good and not intended.

> What did you expect to happen? What happened instead? What would you like to see changed?

No wiggling. As it is in Chrome.

> What browser are you working in?
Safari Version 13.1 (15609.1.20.111.8) 

## Steps to reproduce the issue

1. Tighten your browser window of safari to e.g. 670px width
2. Open a feedback dialog from somewhere
3. See the wiggling animation

## Additional information

- A workaround is to set the `transition-duration: $duration--fast-02;` always. Currently its set to a smaller duration on devices lower than "md" breakpoint.
- Could have made a video but I think it should be obvious.

**Comment by jnm2377** [comment]
I'm gonna close this issue since we have another design issue open with new animation specs for the Feedback Dialog anyway, this will be changing. :) https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1008
