### ISSUE TITLE
Multiple Highlighted Navigation Tabs

### ISSUE THREAD

**Issue by bkribbs15** [carbon-design-system/gatsby-theme-carbon#827]
## Detailed description

Having an issue in chrome where multiple tabs are highlighted at the same time while visiting different pages.  The paths for each of the pages have very different names as well.

Feel free to look at the Github Repo for the site. 
https://github.com/ibm-cloud-architecture/learning-cloudnative-101

or 

https://cloudnative101.dev/

## Additional information

![image](https://user-images.githubusercontent.com/4122319/80519907-54b7af80-894e-11ea-8b2b-b4deac9fee9f.png)

![image](https://user-images.githubusercontent.com/4122319/80519922-5a14fa00-894e-11ea-985a-81e335e2d9de.png)

**Comment by jnm2377** [comment]
@bkribbs15 are you still seeing this issue?

**Comment by bkribbs15** [comment]
@jnm2377 I don't believe so. Should be good to close this issue.

**Comment by dasabhisek** [comment]
What was the fix? I am too getting same issue.
