### ISSUE TITLE
[IDL] Missing poster image in 2x Grid page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#828]
https://www.ibm.com/design/language/2x-grid

Looks like the poster image is missing. Not sure how that happened?

@peter-garvin or @sadekbazaraa Can you see what happened with this animation.

**Comment by peter-garvin** [comment]
@mjabbink I made an issue here: https://github.com/carbon-design-system/design-language-website/issues/530

**Comment by andreancardona** [comment]
This issue has been transferred to the IDL repo: https://github.com/carbon-design-system/design-language-website/issues/530

**Comment by mjabbink** [comment]
@andreancardona this issue still exists. The poster is image is still missing? https://www.ibm.com/design/language/2x-grid/#divisions-of-two
