### ISSUE TITLE
Bug: switcher and search icons

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#83]
if scrolling fast they disappear but hover is still there.  Check screen video.

[Screen Recording 2019-05-20 at 3.34.17 PM.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/3199539/Screen.Recording.2019-05-20.at.3.34.17.PM.zip)

Seems fine in Chrome

**Comment by vpicone** [comment]
@mjabbink I'm not able to reproduce this on the current build, It might have been fixed with a recent update. Can you try again at https://gatsby-theme-carbon.now.sh/?

**Comment by alisonjoseph** [comment]
Not seeing this anymore with latest version, feel free to re-open if we missed something.
