### ISSUE TITLE
How to change the ibm logo on the footer?

### ISSUE THREAD

**Issue by ksurendra** [carbon-design-system/gatsby-theme-carbon#831]
## Summary
How can we change the IBM logo on the footer?

<img width="1107" alt="Screen Shot 2020-04-30 at 5 31 53 PM" src="https://user-images.githubusercontent.com/902972/80765485-c176a980-8b08-11ea-878d-172bf1fe5694.png">

## Relevant information

- Built the project using `npx gatsby new jaqstack-website https://github.com/carbon-design-system/gatsby-starter-carbon-theme` 
- Tried to look in `https://github.com/carbon-design-system/gatsby-starter-carbon-theme/blob/master/src/gatsby-theme-carbon/components/Footer.js` but cannot find any reference
- On inspecting.. 

<img width="1505" alt="Screen Shot 2020-04-30 at 5 39 19 PM" src="https://user-images.githubusercontent.com/902972/80765923-cdaf3680-8b09-11ea-95ad-6db40a8c5d00.png">

**Comment by jnm2377** [comment]
Hi! Great question. Our `Footer` component, by default, renders the IBM logo, but you can render your own logo by using the `logo` prop on it.

**Comment by vpicone** [comment]
The best way about this is to shadow our Footer component, and re-export it using the logo prop @jnm2377 mentioned. Check out our shadowing guide here for more info: https://gatsby-theme-carbon.now.sh/guides/shadowing#shadowing-basics

**Comment by ksurendra** [comment]
Thanks @vpicone @jnm2377 

Here's the solution:

1. Copy logo to `<project>/src/images`
2. Edit Footer.js (<project>/src/gatsby-theme-carbon/components/Footer.js) as

```
...
const FooterLogo = () => (
  <img src="/images/stack-logo-2019.png" alt="" />
);

const CustomFooter = () => <Footer links={links} Content={Content} Logo={FooterLogo} />;
```

**Comment by vpicone** [comment]
@ksurendra nice you got it. Don’t forget that alt tag though!

**Comment by zhengbi-yong** [comment]
Why I couldn't change the logo? once I changed it with my picture, no matter jpg/png/svg, all the format didn't work. Can you help me with that?
