### ISSUE TITLE
Add Andrea's FED talk to getting started docs

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#851]
Whenever it gets published

**Comment by andreancardona** [comment]
@vpicone

Here is an edited version with just the "Spinning up a Carbon Gatsby Theme Site" clip - let me know your thoughts on best next steps: 

Video: https://ibm.box.com/s/3u82h40vlda830ly2wemmg9nd0zyg5al

Keynote: https://ibm.box.com/s/zzhtkq6mkanpo0s1egni3960u0wd8td1
