### ISSUE TITLE
Add documentation for custom Switcher Component Content?

### ISSUE THREAD

**Issue by vzrenggamani** [carbon-design-system/gatsby-theme-carbon#860]
## Summary

Hi, I am new into carbon design system and want to use the gatsby theme carbon for my blog. I have read the documentation quick and doing some modifications. 

Unfortunately, I can't find the documentation how to change the switcher component with my personal content, I have search in this project repos and the switcher content are populated directly from the theme itself. Is any possible ways to fill the switcher content with my own?

**Comment by vpicone** [comment]
Hey @vzrenggamani you'll want to [shadow](https://gatsby-theme-carbon.now.sh/guides/shadowing) the switcher component and provide your own list of links to the switcher component via props. Be sure to spread  the other props into the component as well.

**Comment by vpicone** [comment]
This would make for a good addition to the shadowing guide

**Comment by vzrenggamani** [comment]
I am very new into gatsby :smile:. Would like to wait the proper documentation for this components and I'll try my best to do with my own.
Thank you very much

**Comment by sstrubberg** [comment]
@vzrenggamani were you able to figure out how to shadow the AppSwitcher?

**Comment by vzrenggamani** [comment]
> @vzrenggamani were you able to figure out how to shadow the AppSwitcher?

Nothing comes to my mind about shadowing the AppSwitcher. I am no idea how to use gatsby and shadowing stuff.

**Comment by vzrenggamani** [comment]
Just got some error and IDK for the fixes...
I have followed the preshadowed templates and trying to edit the switcher, but it looks wrong..

![image](https://user-images.githubusercontent.com/14950309/88679737-f0a5b280-d119-11ea-8ec8-267eb16b3b95.png)

```js
import React from 'react';
import Switcher from 'gatsby-theme-carbon/src/components/Switcher';
import SwitcherLink from 'gatsby-theme-carbon/src/components/Switcher';
import SwitcherDivider from 'gatsby-theme-carbon/src/components/Switcher';

const CustomSwitcher = (props) => (
  <Switcher {...props}>
    <SwitcherLink {...props}  href="https://somelinks.id">
      Japan Festival
    </SwitcherLink>
    <SwitcherLink {...props} href="https://somelinks.id">
      Japan Festival Media
    </SwitcherLink>
    <SwitcherLink {...props} href="https://somelinks.id">
      Japan Festival Platfrom
    </SwitcherLink>
    <SwitcherDivider>Technology Stack</SwitcherDivider>
  </Switcher>
);

export default CustomSwitcher;
```

**Comment by vpicone** [comment]
@vzrenggamani thats pretty close you need to change your imports a bit. `Switcher` is the default export so it's fine, but the other two imports are _named_ imports so you need to use brackets to pull them out of the Switcher file:

```
import Switcher from 'gatsby-theme-carbon/src/components/Switcher'; // default export, no brackets needed
import { SwitcherLink } from 'gatsby-theme-carbon/src/components/Switcher'; // add brackets
import { SwitcherDivider } from 'gatsby-theme-carbon/src/components/Switcher'; // add brackets
```

In addition, you only need to pass props through to the `Switcher` component so you can remove `{...props}` from the links.

Let me know if you have any questions!

**Comment by vzrenggamani** [comment]
Ahh, work like a charm.. Thank you.

**Comment by vpicone** [comment]
No prob! Going to close this one out since it's pretty straight forward so long as you use the correct imports.
