### ISSUE TITLE
Multi-Top Level Selections with new Update.

### ISSUE THREAD

**Issue by bkribbs15** [carbon-design-system/gatsby-theme-carbon#863]
## Detailed description

With the new 1.24.3 update that fixed the multiple selected tabs on the left nav bar, now their is two issues with the top level tabs.  

The first is multiple are selected when they are closed manually and only one section is being viewed.

The second is when one section is selected the left side navigation dropdown opens another section along with the selected one. 

## Additional information

I have a video attached showing the bugs I found.  Let me know if there is a current way to fix this.  

If you would like to the visit the site and try it yourself the link is: https://cloudnative101.dev/

[gatsby-bug.mov.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/4714815/gatsby-bug.mov.zip)

**Comment by vpicone** [comment]
@bkribbs15 can you share your navigation yaml? It looks like your URLs are the top-level path segment that's used to differentiate between similar pages. And have an extra bit on the end for some reason.

For example I would expect `https://cloudnative101.dev/cloud-native-overview/read/` to be `https://cloudnative101.dev/concepts/cloud-native-overview/

The reason you're getting both menus opening is the first link in each menu starts with `https://cloudnative101.dev/cloud-native-overview`, so the theme thinks one is a tab item of another.

**Comment by vpicone** [comment]
Your `pages` directory structure should map to the urls generated, and match pretty closely the navigation yaml. The reason we need the yaml at all is so folks can exclude pages or determine the order of links in the sidebar, but there's some expectation of mapping the yaml structure to directory structure. The theme's `example` project is a good example of how to set it up.

**Comment by bkribbs15** [comment]
@vpicone Here is the link to my navigation yaml https://github.com/ibm-cloud-architecture/learning-cloudnative-101/blob/master/src/data/nav-items.yaml.

I'm pretty sure I understand what you mean. For the most part the links and directory structure should be the same as the page linkage. In both the `concepts` and `lecture` sections of our site we have the same topics. One is for a basic read to understand and the other contains resources and is there for when the concept is presented to live audience.

**Comment by bkribbs15** [comment]
We set them up in our repo under the topic name vs the section name. IE There is a Cloud Native section with a `read.mdx` for the `concepts` section and the `index.mdx` for the `lecture` section

**Comment by bkribbs15** [comment]
gotcha, okay makes sense. Thanks for the help.
