### ISSUE TITLE
[IDL Animation] Gif/video player functionality

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#872]
@sadekbazaraa commented on [Tue Jun 02 2020](https://github.com/carbon-design-system/design-language-website/issues/559)

PR: https://github.com/carbon-design-system/design-language-website/pull/548

@vpicone @sstrubberg I'm using a combination of animated Gifs and Mp4s within the Do/don't component where animated examples are needed. The intended behavior is for these examples to autoplay. It's necessary that the videos play and loop side by side in order for them to be effective.
https://design-language-website-git-add-animation-v3.carbon-design-system.now.sh/animation/classic-principles/

**Autoplay**
For whatever reason the videos do not autoplay. Is there a property that can be included to invoke the autoplay feature? Incidentally, the pause/play icons are inverted.

**Lottie**
For many of the videos, we've been able to get lottie files. How do we implement lottie files?

The examples portion of this page is working as intended where the smaller and shorter files are automatically looping and the longer form videos have the blue play button. https://design-language-website-git-add-animation-v3.carbon-design-system.now.sh/animation/tips-and-techniques/#examples

Similar to the Classic Principles page, the do/don't examples should autoplay here as well.

**Lazy load**
Does it make sense to load this content as you scroll similar to https://www.ibm.com/design/

These issues are fairly high priority to resolve so we can get these pages live sooner than later.

FYI @mjabbink

**Comment by vpicone** [comment]
autoplay stuff is being covered here: https://github.com/carbon-design-system/design-language-website/issues/615

Other things are resolved, we've discussed the lazy loading thing before it can get really busy animation-wise. We can implement it in an individual site to try, but I don't think it's as high priority as the other issues you mentioned here.
