### ISSUE TITLE
 Icons in the FeatureCard have became blue

### ISSUE THREAD

**Issue by xylish7** [carbon-design-system/gatsby-theme-carbon#883]
## Detailed description

> Describe in detail the issue you’re having.

Upgrading to the last version of carbon (1.24.4) the icon of the FeatureCard became blue.

> What did you expect to happen? What happened instead? What would you like to see changed?
- Expected look:

![image](https://user-images.githubusercontent.com/24867712/85296288-d557df80-b4a9-11ea-81b5-3dfac35c4419.png)

- Current look: 

![image](https://user-images.githubusercontent.com/24867712/85297095-01c02b80-b4ab-11ea-80fb-304d2948b038.png)

> What browser are you working in?

- Firefox
- Google Chrome

## Steps to reproduce the issue

1. Run `npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme`
2. Change this packages to this versions in `package.json`:
    - "gatsby": "^2.23.8",
    - "gatsby-theme-carbon": "^1.24.4",
    - "react": "^16.13.1",
    - "react-dom": "^16.13.1"
3. Run `yarn`
4. Run `yarn dev` -> the icon become blue in FeatureCard on light type

**Comment by sstrubberg** [comment]
Works just fine for me.

1. I ran `npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme`
2. I then ran `yarn add gatsby gatsby-theme-carbon react react-dom` to upgrade all the packages.
3. Ran `yarn dev`. Rock n' roll!

![image](https://user-images.githubusercontent.com/15822070/85461336-dea88100-b569-11ea-9152-4d999c38649b.png)

**Comment by xylish7** [comment]
@sstrubberg yes, but this is a dark card, not a light one. Try with a light one
