### ISSUE TITLE
Feedback button: Make them the same gray color.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#886]
currently the feedback button is different color than the jump to top of page button. They should be the same.

![85312628-11c51480-b485-11ea-9dde-ecf79de70ca6.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/2400432e-1900-4f1d-b3e8-cc27090a1ee9)

—

![85312659-21445d80-b485-11ea-88f7-36a439a86f03.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/25e7a2d0-1524-4137-80a6-407074cf28bf)

**Comment by mjabbink** [comment]
@jeanservaas Looks like your final decision is the lighter gray. Confirm please and Vince will change.

**Comment by mjabbink** [comment]
👍

**Comment by vpicone** [comment]
@jnm2377 Do you mind making a new PR with just the fix for this while they work out a new issue with a proper motion spec?

**Comment by vpicone** [comment]
@jnm2377 Here's [the final spec for the color changes](https://github.com/carbon-design-system/gatsby-theme-carbon/pull/977#issuecomment-693476525) from @jeanservaas comment in the original PR.

Enabled state should look like this:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/43144260/93357504-5f47e800-f80e-11ea-9999-5a4b3d14a4a9.png">


Both hover and selected state should look like this:

<img width="116" alt="image" src="https://user-images.githubusercontent.com/43144260/93357254-1859f280-f80e-11ea-9ac8-af0a7dc9ae96.png">
