### ISSUE TITLE
LeftNavItemProvider is no longer available???

### ISSUE THREAD

**Issue by chainergar** [carbon-design-system/gatsby-theme-carbon#897]
## Detailed description

> I am shadowing LeftNav and used LeftNavItemProvider for this
Suddenly, I got this build error when I run gatsby build command.

```
ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve 'gatsby-theme-carbon/src/components/LeftNav/LeftNavItemProvider' in '/Volumes/Dev/Project/REACT/FreightTrust/homepage-update/src/gatsby-theme-carbon/components/LeftNav'

If you're trying to use a package make sure that 'gatsby-theme-carbon/src/components/LeftNav/LeftNavItemProvider' is installed. If you're trying to use a local file make sure that the path is correct.

File: src/gatsby-theme-carbon/components/LeftNav/LeftNavItemProvider.js
```

I have checked the node_moduels and it seems like the carbon theme has removed the LeftNavItemProvider from its packages for new releases.
But the readme still says it's available

https://gatsby-theme-carbon.now.sh/guides/navigation/sidebar/#customizing

What did I miss here?
And how can I fix this build error?

This is going to be very serious, I am struggling with this build issue for several days and the production is getting wrong.
Please check and fix this as soon as possible.

Thanks

**Comment by vpicone** [comment]
@chainergar that file was renamed so it could be used with the header nav. You can shadow the file here: https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/gatsby-theme-carbon/src/util/NavItems.js

I'll update the docs to reflect that change, sorry for the confusion! In the future, if something is "very serious" and production is getting it wrong, you can always revert the theme to a version that works! In this case, that would be just a couple releases ago.
