### ISSUE TITLE
Example for overriding NavItems.js in sidebar documentation causes an infinite loop

### ISSUE THREAD

**Issue by rafael-nogueras** [carbon-design-system/gatsby-theme-carbon#908]
## Detailed description

> Describe in detail the issue you’re having.

In the sidebar documentation (https://gatsby-theme-carbon.now.sh/guides/navigation/sidebar), the following example is shown for overriding `NavItems.js`:
```
// /src/util/NavItems.js
import { useNavItems as themeUseNavItems } from 'gatsby-theme-carbon/src/util/NavItems.js';

// add nav items
export function useNavItems() {
  const navItems = themeUseNavItems();
  return navItems.concat({
    title: 'Additional Nav Item',
    pages: [
      { path: '/page1', title: 'New Page 1' },
      { path: '/page2', title: 'New Page 2' },
    ],
  });
}
```

However, that causes an infinite loop, because the line `import { useNavItems as themeUseNavItems } from 'gatsby-theme-carbon/src/util/NavItems.js';` actually imports the current file (i.e. the overriding module itself), so calling `const navItems = themeUseNavItems();` recurses infinitely.

## Steps to reproduce the issue

1. Create a file called `src/gatsby-theme-carbon/util/NavItems.js` in a project that uses the Gatsby theme with the contents listed above.
2. Run the `yarn dev:clean`.
3. Load any page that uses the side nav: it will hang for a while and eventually show an error due to too many recursions.

## Additional information

The solution is simple: replace:
```
import { useNavItems as themeUseNavItems } from 'gatsby-theme-carbon/src/util/NavItems.js';
```
in the sample code with:
```
import { useNavItems as themeUseNavItems } from 'gatsby-theme-carbon/src/util/NavItems';
```

I am not sure why removing the `.js` correctly loads the module from `node_modules` instead of the overriding module, but it does!

**Comment by vpicone** [comment]
Shadowing is so weird haha, do you mind opening a PR to update the docs? Great find and thank you!!

**Comment by rafael-nogueras** [comment]
@vpicone Yup, I already started the process, but it was already the end of the work day when I opened the issue, so I'll handle that on Monday. :-)
