### ISSUE TITLE
Spacing issues in the theme.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#911]
Horizontal spacing between Feature cards should be minimum of 32px and we also use 64px

![Screen Shot 2020-07-13 at 5.16.54 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/cd243737-6c3b-41e3-bbb1-c7b6d9b22db6)

FOr Artical cards the horzontal spacing shoulf be 16px:

![Screen Shot 2020-07-13 at 5.19.26 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/0b3a0bac-5442-4bce-a9e9-304e614f8f96)

**Comment by mjabbink** [comment]
causing the issues in #613

**Comment by mjabbink** [comment]
@sadekbazaraa

**Comment by sadekbazaraa** [comment]
@mjabbink in general, we always have 32px between elements vertically. The cards above have 16px space on the right side only so we can keep the type on the columns, otherwise we'd use the cards that butt up against each other. Either way, I think we should always maintain our consistent 32px minimum spacing between items vertically whether we're using touching cards or cards that have the 16px to the right. This is the way it's always been in our original sketch files.

![Screen Shot 2020-07-14 at 10 55 46 AM](https://user-images.githubusercontent.com/33162280/87441050-a6242200-c5c0-11ea-85d2-85bf3898865c.png)

**Comment by sadekbazaraa** [comment]
@mjabbink also worth noting, in the screenshot above is that the spacing is globally applied to the top of these cards which is what also gives you the 32px space between the intro paragraph and the first set of cards. If we go adjusting these cards to only have 16px on top now, we'll start breaking other things in the process.

**Comment by mjabbink** [comment]
I thought so but the current situation is not 32px or 16px in many places. BC and even Gatsby demo site has some other pixel amounts there. 

https://gatsby-theme-carbon.now.sh/components/ArticleCard/#example

https://gatsby-theme-carbon.now.sh/components/FeatureCard

BC:

https://www.ibm.com/brand/systems/#additional-systems

this seems wrong too. Seems like the horizontal spacing should be 16px here too.
https://www.ibm.com/brand/expression

**Comment by mjabbink** [comment]
Seems like the good of cards should not be turned into rows but I’m not wed to this. If this is how it’s been then we can leave the 32px between the 16px.

**Comment by sadekbazaraa** [comment]
@mjabbink I think something happened with spacing in multiple places with the last Gatsby update which was recent. I can see all the subtle errors in the links you posted above. Not sure what happened along the way?

The Systems page on Brand Center should be the way we've outlined it here: https://github.ibm.com/brand/events/issues/37

**Comment by mjabbink** [comment]
@sadekbazaraa I reckon I’m OK with 32 with article cards. I just gotta get my head around the different spacing between horizontal and vertical. @sstrubberg

**Comment by vpicone** [comment]
@sadekbazaraa since the spacing overhaul last year, our default vertical space has been 24px. We created an exception for the `DoDont` for example so that the vertical and horizontal were both 32px.
