### ISSUE TITLE
Document how to suppress target=_blank for internal links in ArticleCard and ImageCard href

### ISSUE THREAD

**Issue by mzuliani-ibm** [carbon-design-system/gatsby-theme-carbon#916]
## Summary
I had to read [the source code](https://github.com/carbon-design-system/gatsby-theme-carbon/blob/8296c8d16693e3c8f690bfd64c6421daff255a4f/packages/gatsby-theme-carbon/src/components/ImageCard/ImageCard.js) to figure out why my hrefs in image and resource cards to pages on my same site were opening in new browser tabs.

Please update the documentation on one or more of these pages to make it clear:
https://gatsby-theme-carbon.now.sh/components/ArticleCard
https://gatsby-theme-carbon.now.sh/components/ImageCard

## Relevant information
Turns out, these components parse based on a leading `/`, even through the relative URL works regardless of the slash.

- No slash = open in new browser tab and window via `target="_blank"`
- Leading slash = open in current browser tab

Example of JS code that decides whether or not to add target = blank...

```
    let isLink;
    if (href !== undefined && !rest.download) {
      isLink = href.charAt(0) === '/';
    }
```
```

    if (disabled === true || href === undefined) {
      cardContainer = <div className={carbonTileclassNames}>{cardContent}</div>;
    } else if (isLink === true) {
      cardContainer = (
        <Link to={href} className={carbonTileclassNames}>
          {cardContent}
        </Link>
      );
    } else {
      cardContainer = (
        <a
          target="_blank"
          rel="noopener noreferrer"
          href={href}
          className={carbonTileclassNames}>
          {cardContent}
        </a>
      );
    }
```

My code, version A, that opened in new tab unexpectedly:
```
<ImageCard
    title="UI shell header"
    titleColor="dark"
    href="components/UI-shell-header#design-details">

![Headers](images/headersThumbnail.png)

  </ImageCard>
```

My code, version B, that opened in the same tab:
```
<ImageCard
    title="UI shell header"
    titleColor="dark"
    href="/components/UI-shell-header#design-details">

![Headers](images/headersThumbnail.png)

  </ImageCard>
```

**Comment by vpicone** [comment]
These were removed in a recent update

**Comment by mzuliani-ibm** [comment]
What was removed, these types of cards or the URL parsing?

**Comment by vpicone** [comment]
@mzuliani-ibm the new tab behavior from those components
