### ISSUE TITLE
[plex] font-weights missing, only 400 and 600 available

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/gatsby-theme-carbon#927]
## Detailed description

We only have two font weights available on our site that we generated from the starter a few months ago. We don't have any font weight overrides in place in our styles.

- [ ] 300 font weight is not included by default - it appears we only have 400 and 600.
- [ ] symptom of the above issue is that the page headers on our site are not the proper weight ([Internal issue here](https://github.ibm.com/ai-applications/design/issues/149))
- [ ] `additionalFontWeights` config doesn't include the specified weights either
  - we have `additionalFontWeights: ['200', '200i'],` defined, but as you can see in the gif below demonstrating all these issues, we only have the two weights.

![Jul-20-2020 09-41-52](https://user-images.githubusercontent.com/3360588/87950968-9e0b2d00-ca6d-11ea-9a60-43458214c5ed.gif)

We're on v1.24.3, but I don't think an upgrade will fix. I didn't see any updates that have been made since then up until current.

**Comment by sstrubberg** [comment]
Here's [the fix](https://github.ibm.com/Design/w3-design/blob/master/gatsby-ssr.js) i did on w3/design.

**Comment by vpicone** [comment]
The Gatsby sites all use the plex variable font so they should have access  to all the Plex weights from 200-900. You’ll need to hit google fonts for Mono weights (like Scott did), but for regular IBM Plex Sans, you shouldn’t need to to that.

The `additionalFontWeights` config option is non functional since all the font weights are included now for IBM Plex Sans. Do you have a link where this is happening? I recommend opening in FireFox and using the font tools to dig in.

**Comment by tay1orjones** [comment]
@vpicone I do see the variable font files being loaded in the network tab, but Firefox font tools show two `font-face` declarations pointing to different font files in `static`. 

![image](https://user-images.githubusercontent.com/3360588/88076595-e266fd80-cb3f-11ea-89d0-133fcea8119a.png)

We [don't have `font-face` declarations in the source](https://github.ibm.com/ai-applications/design/search?q=font-face&unscoped_q=font-face), and [we don't have any .woff font files in the repo](https://github.ibm.com/search?utf8=%E2%9C%93&q=.woff+repo%3Aai-applications%2Fdesign+extension%3A.woff&type=Code&ref=advsearch&l=&l=).

Site: https://pages.github.ibm.com/ai-applications/design/team/welcome-to-design/welcome/
Source: https://github.ibm.com/ai-applications/design/

**Comment by vpicone** [comment]
@tay1orjones could you shadow the file under `gatsby-theme-carbon/src/styles/internal/_global.scss` and comment out line 24: 

```scss
// Typography
@include carbon--type-reset(); // comment this out
```
