### ISSUE TITLE
List acting up in Firefox. Numbering continues rather than starting from 1 on second list

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#949]
See here in Firefox:

https://www.ibm.com/design/language/iconography/pictograms/contribute

https://www.carbondesignsystem.com/guidelines/pictograms/contribute

Correct in Chrome and Safari.

**Comment by laurenmrice** [comment]
Re-opening because this still seems to be happening in Firefox. I cleared my cache, but still see this:
<img width="1237" alt="Screen Shot 2020-11-19 at 8 59 27 AM" src="https://user-images.githubusercontent.com/43969356/99683102-97a1b780-2a45-11eb-969d-1056173858e3.png">

**Comment by jnm2377** [comment]
This issue is fixed. The website is not up to date.

**Comment by jnm2377** [comment]
this fix was in `1.27.1`, and the website is on `1.27.0` @laurenmrice
