### ISSUE TITLE
fix[vertical spacing]: margin tops are all squashed on Carbon site

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#958]
There should be:

- 80px of spacing above H2s
- 48px of spacing above H3s
- 32px of spacing above H4s

![image](https://user-images.githubusercontent.com/43144260/89331574-a19ad880-d657-11ea-8da0-f1e35d8608a1.png)

**Comment by vpicone** [comment]
Fixed
