### ISSUE TITLE
Problem with a tab name that has an apostrophe in it

### ISSUE THREAD

**Issue by scanlana** [carbon-design-system/gatsby-theme-carbon#960]
## Detailed description

> Describe in detail the issue you’re having.
tabs:
  [
    'Overview',
    'Welcome page',
    'Whats new',
  ]
Results in an error on the page and the tab list getting displayed as plain text

Using the HTML code for ' instead of the character results in the tab name being displayed as What&#39; New

> What did you expect to happen? What happened instead? What would you like to see changed?
I would like to be able to use an apostrophe in the tab name.

> What browser are you working in?
Firefox

## Steps to reproduce the issue

1. Create a page that has a tab that as an apostrophe in the name.

## Additional information

- Screenshots or code
- Notes

**Comment by tay1orjones** [comment]
Have you tried escaping the quote with a slash `\`?

```
---
tabs: ['What\'s new', 'Overview']
---
```

**Comment by scanlana** [comment]
I hadn't tried that. I did:
`---
title: Overview
tabs:
  ['Overview', 'Welcome page', 'What\'s new', 'Getting started', 'Administration', 'Troubleshooting', 'Customization', 'Navigation', 'APIs']
---`
And this was the result:
![image](https://user-images.githubusercontent.com/19390362/89758487-d5568200-dadf-11ea-80c2-d522ea40ab74.png)
