### ISSUE TITLE
fix(ArticleCard): font-size breaks down at the smallest point on lg screens

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/gatsby-theme-carbon#962]
Found this over at the carbon website.

What's the Theme's stance on this? Are we telling people to use less characters on the article card **or** should we be using a different type token for large screens so we can accommodate more type.

![image](https://user-images.githubusercontent.com/15822070/89650968-cfb32f00-d888-11ea-8c9d-08bd6a57f893.png)

**Comment by jeanservaas** [comment]
I made an issue for this too @sstrubberg 

The token for the article card type is wrong. It should be $body-short-02 which will solve this problem. Mike wants this listed as high priority as it's been broken for a while.

https://github.com/carbon-design-system/gatsby-theme-carbon/issues/973
