### ISSUE TITLE
Ordered lists don't start at "1" in Firefox

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#963]
Ordered lists don't appear to be starting at the number 1
https://gatsby-theme-carbon.now.sh/components/markdown#lists

![Screen Shot 2020-08-10 at 10 05 38 AM](https://user-images.githubusercontent.com/2753488/89797838-0be8c880-daf1-11ea-9978-f462e60d7e21.png)

this is also happening on the Carbon website
https://www.carbondesignsystem.com/components/breadcrumb/usage

![Screen Shot 2020-08-10 at 10 05 59 AM](https://user-images.githubusercontent.com/2753488/89797878-199e4e00-daf1-11ea-80b6-f6c14ffa9c01.png)

**Comment by alisonjoseph** [comment]
possibly related to this https://bugzilla.mozilla.org/show_bug.cgi?id=1545746

**Comment by jnm2377** [comment]
related #949, closing this issue for that one.
