### ISSUE TITLE
Incorrect active styling in sidenav

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/gatsby-theme-carbon#969]
## Detailed description

> Describe in detail the issue you’re having.

I've noticed this on the Carbon website, which is possibly a bug in `carbon-gatsby-theme`.

![image](https://user-images.githubusercontent.com/14989804/90261789-749ab280-de1b-11ea-99c9-2743f386ce15.png)

when you click on a nav item, as you're redirected to the correct page, the nav item goes darker.

now when you **refresh** on the same page, you get this incorrect lighter styling:
![image](https://user-images.githubusercontent.com/14989804/90261877-909e5400-de1b-11ea-98f8-f55cf58f2783.png)

> What did you expect to happen? What happened instead? What would you like to see changed?

Same darker font color on the active nav item

> What browser are you working in?
Chrome

## Steps to reproduce the issue
1. Click on `Resources` in https://www.carbondesignsystem.com
2. Refresh page

**Comment by urmauur** [comment]
Hi @theiliad I try to reproduce the issue, but I can't find the `Resources` menu. am I missing something?

<img width="982" alt="Screen Shot 2020-10-05 at 09 53 13" src="https://user-images.githubusercontent.com/10354610/95036043-e80cc200-06f0-11eb-9028-5096ba2c43b4.png">

**Comment by theiliad** [comment]
> Hi @theiliad I try to reproduce the issue, but I can't find the `Resources` menu. am I missing something?
> 
> <img alt="Screen Shot 2020-10-05 at 09 53 13" width="982" src="https://user-images.githubusercontent.com/10354610/95036043-e80cc200-06f0-11eb-9028-5096ba2c43b4.png">

Hi, thanks for participating in Hacktoberfest 👋 

Seems like either someone's fixed this or it's no longer an issue, I can't reproduce
