### ISSUE TITLE
Create ImageCard component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#98]

**Comment by SilverFox70** [comment]
![Screen Shot 2019-05-23 at 10 37 24 AM](https://user-images.githubusercontent.com/10566194/58274477-d1f2a180-7d47-11e9-8f56-2bb3daca6867.png)

**Comment by alisonjoseph** [comment]
@SilverFox70 Do you know the font sizes/type tokens for the text inside the cards?

**Comment by SilverFox70** [comment]
Title: IBMPlexSans Size 20px line height 26px
text in bottom-left: size 14px
