### ISSUE TITLE
I created my own component through Gatsby theme repo, now what?

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/gatsby-theme-carbon#981]
@helmutgranda commented on [Mon Aug 31 2020](https://github.com/carbon-design-system/carbon/issues/6750)

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

Using Gatsby Theme is great but need to figure out the workflow when it comes to incorporating custom components. 

## Relevant information

I am creating our own UI version of our components using https://github.com/carbon-design-system/gatsby-theme-carbon and I have created a couple of components to test the workflow, pretty straight forward. Now, I want to have those components as part of the mininfied CSS and JS since we are going vanilla and that is where I got stuck since gatsby-theme-carbon does not provide the tools to do so, does that mean that I have to somehow incorporate this work with gatsby-theme-carbon?

**Comment by jnm2377** [comment]
Hi @helmutgranda, I'm not sure I'm following the issue you're running into. Here's what I understand:
- you created a documentation site using our gatsby theme carbon
- you then created some custom components in your repo

 and now, are you running into issues on how to implement then?

**Comment by vpicone** [comment]
Gonna close this out for now, you can import and use custom components in gatsby theme sites wherever you want! They can be imported into mdx pages or regular js pages. See the carbon website for an example.

**Comment by helmutgranda** [comment]
Thanks for the comments, I had switched to a different project but back to this.

I think initially the impression was that this theme would also give us the ability to create core carbon components but that is not the case. We of course can create carbon-theme components but if we want to create carbon components we need to create a different project and do our work there.

I was hopping to have a unified system that would allow us to create the UI and also the core library along with the UI only component library.

Does that answer your question @jnm2377?
