### ISSUE TITLE
Switcher —> Update Content with labels

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#984]
Need to update switcher—  “Digital” under Design disciplines should link to http://ibm-dotcom-library.mybluemix.net/

FYI @wonilsuhibm

**Comment by mjabbink** [comment]
@sadekbazaraa @kennethhartmann We need to do the same for Brand Center and flow down to XG sites.

**Comment by kennethhartmann** [comment]
> @sadekbazaraa @kennethhartmann We need to do the same for Brand Center and flow down to XG sites.



> Need to update switcher— “Digital” under Design disciplines should link to http://ibm-dotcom-library.mybluemix.net/
> 
> FYI @wonilsuhibm

Hi @mjabbink what happens to the current "Digital" URL: https://www.ibm.com/standards/web/ ?
Do we need to point to it–IBM Web Standards–from any other location w/i BC and our XGs or is are we no longer cross-linking to that site?

**Comment by jeffchew** [comment]
@mjabbink this change was already contributed by me 11 days ago and merged in, but I don't think there has been a Gatsby release since before that: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/974

cc: @wonilsuhibm @vpicone

**Comment by jeffchew** [comment]
@kennethhartmann in my PR, I added `IBM Web Standards` as its own entry, as that is a tier 1 level site that points to things beyond design (SEO, content authoring, accessibility, etc) for all teams that need to build an application under IBM.com.

**Comment by kennethhartmann** [comment]
> @kennethhartmann in my PR, I added `IBM Web Standards` as its own entry, as that is a tier 1 level site that points to things beyond design (SEO, content authoring, accessibility, etc) for all teams that need to build an application under IBM.com.

Hi @jeffchew, so is`IBM Web Standards` now above _Design Disciplines_ and below IBM Accessibility?

**Comment by jeffchew** [comment]
> > @kennethhartmann in my PR, I added `IBM Web Standards` as its own entry, as that is a tier 1 level site that points to things beyond design (SEO, content authoring, accessibility, etc) for all teams that need to build an application under IBM.com.
> 
> Hi @jeffchew, so is`IBM Web Standards` now above _Design Disciplines_ and below IBM Accessibility?

Yes, that's correct.

**Comment by sadekbazaraa** [comment]
FYI @KSandeep5 — let's make sure this gets tracked across all of our sites as it's related to the global nav switcher.

**Comment by mjabbink** [comment]
I’m confused now.

@kennethhartmann the web standards are in the left nav in the dot com library site. The switcher should aim to the library.

**Comment by kennethhartmann** [comment]
> @kennethhartmann and @jeffchew The web.standards should not be in the switcher

Okay, that makes sense. Thanks for confirming @mjabbink!

**Comment by vpicone** [comment]
Hey everyone, sorry for the delay. We wanted to get a few more PRs in before a theme release. Should be good to go tomorrow.

**Comment by janchild** [comment]
@jeanservaas and @jillianhowarth 

I spoke with @mjabbink last night and there are a couple of tweaks for the attached image. I sent a message in Slack but will reiterate here for others to see.

- Include a padlock for Brand Center, to be clear that a login is required. 
- Include a padlock for IBM Design (and it will go to the w3 site instead of the externally facing site—more useful).
- We’ll definitely go with Foundations, plural.
- Implementation is the heading to validate in testing also.

![image](https://user-images.githubusercontent.com/44503588/94562973-a7620400-022b-11eb-87c7-65892c8b892b.png)

Thank you!

**Comment by jeanservaas** [comment]
## Finalized App Switcher Content Updates

**Step 1 (Breadcrumb)** 
For immediate update (no name change to Carbon Design System or IBM.com Library)

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/43144260/94577870-0bdd8d00-0245-11eb-8746-3d9392026ec9.png">


Note:

- [ ] Please change margin top of labels from 40px (current) to 32px 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/43144260/94578642-fa48b500-0245-11eb-8b38-2203f9b7b697.png">



## Sketch file

[app_switcher_prototype.zip](https://github.com/carbon-design-system/gatsby-theme-carbon/files/5300089/app_switcher_prototype.zip)

**Comment by vpicone** [comment]
@sstrubberg @mjabbink @jeanservaas how close are we on defining this? Did the philback change things?

**Comment by mjabbink** [comment]
I think we can implement now but Jeannie has a new order for those items

Foundations
Implementation
Community
Practices

**Comment by jillianhowarth** [comment]
Here's the findings from the research I've been doing on the update concept for the app switcher. 

https://www.notion.so/carbondesignsystem/App-switcher-testing-notes-e9b84b80fc604cc78983f9755e3288db

**Comment by mjabbink** [comment]
I found our from Wonil they are already moving to change `IBM.com Library` to `Carbon for IBM.com`Next week so we should hold on this until they’ve made their updates.

**Comment by mjabbink** [comment]
@jeanservaas Wonil and team have already switched the name to `Carbon for IBM.com` I’m not asking them when the might change the url to `www.carbondesignsystem.com/for-ibm-dotcom` or `www.carbondesignsystem.com/ibm-dotcom`

**Comment by mjabbink** [comment]
Just waiting to get the right url

<img width="733" alt="Screen Shot 2020-10-12 at 9 30 36 AM" src="https://user-images.githubusercontent.com/32881239/95786764-da7dac00-0c9d-11eb-95b1-4a7c05c23e1a.png">

**Comment by mjabbink** [comment]
Link: https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/

**Comment by jeanservaas** [comment]
@mjabbink @jnm2377 @janchild 

Is this the final then? 

And the Carbon for IBM.com link is:
https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/

<img width="339" alt="image" src="https://user-images.githubusercontent.com/43144260/96132485-7559ce80-0ec8-11eb-9331-703ccfac8de2.png">

**Comment by mjabbink** [comment]
NO!!!!! Not Carbon for Product. 

Carbon Design System

**Comment by mjabbink** [comment]
We are calling things what they are. I’m unaware of our site being called Carbon for product. I would also argue against it.

**Comment by jeanservaas** [comment]
@mjabbink @janchild 
We need to write this stuff out in issues for clarity. It's been shown multiple times and validation tested with "Carbon for Product"

I'm in the process of updating it but there's no way I could've known that unless someone updates it here. All I'm doing is updating the visual spec for Josefina.
