### ISSUE TITLE
List should not be hanging into gutter

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/gatsby-theme-carbon#985]
via @mjabbink 

- [x]  ordered list numbers should left align with body copy. Not hang into gutter

![IMG_5749.jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fb0e8a48-2560-4dc7-ae15-55171dded639)

**Comment by mjabbink** [comment]
@jeanservaas

**Comment by jnm2377** [comment]
@mjabbink where are you still seeing this? All the lists I'm seeing are aligned with the body copy. 

<img width="927" alt="Screen Shot 2020-09-09 at 11 47 48 AM" src="https://user-images.githubusercontent.com/32556167/92640575-1b4f6300-f2a3-11ea-927e-7a125c6b8f6a.png">

**Comment by mjabbink** [comment]
check mobile. I think that is where it was moving into the left margin

**Comment by jnm2377** [comment]
@mjabbink I don't see it happening on mobile either. It all aligns. ![Screen Shot 2020-09-10 at 11.04.41 AM.png](https://images.zenhubusercontent.com/5be9d7ed0cefa317ea423a50/95a1cbaf-aee4-4c6c-a7a4-0a33f74aec07)

**Comment by mjabbink** [comment]
Hmmm. I see it in Safari and Chrome on my iPhone. Have you checked on your device? Not sure why I’m seeing this.

**Comment by mjabbink** [comment]
screen grab from my phone

<img width="143" alt="Screen Shot 2020-09-10 at 1 15 58 PM" src="https://user-images.githubusercontent.com/32881239/92779616-d3464400-f367-11ea-83a7-1f07295a4d20.png">

**Comment by jnm2377** [comment]
Ahh, it's only happening in Safari. Gotcha.

**Comment by mjabbink** [comment]
It does the same thing for me in Chrome mobile.

**Comment by jnm2377** [comment]
That's bc mobile chrome is Safari under the hood, but if you're looking at it in chrome on your computer, it's not an issue.

**Comment by mjabbink** [comment]
yes, looks good in Chrome on desktop. I only see the issue in Safari desktop and Mobile.
