### ISSUE TITLE
fix[component]: gatsby code snippet showing wrong color theme

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#986]
Not sure how this happened, but the Gatsby code snippet is showing orange type. @tw15egan working on a color theme for the Gatsby snippets a long time ago and it's been the same for a while, it there were teals, purples, blues and magentas but no orange. It was so long ago that I don't have specs for it, it was something we worked through together and PR'd.

**Wrong:**

![image](https://user-images.githubusercontent.com/43144260/92518722-c9e19e00-f1e6-11ea-9eb7-324e616ad7f8.png)

You can see remnants of the old code snippet color theme on other pages. I'm wondering what the best way is for us to revert back to this. 

These are the original theme colors:

![image](https://user-images.githubusercontent.com/43144260/92520195-39f12380-f1e9-11ea-8f64-ed7d5a6a23b6.png)

**IDL:**
![image](https://user-images.githubusercontent.com/43144260/92519311-baaf2000-f1e7-11ea-9856-3fa30aebc569.png)

**Carbon:**
![image](https://user-images.githubusercontent.com/43144260/92519252-a10dd880-f1e7-11ea-987c-0ea3ada8d331.png)

**Comment by jeanservaas** [comment]
@vince replace orange with the blue.

**Comment by vince** [comment]
> @vince replace orange with the blue.

Wrong Vince

**Comment by jnm2377** [comment]
Being addressed in @sstrubberg theming PR https://github.com/carbon-design-system/gatsby-theme-carbon/pull/979

**Comment by mjabbink** [comment]
@sstrubberg Hows this going?

**Comment by mjabbink** [comment]
@sstrubberg See above from 7 days ago. Created Sep 8. Not sure why this has taken several months.

**Comment by mjabbink** [comment]
@jeanservaas Since Scott is is not responding to me I’ll check with you if this is resolved?

**Comment by sstrubberg** [comment]
Sorry, I've been off in my own little world and haven't been paying proper attention the pipeline. 

![image](https://user-images.githubusercontent.com/15822070/102365771-89c84f00-3f7d-11eb-8828-42622d79e491.png)

We good?

**Comment by mjabbink** [comment]
Looks good. I think you can close out this issue thanks @sstrubberg
