### ISSUE TITLE
Code Block color specs are incorrect.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#989]
Current
https://gatsby-theme-carbon.now.sh/components/code-blocks#example

@aagonzales or @jeanservaas can one of you please provide color specs.

@vpicone

**Comment by mjabbink** [comment]
Current:
<img width="776" alt="Screen Shot 2020-09-10 at 3 44 29 AM" src="https://user-images.githubusercontent.com/32881239/92713926-28129c00-f321-11ea-9544-7b289f521f24.png">

**Comment by mjabbink** [comment]
Should be these colors:
<img width="696" alt="Screen Shot 2020-09-10 at 4 54 13 AM" src="https://user-images.githubusercontent.com/32881239/92714356-b8e97780-f321-11ea-99e4-951cd4ffc2c5.png">

**Comment by vpicone** [comment]
@mjabbink those are two different "languages", the top plain text and the bottom is React. I think plain text should be the dark mode `text-01` right?

**Comment by aagonzales** [comment]
Yeah better to make it all one color instead of having that red. It would be nice to add custom IDL colors though like the React code.

**Comment by vpicone** [comment]
@aagonzales we totally can, what color should that red be?

**Comment by jeanservaas** [comment]
This issue is a dupe.

https://app.zenhub.com/workspaces/auxiliary-squad-5deea70733c75ceaf1bfacae/issues/carbon-design-system/gatsby-theme-carbon/986
