### ISSUE TITLE
global: body copy width should be 8 columns wide minus 32px

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#99]
@vpicone @alisonjoseph Double check with Jeannie but I think she created this ish in Carbon site and has not yet moved here.

**Comment by alisonjoseph** [comment]
She created the issue both places https://github.com/carbon-design-system/gatsby-theme-carbon/issues/55

**Comment by mjabbink** [comment]
@alisonjoseph @vpicone Did this get done? It’s not reflected in the Gatsby them site yet.

**Comment by alisonjoseph** [comment]
I think it's in an open PR that hasn't gotten merged, I can push just this update in though now.

**Comment by mjabbink** [comment]
:+1:

**Comment by mjabbink** [comment]
@alisonjoseph @vpicone The body copy expands the full 8 columns. It should be minus 32px so it does not go all the way to the far edge of the 8th column.

**Comment by mjabbink** [comment]
What’s the status on this ish?

**Comment by mjabbink** [comment]
<img width="860" alt="Screen Shot 2019-06-04 at 8 33 36 AM" src="https://user-images.githubusercontent.com/32881239/58879456-b3739b00-86a3-11e9-9d6e-b8d86dc6786d.png">

**Comment by alisonjoseph** [comment]
Where is the above screenshot from? I checked and this seems ok in the actual theme. 
![Screen Shot 2019-06-10 at 12 50 08 PM](https://user-images.githubusercontent.com/2753488/59215225-546bc580-8b7e-11e9-9329-72fab0f10c29.png)

**Comment by mjabbink** [comment]
The above one is from brand Center 
https://www.ibm.com/brand/expression

**Comment by alisonjoseph** [comment]
got it, looks like its too much padding now. will look into it
![Screen Shot 2019-06-10 at 1 15 55 PM](https://user-images.githubusercontent.com/2753488/59216749-ecb77980-8b81-11e9-9c33-d3d057ecaefb.png)

**Comment by mjabbink** [comment]
Does look like too much now.

👍

**Comment by alisonjoseph** [comment]
got a fix in this PR https://github.com/carbon-design-system/gatsby-theme-carbon/pull/156
![Screen Shot 2019-06-10 at 1 28 12 PM](https://user-images.githubusercontent.com/2753488/59217484-a6fbb080-8b83-11e9-8ae9-87d351710ccc.png)
