### ISSUE TITLE
Bullet list content should not go beyond the body copy margin

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#990]
The bullets (en dashes) should not push the right margin out further. The bullet content should adhere to the same right margin of the body copy. Spanning 8 columns for body copy (with right side padding).

![Screen Shot 2020-09-10 at 4.53.36 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ef4c587d-68da-4776-9368-1c05ee297656)

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by mjabbink** [comment]
<img width="379" alt="Screen Shot 2020-09-10 at 3 45 32 AM" src="https://user-images.githubusercontent.com/32881239/92717700-45963480-f326-11ea-8e74-8e14634aea17.png">

<img width="378" alt="Screen Shot 2020-09-10 at 3 45 39 AM" src="https://user-images.githubusercontent.com/32881239/92717715-4cbd4280-f326-11ea-8309-dafee47d5616.png">

**Comment by mjabbink** [comment]
<img width="378" alt="Screen Shot 2020-09-10 at 3 46 35 AM" src="https://user-images.githubusercontent.com/32881239/92717740-5a72c800-f326-11ea-956b-62054916815a.png">


<img width="375" alt="Screen Shot 2020-09-10 at 3 46 44 AM" src="https://user-images.githubusercontent.com/32881239/92717750-5fd01280-f326-11ea-8aed-491422104d05.png">

**Comment by mjabbink** [comment]
Becomes very visible in Mobile

**Comment by vpicone** [comment]
@mjabbink lookin into this
