### ISSUE TITLE
Scrolling and sizing issues when in landscape and then back to Portrait site loads at small scale

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#994]
Problem in **Mobile Chrome**

— When in landscape the site moves/scrolls in all directions 
— When you flip back to portrait the site/page loads very small in browser.

...
Watch full recording:
![ezgif.com-optimize.gif](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/d1478498-d049-43b7-a096-fd65cd559775)

**Comment by mjabbink** [comment]
FYI @vpicone

**Comment by vpicone** [comment]
# Heading 1

- list 1
- list

**Comment by mjabbink** [comment]
Looks like a browser issue because other sites are behaving this way too

**Comment by vpicone** [comment]
@mjabbink I'll close this one out then
